/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.test;

import java.io.*;
import java.util.*;
import java.util.logging.*;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import com.harbormaster.delegate.*;
import com.harbormaster.entity.*;
import com.harbormaster.api.*;

/**
 * Test TimeSeries class.
 *
 * @author    Harbormaster Dev Team
 */
public class TimeSeriesTest
{

// constructors

    public TimeSeriesTest()
    {
    	LOGGER.setUseParentHandlers(false);	// only want to output to the provided LogHandler
    }

// test methods
    @Test
    /** 
     * Full Create-Read-Update-Delete of a TimeSeries, through a TimeSeriesTest.
     */
    public void testCRUD() throws Throwable {        
        try {
        	LOGGER.info( "**********************************************************" );
            LOGGER.info( "Beginning full test on TimeSeriesTest..." );
            
            testCreate();            
            testRead();        
            testUpdate();
            testGetAll();                
            testDelete();
            
            LOGGER.info( "Successfully ran a full test on TimeSeriesTest..." );
            LOGGER.info( "**********************************************************" );
            LOGGER.info( "" );
        }
        catch( Throwable e ) {
            throw e;
        }
        finally  {
        	if ( handler != null ) {
        		handler.flush();
        		LOGGER.removeHandler(handler);
        	}
        }
   }

    /** 
     * Tests creating a new TimeSeries.
     *
     * @return    TimeSeries
     */
    public TimeSeries testCreate() throws Throwable {
        TimeSeries entity = null;

        LOGGER.info( "TimeSeriesTest:testCreate()" );
        LOGGER.info( "-- Attempting to create a TimeSeries");

        StringBuilder msg = new StringBuilder( "-- Failed to create a TimeSeries" );

        try {            
            entity = TimeSeriesService.getTimeSeriesInstance().createTimeSeries( generateNewCommand() );
            assertNotNull( entity, msg.toString() );

            theId = entity.getTimeSeriesId();
            assertNotNull( theId, msg.toString() + " Contains a null primary key" );

            LOGGER.info( "-- Successfully created a TimeSeries with primary key" + theId );
        }
        catch (Exception e)  {
            LOGGER.warning( unexpectedErrorMsg );
            LOGGER.warning( msg.toString() + entity );
            
            throw e;
        }
        return entity;
    }

    /** 
     * Tests reading a TimeSeries.
     *
     * @return    TimeSeries  
     */
    public TimeSeries testRead() throws Throwable {
        LOGGER.info( "TimeSeriesTest:testRead()" );
        LOGGER.info( "-- Reading a previously created TimeSeries" );

        TimeSeries entity = null;
        StringBuilder msg = new StringBuilder( "-- Failed to read TimeSeries with primary key" );
        msg.append( theId );

        try {
            entity = TimeSeriesService.getTimeSeriesInstance().getTimeSeries( new TimeSeriesFetchOneSummary(theId) );
            
            assertNotNull( entity,msg.toString() );

            // for use later
            theId = entity.getTimeSeriesId();
            
            LOGGER.info( "-- Successfully found TimeSeries " + entity.toString() );
        }
        catch ( Throwable e ) {
            LOGGER.warning( unexpectedErrorMsg );
            LOGGER.warning( msg.toString() + " : " + e );
            
            throw e;
        }

        return( entity );
    }

    /** 
     * Tests updating a TimeSeries.
     *
     * @return    TimeSeries
     */
    public TimeSeries testUpdate() throws Throwable {
        LOGGER.info( "TimeSeriesTest:testUpdate()" );
        LOGGER.info( "-- Attempting to update a TimeSeries." );

        StringBuilder msg = new StringBuilder( "Failed to update a TimeSeries : " );        
        TimeSeries entity = null;
    
        try {            
        	UpdateTimeSeriesCommand updateCommand = this.generateUpdateCommand();
        	
        	// apply the current id as to update the fields of the current entity
        	updateCommand.setTimeSeriesId( theId );
            
            assertNotNull( updateCommand, msg.toString() );

            LOGGER.info( "-- Now updating the created TimeSeries." );
            
            TimeSeriesService proxy = TimeSeriesService.getTimeSeriesInstance();            
            entity = proxy.updateTimeSeries( updateCommand );   
            
            assertNotNull( entity, msg.toString()  );

            LOGGER.info( "-- Successfully saved TimeSeries - " + entity.toString() );
        }
        catch ( Throwable e ) {
            LOGGER.warning( unexpectedErrorMsg );
            LOGGER.warning( msg.toString() + " : primarykey-" + theId + " : entity-" +  entity + " : " + e );
            
            throw e;
        }

        return( entity );
    }

    /** 
     * Tests deleting a TimeSeries.
     */
    public void testDelete() throws Throwable {
        LOGGER.info( "TimeSeriesTest:testDelete()" );
        LOGGER.info( "-- Deleting a previously created TimeSeries." );
        
        try {
        	DeleteTimeSeriesCommand deleteCommand = new DeleteTimeSeriesCommand( theId );
        	
            TimeSeriesService.getTimeSeriesInstance().delete( deleteCommand );
            
            LOGGER.info( "-- Successfully deleted TimeSeries with primary key " + theId );            
        }
        catch ( Throwable e ) {
            LOGGER.warning( unexpectedErrorMsg );
            LOGGER.warning( "-- Failed to delete TimeSeries with primary key " + theId );
            
            throw e;
        }
    }

    /** 
     * Tests getting all TimeSeriess.
     *
     * @return    Collection
     */
    public List<TimeSeries> testGetAll() throws Throwable {    
        LOGGER.info( "TimeSeriesTest:testGetAll() - Retrieving Collection of TimeSeriess:" );

        StringBuilder msg = new StringBuilder( "-- Failed to get all TimeSeries : " );        
        List<TimeSeries> collection  = null;

        try {
            // call the static get method on the TimeSeriesService
            collection = TimeSeriesService.getTimeSeriesInstance().getAllTimeSeries();

            if ( collection == null || collection.size() == 0 ) {
                LOGGER.warning( unexpectedErrorMsg );
                LOGGER.warning( "-- " + msg.toString() + " Empty collection returned."  );
            }
            else {
	            // Now print out the values
	            TimeSeries currEntity  = null;            
	            Iterator<TimeSeries> iter = collection.iterator();
					
	            while( iter.hasNext() ) {
	                // Retrieve the entity   
	                currEntity = iter.next();
	                
	                assertNotNull( currEntity,"-- null value object in Collection." );
	                assertNotNull( currEntity.getTimeSeriesId(), "-- value object in Collection has a null primary key" );        
	
	                LOGGER.info( " - " + currEntity.toString() );
	            }
            }
        }
        catch ( Throwable e ){
            LOGGER.warning( unexpectedErrorMsg );
            LOGGER.warning( msg.toString() );
            
            throw e;
        }

        return( collection );
    }
    
    public TimeSeriesTest setHandler( Handler handler ) {
    	this.handler = handler;
    	LOGGER.addHandler(handler);	// assign so the LOGGER can only output results to the Handler
    	return this;
    }
    

	/**
	 * Returns a new populated TimeSeries
	 * 
	 * @return CreateTimeSeriesCommand alias
	 */
	protected CreateTimeSeriesCommand generateNewCommand() {
        CreateTimeSeriesCommand command = new CreateTimeSeriesCommand( null,  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),  TimeGranularity.values()[0] );
		
		return( command );
	}

		/**
		 * Returns a new populated TimeSeries
		 * 
		 * @return UpdateTimeSeriesCommand alias
		 */
	protected UpdateTimeSeriesCommand generateUpdateCommand() {
	        UpdateTimeSeriesCommand command = new UpdateTimeSeriesCommand( null,  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),  new HashSet<>(),  new HashSet<>(),  new HashSet<>(),  TimeGranularity.values()[0] );
			
			return( command );
		}
	//----
    
// attributes 

    protected UUID theId  = null;
	private final Logger LOGGER = Logger.getLogger(TimeSeries.class.getName());
	private Handler handler = null;
	private String unexpectedErrorMsg = ":::::::::::::: Unexpected Error :::::::::::::::::";
}
