/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.delegate;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.*;
import java.util.concurrent.*;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;

/**
 *
 * <h2>AccessPolicy business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of AccessPolicy related services in the case of a AccessPolicy business related service failing.</li>
 * <li>Exposes a simpler, uniform AccessPolicy interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill AccessPolicy business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
public class AccessPolicyBusinessDelegate 
extends BaseBusinessDelegate {
//************************************************************************
// Public Methods
//************************************************************************
    /** 
     * Default Constructor 
     */
    public AccessPolicyBusinessDelegate()  {
    	projector = new AccessPolicyEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
				applicationContext.getBean(AccessPolicyRepository.class) );
	}


   /**
	* AccessPolicy Business Delegate Factory Method
	*
	* All methods are expected to be self-sufficient.
	*
	* @return 	AccessPolicyBusinessDelegate
	*/
	public static AccessPolicyBusinessDelegate getAccessPolicyInstance() {
		return( new AccessPolicyBusinessDelegate() );
	}
 
   /**
    * Creates the provided command.
    * 
    * @param		command ${class.getCreateCommandAlias()}
    * @exception    ProcessingException
    * @exception	IllegalArgumentException
    * @return		AccessPolicy
    */
	public AccessPolicy createAccessPolicy( CreateAccessPolicyCommand command )
    throws ProcessingException, IllegalArgumentException {

		AccessPolicy entity = new AccessPolicy();

		try {
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	AccessPolicyValidator.getInstance().validate( command );    

            entity.setAccessPolicyId( command.getAccessPolicyId() );
            entity.setName( command.getName() );
            entity.setSubjectName( command.getSubjectName() );
            entity.setAccessLevel( command.getAccessLevel() );
            entity.setSubjectType( command.getSubjectType() );
    	    
        	// ------------------------------------------
        	// persist a new one
        	// ------------------------------------------ 
    	    entity = projector.create(entity);
    	    
			LOGGER.log( Level.INFO, "done creating of AccessPolicy {0} ", entity.toString() );
			
        }
        catch (Exception exc) {
            final String errMsg = "Unable to create AccessPolicy - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }

   /**
    * Update the provided command.
    * @param		command UpdateAccessPolicyCommand
    * @exception    ProcessingException
    * @exception  	IllegalArgumentException
    * @return		AccessPolicy
    */
    public AccessPolicy updateAccessPolicy( UpdateAccessPolicyCommand command ) 
    throws ProcessingException, IllegalArgumentException {

	    AccessPolicy entity = new AccessPolicy();

    	try {       

			// --------------------------------------
        	// validate 
        	// --------------------------------------    	
        	AccessPolicyValidator.getInstance().validate( command );    

            entity.setAccessPolicyId( command.getAccessPolicyId() );
            entity.setName( command.getName() );
            entity.setSubjectName( command.getSubjectName() );
            entity.setWorkspace( command.getWorkspace() );
            entity.setDatasets( command.getDatasets() );
            entity.setDashboards( command.getDashboards() );
            entity.setReports( command.getReports() );
            entity.setModels( command.getModels() );
            entity.setFeatureSets( command.getFeatureSets() );
            entity.setAccessLevel( command.getAccessLevel() );
            entity.setSubjectType( command.getSubjectType() );
        	
        	// ------------------------------------------
        	// persist an existing one
        	// ------------------------------------------ 
        	entity = projector.update(entity);
    	    
			LOGGER.log( Level.INFO, "done saving of AccessPolicy {0} ", entity.toString() );
    	}
        catch (Exception exc) {
            final String errMsg = "Unable to save AccessPolicy - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
    	
    	return entity;
    }
   
   /**
    * Deletes the associatied value object
    * @param		command DeleteAccessPolicyCommand
    * @exception 	ProcessingException
    */
    public void delete( DeleteAccessPolicyCommand command ) 
    throws ProcessingException, IllegalArgumentException {	
        UUID id = null;
        
    	try {  
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	AccessPolicyValidator.getInstance().validate( command );    
        
        	id = command.getAccessPolicyId();
        	
        	// ------------------------------------------
        	// delete the entity
        	// ------------------------------------------
        	projector.delete(id);

        	LOGGER.log( Level.INFO, "done deleting of AccessPolicy {0} ", id );

        }
        catch (Exception exc) {
            final String errMsg = "Unable to delete AccessPolicy using Id = "  + id;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }
    }

    /**
     * Method to retrieve the AccessPolicy via AccessPolicyFetchOneSummary
     * @param 	summary AccessPolicyFetchOneSummary 
     * @return 	AccessPolicyFetchOneResponse
     * @exception ProcessingException - Thrown if processing any related problems
     * @exception IllegalArgumentException 
     */
    public AccessPolicy getAccessPolicy( AccessPolicyFetchOneSummary summary ) 
    throws ProcessingException, IllegalArgumentException {
    	
    	if( summary == null )
    		throw new IllegalArgumentException( "AccessPolicyFetchOneSummary arg cannot be null" );
    	
    	AccessPolicy entity = null;
    	UUID id = summary.getAccessPolicyId();
    	
        try {
        	// --------------------------------------
        	// validate the fetch one summary
        	// --------------------------------------    	
        	AccessPolicyValidator.getInstance().validate( summary );    
        	
        	// --------------------------------------
        	// find a AccessPolicy using the provided id
        	// --------------------------------------
        	entity = projector.find( id );
        }
        catch( Exception exc ) {
            final String errMsg = "Unable to locate AccessPolicy with id " + id;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }


    /**
     * Method to retrieve a collection of all AccessPolicys
     *
     * @return 	List<AccessPolicy> 
     * @exception ProcessingException Thrown if any problems
     */
    public List<AccessPolicy> getAllAccessPolicy() 
    throws ProcessingException {
        List<AccessPolicy> list = null;

        try {        	
        	list = projector.findAll( new FindAllAccessPolicyQuery() );
        }
        catch( Exception exc ) {
            String errMsg = "Failed to get all AccessPolicy";
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return list;
    }

    /**
     * assign Workspace on AccessPolicy
     * @param		command AssignWorkspaceToAccessPolicyCommand	
     * @exception	ProcessingException
     */     
	public void assignWorkspace( AssignWorkspaceToAccessPolicyCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// best to validate the command now
	    	// --------------------------------------    
	    	AccessPolicyValidator.getInstance().validate( command );    

			// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.assignWorkspace(command.getAccessPolicyId(), command.getAssignment());
		    
		}
        catch( Throwable exc ) {
			final String msg = "Failed to get AnalyticsWorkspace using id " + command.getAccessPolicyId();
			LOGGER.log( Level.WARNING,  msg );
			throw new ProcessingException( msg, exc );
        }
	}

    /**
     * unAssign Workspace on AccessPolicy
     * @param		command UnAssignWorkspaceFromAccessPolicyCommand
     * @exception	ProcessingException
     */     
	public void unAssignWorkspace( UnAssignWorkspaceFromAccessPolicyCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AccessPolicyValidator.getInstance().validate( command );    
	
	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.unAssignWorkspace(command.getAccessPolicyId());
		}
		catch( Exception exc ) {
			final String msg = "Failed to unassign Workspace on AccessPolicy";
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}
	

    /**
     * add DataSet to Datasets 
     * @param		command AssignDatasetsToAccessPolicyCommand
     * @exception	ProcessingException
     */     
	public void addToDatasets( AssignDatasetsToAccessPolicyCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AccessPolicyValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToDatasets(command.getAccessPolicyId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a DataSet as Datasets to AccessPolicy" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove DataSet from Datasets
     * @param		command RemoveDatasetsFromAccessPolicyCommand
     * @exception	ProcessingException
     */     	
	public void removeFromDatasets( RemoveDatasetsFromAccessPolicyCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AccessPolicyValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromDatasets(command.getAccessPolicyId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getAccessPolicyId(); 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Dashboard to Dashboards 
     * @param		command AssignDashboardsToAccessPolicyCommand
     * @exception	ProcessingException
     */     
	public void addToDashboards( AssignDashboardsToAccessPolicyCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AccessPolicyValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToDashboards(command.getAccessPolicyId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Dashboard as Dashboards to AccessPolicy" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Dashboard from Dashboards
     * @param		command RemoveDashboardsFromAccessPolicyCommand
     * @exception	ProcessingException
     */     	
	public void removeFromDashboards( RemoveDashboardsFromAccessPolicyCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AccessPolicyValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromDashboards(command.getAccessPolicyId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getAccessPolicyId(); 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Report to Reports 
     * @param		command AssignReportsToAccessPolicyCommand
     * @exception	ProcessingException
     */     
	public void addToReports( AssignReportsToAccessPolicyCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AccessPolicyValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToReports(command.getAccessPolicyId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Report as Reports to AccessPolicy" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Report from Reports
     * @param		command RemoveReportsFromAccessPolicyCommand
     * @exception	ProcessingException
     */     	
	public void removeFromReports( RemoveReportsFromAccessPolicyCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AccessPolicyValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromReports(command.getAccessPolicyId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getAccessPolicyId(); 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Model to Models 
     * @param		command AssignModelsToAccessPolicyCommand
     * @exception	ProcessingException
     */     
	public void addToModels( AssignModelsToAccessPolicyCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AccessPolicyValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToModels(command.getAccessPolicyId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Model as Models to AccessPolicy" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Model from Models
     * @param		command RemoveModelsFromAccessPolicyCommand
     * @exception	ProcessingException
     */     	
	public void removeFromModels( RemoveModelsFromAccessPolicyCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AccessPolicyValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromModels(command.getAccessPolicyId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getAccessPolicyId(); 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add FeatureSet to FeatureSets 
     * @param		command AssignFeatureSetsToAccessPolicyCommand
     * @exception	ProcessingException
     */     
	public void addToFeatureSets( AssignFeatureSetsToAccessPolicyCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AccessPolicyValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToFeatureSets(command.getAccessPolicyId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a FeatureSet as FeatureSets to AccessPolicy" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove FeatureSet from FeatureSets
     * @param		command RemoveFeatureSetsFromAccessPolicyCommand
     * @exception	ProcessingException
     */     	
	public void removeFromFeatureSets( RemoveFeatureSetsFromAccessPolicyCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AccessPolicyValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromFeatureSets(command.getAccessPolicyId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getAccessPolicyId(); 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}





//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final AccessPolicyEntityProjector projector;
	private AccessPolicy accessPolicy 	= null;
    private static final Logger LOGGER 			= Logger.getLogger(AccessPolicyBusinessDelegate.class.getName());
    
}
