/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.delegate;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.*;
import java.util.concurrent.*;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;

/**
 *
 * <h2>BIQuery business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of BIQuery related services in the case of a BIQuery business related service failing.</li>
 * <li>Exposes a simpler, uniform BIQuery interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill BIQuery business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
public class BIQueryBusinessDelegate 
extends BaseBusinessDelegate {
//************************************************************************
// Public Methods
//************************************************************************
    /** 
     * Default Constructor 
     */
    public BIQueryBusinessDelegate()  {
    	projector = new BIQueryEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
				applicationContext.getBean(BIQueryRepository.class) );
	}


   /**
	* BIQuery Business Delegate Factory Method
	*
	* All methods are expected to be self-sufficient.
	*
	* @return 	BIQueryBusinessDelegate
	*/
	public static BIQueryBusinessDelegate getBIQueryInstance() {
		return( new BIQueryBusinessDelegate() );
	}
 
   /**
    * Creates the provided command.
    * 
    * @param		command ${class.getCreateCommandAlias()}
    * @exception    ProcessingException
    * @exception	IllegalArgumentException
    * @return		BIQuery
    */
	public BIQuery createBIQuery( CreateBIQueryCommand command )
    throws ProcessingException, IllegalArgumentException {

		BIQuery entity = new BIQuery();

		try {
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	BIQueryValidator.getInstance().validate( command );    

            entity.setBIQueryId( command.getBIQueryId() );
            entity.setName( command.getName() );
            entity.setText( command.getText() );
            entity.setDialect( command.getDialect() );
    	    
        	// ------------------------------------------
        	// persist a new one
        	// ------------------------------------------ 
    	    entity = projector.create(entity);
    	    
			LOGGER.log( Level.INFO, "done creating of BIQuery {0} ", entity.toString() );
			
        }
        catch (Exception exc) {
            final String errMsg = "Unable to create BIQuery - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }

   /**
    * Update the provided command.
    * @param		command UpdateBIQueryCommand
    * @exception    ProcessingException
    * @exception  	IllegalArgumentException
    * @return		BIQuery
    */
    public BIQuery updateBIQuery( UpdateBIQueryCommand command ) 
    throws ProcessingException, IllegalArgumentException {

	    BIQuery entity = new BIQuery();

    	try {       

			// --------------------------------------
        	// validate 
        	// --------------------------------------    	
        	BIQueryValidator.getInstance().validate( command );    

            entity.setBIQueryId( command.getBIQueryId() );
            entity.setName( command.getName() );
            entity.setText( command.getText() );
            entity.setWorkspace( command.getWorkspace() );
            entity.setDatasets( command.getDatasets() );
            entity.setReports( command.getReports() );
            entity.setDashboards( command.getDashboards() );
            entity.setNotebooks( command.getNotebooks() );
            entity.setDialect( command.getDialect() );
        	
        	// ------------------------------------------
        	// persist an existing one
        	// ------------------------------------------ 
        	entity = projector.update(entity);
    	    
			LOGGER.log( Level.INFO, "done saving of BIQuery {0} ", entity.toString() );
    	}
        catch (Exception exc) {
            final String errMsg = "Unable to save BIQuery - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
    	
    	return entity;
    }
   
   /**
    * Deletes the associatied value object
    * @param		command DeleteBIQueryCommand
    * @exception 	ProcessingException
    */
    public void delete( DeleteBIQueryCommand command ) 
    throws ProcessingException, IllegalArgumentException {	
        UUID id = null;
        
    	try {  
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	BIQueryValidator.getInstance().validate( command );    
        
        	id = command.getBIQueryId();
        	
        	// ------------------------------------------
        	// delete the entity
        	// ------------------------------------------
        	projector.delete(id);

        	LOGGER.log( Level.INFO, "done deleting of BIQuery {0} ", id );

        }
        catch (Exception exc) {
            final String errMsg = "Unable to delete BIQuery using Id = "  + id;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }
    }

    /**
     * Method to retrieve the BIQuery via BIQueryFetchOneSummary
     * @param 	summary BIQueryFetchOneSummary 
     * @return 	BIQueryFetchOneResponse
     * @exception ProcessingException - Thrown if processing any related problems
     * @exception IllegalArgumentException 
     */
    public BIQuery getBIQuery( BIQueryFetchOneSummary summary ) 
    throws ProcessingException, IllegalArgumentException {
    	
    	if( summary == null )
    		throw new IllegalArgumentException( "BIQueryFetchOneSummary arg cannot be null" );
    	
    	BIQuery entity = null;
    	UUID id = summary.getBIQueryId();
    	
        try {
        	// --------------------------------------
        	// validate the fetch one summary
        	// --------------------------------------    	
        	BIQueryValidator.getInstance().validate( summary );    
        	
        	// --------------------------------------
        	// find a BIQuery using the provided id
        	// --------------------------------------
        	entity = projector.find( id );
        }
        catch( Exception exc ) {
            final String errMsg = "Unable to locate BIQuery with id " + id;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }


    /**
     * Method to retrieve a collection of all BIQuerys
     *
     * @return 	List<BIQuery> 
     * @exception ProcessingException Thrown if any problems
     */
    public List<BIQuery> getAllBIQuery() 
    throws ProcessingException {
        List<BIQuery> list = null;

        try {        	
        	list = projector.findAll( new FindAllBIQueryQuery() );
        }
        catch( Exception exc ) {
            String errMsg = "Failed to get all BIQuery";
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return list;
    }

    /**
     * assign Workspace on BIQuery
     * @param		command AssignWorkspaceToBIQueryCommand	
     * @exception	ProcessingException
     */     
	public void assignWorkspace( AssignWorkspaceToBIQueryCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// best to validate the command now
	    	// --------------------------------------    
	    	BIQueryValidator.getInstance().validate( command );    

			// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.assignWorkspace(command.getBIQueryId(), command.getAssignment());
		    
		}
        catch( Throwable exc ) {
			final String msg = "Failed to get AnalyticsWorkspace using id " + command.getBIQueryId();
			LOGGER.log( Level.WARNING,  msg );
			throw new ProcessingException( msg, exc );
        }
	}

    /**
     * unAssign Workspace on BIQuery
     * @param		command UnAssignWorkspaceFromBIQueryCommand
     * @exception	ProcessingException
     */     
	public void unAssignWorkspace( UnAssignWorkspaceFromBIQueryCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	BIQueryValidator.getInstance().validate( command );    
	
	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.unAssignWorkspace(command.getBIQueryId());
		}
		catch( Exception exc ) {
			final String msg = "Failed to unassign Workspace on BIQuery";
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}
	

    /**
     * add DataSet to Datasets 
     * @param		command AssignDatasetsToBIQueryCommand
     * @exception	ProcessingException
     */     
	public void addToDatasets( AssignDatasetsToBIQueryCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	BIQueryValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToDatasets(command.getBIQueryId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a DataSet as Datasets to BIQuery" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove DataSet from Datasets
     * @param		command RemoveDatasetsFromBIQueryCommand
     * @exception	ProcessingException
     */     	
	public void removeFromDatasets( RemoveDatasetsFromBIQueryCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	BIQueryValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromDatasets(command.getBIQueryId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getBIQueryId(); 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Report to Reports 
     * @param		command AssignReportsToBIQueryCommand
     * @exception	ProcessingException
     */     
	public void addToReports( AssignReportsToBIQueryCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	BIQueryValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToReports(command.getBIQueryId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Report as Reports to BIQuery" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Report from Reports
     * @param		command RemoveReportsFromBIQueryCommand
     * @exception	ProcessingException
     */     	
	public void removeFromReports( RemoveReportsFromBIQueryCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	BIQueryValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromReports(command.getBIQueryId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getBIQueryId(); 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Dashboard to Dashboards 
     * @param		command AssignDashboardsToBIQueryCommand
     * @exception	ProcessingException
     */     
	public void addToDashboards( AssignDashboardsToBIQueryCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	BIQueryValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToDashboards(command.getBIQueryId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Dashboard as Dashboards to BIQuery" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Dashboard from Dashboards
     * @param		command RemoveDashboardsFromBIQueryCommand
     * @exception	ProcessingException
     */     	
	public void removeFromDashboards( RemoveDashboardsFromBIQueryCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	BIQueryValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromDashboards(command.getBIQueryId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getBIQueryId(); 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Notebook to Notebooks 
     * @param		command AssignNotebooksToBIQueryCommand
     * @exception	ProcessingException
     */     
	public void addToNotebooks( AssignNotebooksToBIQueryCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	BIQueryValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToNotebooks(command.getBIQueryId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Notebook as Notebooks to BIQuery" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Notebook from Notebooks
     * @param		command RemoveNotebooksFromBIQueryCommand
     * @exception	ProcessingException
     */     	
	public void removeFromNotebooks( RemoveNotebooksFromBIQueryCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	BIQueryValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromNotebooks(command.getBIQueryId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getBIQueryId(); 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}





//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final BIQueryEntityProjector projector;
	private BIQuery bIQuery 	= null;
    private static final Logger LOGGER 			= Logger.getLogger(BIQueryBusinessDelegate.class.getName());
    
}
