/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.delegate;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.*;
import java.util.concurrent.*;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;

/**
 *
 * <h2>DataPipeline business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of DataPipeline related services in the case of a DataPipeline business related service failing.</li>
 * <li>Exposes a simpler, uniform DataPipeline interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill DataPipeline business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
public class DataPipelineBusinessDelegate 
extends BaseBusinessDelegate {
//************************************************************************
// Public Methods
//************************************************************************
    /** 
     * Default Constructor 
     */
    public DataPipelineBusinessDelegate()  {
    	projector = new DataPipelineEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
				applicationContext.getBean(DataPipelineRepository.class) );
	}


   /**
	* DataPipeline Business Delegate Factory Method
	*
	* All methods are expected to be self-sufficient.
	*
	* @return 	DataPipelineBusinessDelegate
	*/
	public static DataPipelineBusinessDelegate getDataPipelineInstance() {
		return( new DataPipelineBusinessDelegate() );
	}
 
   /**
    * Creates the provided command.
    * 
    * @param		command ${class.getCreateCommandAlias()}
    * @exception    ProcessingException
    * @exception	IllegalArgumentException
    * @return		DataPipeline
    */
	public DataPipeline createDataPipeline( CreateDataPipelineCommand command )
    throws ProcessingException, IllegalArgumentException {

		DataPipeline entity = new DataPipeline();

		try {
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	DataPipelineValidator.getInstance().validate( command );    

            entity.setDataPipelineId( command.getDataPipelineId() );
            entity.setName( command.getName() );
            entity.setSchedule( command.getSchedule() );
            entity.setTriggerType( command.getTriggerType() );
            entity.setStatus( command.getStatus() );
    	    
        	// ------------------------------------------
        	// persist a new one
        	// ------------------------------------------ 
    	    entity = projector.create(entity);
    	    
			LOGGER.log( Level.INFO, "done creating of DataPipeline {0} ", entity.toString() );
			
        }
        catch (Exception exc) {
            final String errMsg = "Unable to create DataPipeline - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }

   /**
    * Update the provided command.
    * @param		command UpdateDataPipelineCommand
    * @exception    ProcessingException
    * @exception  	IllegalArgumentException
    * @return		DataPipeline
    */
    public DataPipeline updateDataPipeline( UpdateDataPipelineCommand command ) 
    throws ProcessingException, IllegalArgumentException {

	    DataPipeline entity = new DataPipeline();

    	try {       

			// --------------------------------------
        	// validate 
        	// --------------------------------------    	
        	DataPipelineValidator.getInstance().validate( command );    

            entity.setDataPipelineId( command.getDataPipelineId() );
            entity.setName( command.getName() );
            entity.setSchedule( command.getSchedule() );
            entity.setWorkspace( command.getWorkspace() );
            entity.setTasks( command.getTasks() );
            entity.setSources( command.getSources() );
            entity.setOutputs( command.getOutputs() );
            entity.setLineageNode( command.getLineageNode() );
            entity.setTriggerType( command.getTriggerType() );
            entity.setStatus( command.getStatus() );
        	
        	// ------------------------------------------
        	// persist an existing one
        	// ------------------------------------------ 
        	entity = projector.update(entity);
    	    
			LOGGER.log( Level.INFO, "done saving of DataPipeline {0} ", entity.toString() );
    	}
        catch (Exception exc) {
            final String errMsg = "Unable to save DataPipeline - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
    	
    	return entity;
    }
   
   /**
    * Deletes the associatied value object
    * @param		command DeleteDataPipelineCommand
    * @exception 	ProcessingException
    */
    public void delete( DeleteDataPipelineCommand command ) 
    throws ProcessingException, IllegalArgumentException {	
        UUID id = null;
        
    	try {  
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	DataPipelineValidator.getInstance().validate( command );    
        
        	id = command.getDataPipelineId();
        	
        	// ------------------------------------------
        	// delete the entity
        	// ------------------------------------------
        	projector.delete(id);

        	LOGGER.log( Level.INFO, "done deleting of DataPipeline {0} ", id );

        }
        catch (Exception exc) {
            final String errMsg = "Unable to delete DataPipeline using Id = "  + id;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }
    }

    /**
     * Method to retrieve the DataPipeline via DataPipelineFetchOneSummary
     * @param 	summary DataPipelineFetchOneSummary 
     * @return 	DataPipelineFetchOneResponse
     * @exception ProcessingException - Thrown if processing any related problems
     * @exception IllegalArgumentException 
     */
    public DataPipeline getDataPipeline( DataPipelineFetchOneSummary summary ) 
    throws ProcessingException, IllegalArgumentException {
    	
    	if( summary == null )
    		throw new IllegalArgumentException( "DataPipelineFetchOneSummary arg cannot be null" );
    	
    	DataPipeline entity = null;
    	UUID id = summary.getDataPipelineId();
    	
        try {
        	// --------------------------------------
        	// validate the fetch one summary
        	// --------------------------------------    	
        	DataPipelineValidator.getInstance().validate( summary );    
        	
        	// --------------------------------------
        	// find a DataPipeline using the provided id
        	// --------------------------------------
        	entity = projector.find( id );
        }
        catch( Exception exc ) {
            final String errMsg = "Unable to locate DataPipeline with id " + id;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }


    /**
     * Method to retrieve a collection of all DataPipelines
     *
     * @return 	List<DataPipeline> 
     * @exception ProcessingException Thrown if any problems
     */
    public List<DataPipeline> getAllDataPipeline() 
    throws ProcessingException {
        List<DataPipeline> list = null;

        try {        	
        	list = projector.findAll( new FindAllDataPipelineQuery() );
        }
        catch( Exception exc ) {
            String errMsg = "Failed to get all DataPipeline";
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return list;
    }

    /**
     * assign Workspace on DataPipeline
     * @param		command AssignWorkspaceToDataPipelineCommand	
     * @exception	ProcessingException
     */     
	public void assignWorkspace( AssignWorkspaceToDataPipelineCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// best to validate the command now
	    	// --------------------------------------    
	    	DataPipelineValidator.getInstance().validate( command );    

			// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.assignWorkspace(command.getDataPipelineId(), command.getAssignment());
		    
		}
        catch( Throwable exc ) {
			final String msg = "Failed to get AnalyticsWorkspace using id " + command.getDataPipelineId();
			LOGGER.log( Level.WARNING,  msg );
			throw new ProcessingException( msg, exc );
        }
	}

    /**
     * unAssign Workspace on DataPipeline
     * @param		command UnAssignWorkspaceFromDataPipelineCommand
     * @exception	ProcessingException
     */     
	public void unAssignWorkspace( UnAssignWorkspaceFromDataPipelineCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	DataPipelineValidator.getInstance().validate( command );    
	
	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.unAssignWorkspace(command.getDataPipelineId());
		}
		catch( Exception exc ) {
			final String msg = "Failed to unassign Workspace on DataPipeline";
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}
	
    /**
     * assign LineageNode on DataPipeline
     * @param		command AssignLineageNodeToDataPipelineCommand	
     * @exception	ProcessingException
     */     
	public void assignLineageNode( AssignLineageNodeToDataPipelineCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// best to validate the command now
	    	// --------------------------------------    
	    	DataPipelineValidator.getInstance().validate( command );    

			// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.assignLineageNode(command.getDataPipelineId(), command.getAssignment());
		    
		}
        catch( Throwable exc ) {
			final String msg = "Failed to get LineageNode using id " + command.getDataPipelineId();
			LOGGER.log( Level.WARNING,  msg );
			throw new ProcessingException( msg, exc );
        }
	}

    /**
     * unAssign LineageNode on DataPipeline
     * @param		command UnAssignLineageNodeFromDataPipelineCommand
     * @exception	ProcessingException
     */     
	public void unAssignLineageNode( UnAssignLineageNodeFromDataPipelineCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	DataPipelineValidator.getInstance().validate( command );    
	
	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.unAssignLineageNode(command.getDataPipelineId());
		}
		catch( Exception exc ) {
			final String msg = "Failed to unassign LineageNode on DataPipeline";
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}
	

    /**
     * add DataTask to Tasks 
     * @param		command AssignTasksToDataPipelineCommand
     * @exception	ProcessingException
     */     
	public void addToTasks( AssignTasksToDataPipelineCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	DataPipelineValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToTasks(command.getDataPipelineId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a DataTask as Tasks to DataPipeline" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove DataTask from Tasks
     * @param		command RemoveTasksFromDataPipelineCommand
     * @exception	ProcessingException
     */     	
	public void removeFromTasks( RemoveTasksFromDataPipelineCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	DataPipelineValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromTasks(command.getDataPipelineId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getDataPipelineId(); 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add DataSource to Sources 
     * @param		command AssignSourcesToDataPipelineCommand
     * @exception	ProcessingException
     */     
	public void addToSources( AssignSourcesToDataPipelineCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	DataPipelineValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToSources(command.getDataPipelineId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a DataSource as Sources to DataPipeline" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove DataSource from Sources
     * @param		command RemoveSourcesFromDataPipelineCommand
     * @exception	ProcessingException
     */     	
	public void removeFromSources( RemoveSourcesFromDataPipelineCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	DataPipelineValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromSources(command.getDataPipelineId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getDataPipelineId(); 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add DataSet to Outputs 
     * @param		command AssignOutputsToDataPipelineCommand
     * @exception	ProcessingException
     */     
	public void addToOutputs( AssignOutputsToDataPipelineCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	DataPipelineValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToOutputs(command.getDataPipelineId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a DataSet as Outputs to DataPipeline" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove DataSet from Outputs
     * @param		command RemoveOutputsFromDataPipelineCommand
     * @exception	ProcessingException
     */     	
	public void removeFromOutputs( RemoveOutputsFromDataPipelineCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	DataPipelineValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromOutputs(command.getDataPipelineId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getDataPipelineId(); 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}





//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final DataPipelineEntityProjector projector;
	private DataPipeline dataPipeline 	= null;
    private static final Logger LOGGER 			= Logger.getLogger(DataPipelineBusinessDelegate.class.getName());
    
}
