/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.delegate;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.*;
import java.util.concurrent.*;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;

/**
 *
 * <h2>DataTask business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of DataTask related services in the case of a DataTask business related service failing.</li>
 * <li>Exposes a simpler, uniform DataTask interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill DataTask business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
public class DataTaskBusinessDelegate 
extends BaseBusinessDelegate {
//************************************************************************
// Public Methods
//************************************************************************
    /** 
     * Default Constructor 
     */
    public DataTaskBusinessDelegate()  {
    	projector = new DataTaskEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
				applicationContext.getBean(DataTaskRepository.class) );
	}


   /**
	* DataTask Business Delegate Factory Method
	*
	* All methods are expected to be self-sufficient.
	*
	* @return 	DataTaskBusinessDelegate
	*/
	public static DataTaskBusinessDelegate getDataTaskInstance() {
		return( new DataTaskBusinessDelegate() );
	}
 
   /**
    * Creates the provided command.
    * 
    * @param		command ${class.getCreateCommandAlias()}
    * @exception    ProcessingException
    * @exception	IllegalArgumentException
    * @return		DataTask
    */
	public DataTask createDataTask( CreateDataTaskCommand command )
    throws ProcessingException, IllegalArgumentException {

		DataTask entity = new DataTask();

		try {
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	DataTaskValidator.getInstance().validate( command );    

            entity.setDataTaskId( command.getDataTaskId() );
            entity.setName( command.getName() );
            entity.setCommand( command.getCommand() );
            entity.setRetries( command.getRetries() );
            entity.setTaskType( command.getTaskType() );
    	    
        	// ------------------------------------------
        	// persist a new one
        	// ------------------------------------------ 
    	    entity = projector.create(entity);
    	    
			LOGGER.log( Level.INFO, "done creating of DataTask {0} ", entity.toString() );
			
        }
        catch (Exception exc) {
            final String errMsg = "Unable to create DataTask - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }

   /**
    * Update the provided command.
    * @param		command UpdateDataTaskCommand
    * @exception    ProcessingException
    * @exception  	IllegalArgumentException
    * @return		DataTask
    */
    public DataTask updateDataTask( UpdateDataTaskCommand command ) 
    throws ProcessingException, IllegalArgumentException {

	    DataTask entity = new DataTask();

    	try {       

			// --------------------------------------
        	// validate 
        	// --------------------------------------    	
        	DataTaskValidator.getInstance().validate( command );    

            entity.setDataTaskId( command.getDataTaskId() );
            entity.setName( command.getName() );
            entity.setCommand( command.getCommand() );
            entity.setRetries( command.getRetries() );
            entity.setPipeline( command.getPipeline() );
            entity.setInputDatasets( command.getInputDatasets() );
            entity.setOutputDatasets( command.getOutputDatasets() );
            entity.setTaskType( command.getTaskType() );
        	
        	// ------------------------------------------
        	// persist an existing one
        	// ------------------------------------------ 
        	entity = projector.update(entity);
    	    
			LOGGER.log( Level.INFO, "done saving of DataTask {0} ", entity.toString() );
    	}
        catch (Exception exc) {
            final String errMsg = "Unable to save DataTask - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
    	
    	return entity;
    }
   
   /**
    * Deletes the associatied value object
    * @param		command DeleteDataTaskCommand
    * @exception 	ProcessingException
    */
    public void delete( DeleteDataTaskCommand command ) 
    throws ProcessingException, IllegalArgumentException {	
        UUID id = null;
        
    	try {  
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	DataTaskValidator.getInstance().validate( command );    
        
        	id = command.getDataTaskId();
        	
        	// ------------------------------------------
        	// delete the entity
        	// ------------------------------------------
        	projector.delete(id);

        	LOGGER.log( Level.INFO, "done deleting of DataTask {0} ", id );

        }
        catch (Exception exc) {
            final String errMsg = "Unable to delete DataTask using Id = "  + id;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }
    }

    /**
     * Method to retrieve the DataTask via DataTaskFetchOneSummary
     * @param 	summary DataTaskFetchOneSummary 
     * @return 	DataTaskFetchOneResponse
     * @exception ProcessingException - Thrown if processing any related problems
     * @exception IllegalArgumentException 
     */
    public DataTask getDataTask( DataTaskFetchOneSummary summary ) 
    throws ProcessingException, IllegalArgumentException {
    	
    	if( summary == null )
    		throw new IllegalArgumentException( "DataTaskFetchOneSummary arg cannot be null" );
    	
    	DataTask entity = null;
    	UUID id = summary.getDataTaskId();
    	
        try {
        	// --------------------------------------
        	// validate the fetch one summary
        	// --------------------------------------    	
        	DataTaskValidator.getInstance().validate( summary );    
        	
        	// --------------------------------------
        	// find a DataTask using the provided id
        	// --------------------------------------
        	entity = projector.find( id );
        }
        catch( Exception exc ) {
            final String errMsg = "Unable to locate DataTask with id " + id;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }


    /**
     * Method to retrieve a collection of all DataTasks
     *
     * @return 	List<DataTask> 
     * @exception ProcessingException Thrown if any problems
     */
    public List<DataTask> getAllDataTask() 
    throws ProcessingException {
        List<DataTask> list = null;

        try {        	
        	list = projector.findAll( new FindAllDataTaskQuery() );
        }
        catch( Exception exc ) {
            String errMsg = "Failed to get all DataTask";
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return list;
    }

    /**
     * assign Pipeline on DataTask
     * @param		command AssignPipelineToDataTaskCommand	
     * @exception	ProcessingException
     */     
	public void assignPipeline( AssignPipelineToDataTaskCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// best to validate the command now
	    	// --------------------------------------    
	    	DataTaskValidator.getInstance().validate( command );    

			// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.assignPipeline(command.getDataTaskId(), command.getAssignment());
		    
		}
        catch( Throwable exc ) {
			final String msg = "Failed to get DataPipeline using id " + command.getDataTaskId();
			LOGGER.log( Level.WARNING,  msg );
			throw new ProcessingException( msg, exc );
        }
	}

    /**
     * unAssign Pipeline on DataTask
     * @param		command UnAssignPipelineFromDataTaskCommand
     * @exception	ProcessingException
     */     
	public void unAssignPipeline( UnAssignPipelineFromDataTaskCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	DataTaskValidator.getInstance().validate( command );    
	
	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.unAssignPipeline(command.getDataTaskId());
		}
		catch( Exception exc ) {
			final String msg = "Failed to unassign Pipeline on DataTask";
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}
	

    /**
     * add DataSet to InputDatasets 
     * @param		command AssignInputDatasetsToDataTaskCommand
     * @exception	ProcessingException
     */     
	public void addToInputDatasets( AssignInputDatasetsToDataTaskCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	DataTaskValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToInputDatasets(command.getDataTaskId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a DataSet as InputDatasets to DataTask" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove DataSet from InputDatasets
     * @param		command RemoveInputDatasetsFromDataTaskCommand
     * @exception	ProcessingException
     */     	
	public void removeFromInputDatasets( RemoveInputDatasetsFromDataTaskCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	DataTaskValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromInputDatasets(command.getDataTaskId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getDataTaskId(); 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add DataSet to OutputDatasets 
     * @param		command AssignOutputDatasetsToDataTaskCommand
     * @exception	ProcessingException
     */     
	public void addToOutputDatasets( AssignOutputDatasetsToDataTaskCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	DataTaskValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToOutputDatasets(command.getDataTaskId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a DataSet as OutputDatasets to DataTask" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove DataSet from OutputDatasets
     * @param		command RemoveOutputDatasetsFromDataTaskCommand
     * @exception	ProcessingException
     */     	
	public void removeFromOutputDatasets( RemoveOutputDatasetsFromDataTaskCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	DataTaskValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromOutputDatasets(command.getDataTaskId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getDataTaskId(); 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}





//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final DataTaskEntityProjector projector;
	private DataTask dataTask 	= null;
    private static final Logger LOGGER 			= Logger.getLogger(DataTaskBusinessDelegate.class.getName());
    
}
