/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.delegate;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.*;
import java.util.concurrent.*;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;

/**
 *
 * <h2>ModelVersion business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of ModelVersion related services in the case of a ModelVersion business related service failing.</li>
 * <li>Exposes a simpler, uniform ModelVersion interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill ModelVersion business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
public class ModelVersionBusinessDelegate 
extends BaseBusinessDelegate {
//************************************************************************
// Public Methods
//************************************************************************
    /** 
     * Default Constructor 
     */
    public ModelVersionBusinessDelegate()  {
    	projector = new ModelVersionEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
				applicationContext.getBean(ModelVersionRepository.class) );
	}


   /**
	* ModelVersion Business Delegate Factory Method
	*
	* All methods are expected to be self-sufficient.
	*
	* @return 	ModelVersionBusinessDelegate
	*/
	public static ModelVersionBusinessDelegate getModelVersionInstance() {
		return( new ModelVersionBusinessDelegate() );
	}
 
   /**
    * Creates the provided command.
    * 
    * @param		command ${class.getCreateCommandAlias()}
    * @exception    ProcessingException
    * @exception	IllegalArgumentException
    * @return		ModelVersion
    */
	public ModelVersion createModelVersion( CreateModelVersionCommand command )
    throws ProcessingException, IllegalArgumentException {

		ModelVersion entity = new ModelVersion();

		try {
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	ModelVersionValidator.getInstance().validate( command );    

            entity.setModelVersionId( command.getModelVersionId() );
            entity.setVersion( command.getVersion() );
            entity.setLifecycle( command.getLifecycle() );
            entity.setTrainingStatus( command.getTrainingStatus() );
    	    
        	// ------------------------------------------
        	// persist a new one
        	// ------------------------------------------ 
    	    entity = projector.create(entity);
    	    
			LOGGER.log( Level.INFO, "done creating of ModelVersion {0} ", entity.toString() );
			
        }
        catch (Exception exc) {
            final String errMsg = "Unable to create ModelVersion - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }

   /**
    * Update the provided command.
    * @param		command UpdateModelVersionCommand
    * @exception    ProcessingException
    * @exception  	IllegalArgumentException
    * @return		ModelVersion
    */
    public ModelVersion updateModelVersion( UpdateModelVersionCommand command ) 
    throws ProcessingException, IllegalArgumentException {

	    ModelVersion entity = new ModelVersion();

    	try {       

			// --------------------------------------
        	// validate 
        	// --------------------------------------    	
        	ModelVersionValidator.getInstance().validate( command );    

            entity.setModelVersionId( command.getModelVersionId() );
            entity.setVersion( command.getVersion() );
            entity.setModel( command.getModel() );
            entity.setTrainingRun( command.getTrainingRun() );
            entity.setEvaluationMetrics( command.getEvaluationMetrics() );
            entity.setDeployments( command.getDeployments() );
            entity.setFeatureSets( command.getFeatureSets() );
            entity.setDatasets( command.getDatasets() );
            entity.setLifecycle( command.getLifecycle() );
            entity.setTrainingStatus( command.getTrainingStatus() );
        	
        	// ------------------------------------------
        	// persist an existing one
        	// ------------------------------------------ 
        	entity = projector.update(entity);
    	    
			LOGGER.log( Level.INFO, "done saving of ModelVersion {0} ", entity.toString() );
    	}
        catch (Exception exc) {
            final String errMsg = "Unable to save ModelVersion - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
    	
    	return entity;
    }
   
   /**
    * Deletes the associatied value object
    * @param		command DeleteModelVersionCommand
    * @exception 	ProcessingException
    */
    public void delete( DeleteModelVersionCommand command ) 
    throws ProcessingException, IllegalArgumentException {	
        UUID id = null;
        
    	try {  
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	ModelVersionValidator.getInstance().validate( command );    
        
        	id = command.getModelVersionId();
        	
        	// ------------------------------------------
        	// delete the entity
        	// ------------------------------------------
        	projector.delete(id);

        	LOGGER.log( Level.INFO, "done deleting of ModelVersion {0} ", id );

        }
        catch (Exception exc) {
            final String errMsg = "Unable to delete ModelVersion using Id = "  + id;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }
    }

    /**
     * Method to retrieve the ModelVersion via ModelVersionFetchOneSummary
     * @param 	summary ModelVersionFetchOneSummary 
     * @return 	ModelVersionFetchOneResponse
     * @exception ProcessingException - Thrown if processing any related problems
     * @exception IllegalArgumentException 
     */
    public ModelVersion getModelVersion( ModelVersionFetchOneSummary summary ) 
    throws ProcessingException, IllegalArgumentException {
    	
    	if( summary == null )
    		throw new IllegalArgumentException( "ModelVersionFetchOneSummary arg cannot be null" );
    	
    	ModelVersion entity = null;
    	UUID id = summary.getModelVersionId();
    	
        try {
        	// --------------------------------------
        	// validate the fetch one summary
        	// --------------------------------------    	
        	ModelVersionValidator.getInstance().validate( summary );    
        	
        	// --------------------------------------
        	// find a ModelVersion using the provided id
        	// --------------------------------------
        	entity = projector.find( id );
        }
        catch( Exception exc ) {
            final String errMsg = "Unable to locate ModelVersion with id " + id;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }


    /**
     * Method to retrieve a collection of all ModelVersions
     *
     * @return 	List<ModelVersion> 
     * @exception ProcessingException Thrown if any problems
     */
    public List<ModelVersion> getAllModelVersion() 
    throws ProcessingException {
        List<ModelVersion> list = null;

        try {        	
        	list = projector.findAll( new FindAllModelVersionQuery() );
        }
        catch( Exception exc ) {
            String errMsg = "Failed to get all ModelVersion";
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return list;
    }

    /**
     * assign Model on ModelVersion
     * @param		command AssignModelToModelVersionCommand	
     * @exception	ProcessingException
     */     
	public void assignModel( AssignModelToModelVersionCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// best to validate the command now
	    	// --------------------------------------    
	    	ModelVersionValidator.getInstance().validate( command );    

			// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.assignModel(command.getModelVersionId(), command.getAssignment());
		    
		}
        catch( Throwable exc ) {
			final String msg = "Failed to get Model using id " + command.getModelVersionId();
			LOGGER.log( Level.WARNING,  msg );
			throw new ProcessingException( msg, exc );
        }
	}

    /**
     * unAssign Model on ModelVersion
     * @param		command UnAssignModelFromModelVersionCommand
     * @exception	ProcessingException
     */     
	public void unAssignModel( UnAssignModelFromModelVersionCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	ModelVersionValidator.getInstance().validate( command );    
	
	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.unAssignModel(command.getModelVersionId());
		}
		catch( Exception exc ) {
			final String msg = "Failed to unassign Model on ModelVersion";
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}
	
    /**
     * assign TrainingRun on ModelVersion
     * @param		command AssignTrainingRunToModelVersionCommand	
     * @exception	ProcessingException
     */     
	public void assignTrainingRun( AssignTrainingRunToModelVersionCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// best to validate the command now
	    	// --------------------------------------    
	    	ModelVersionValidator.getInstance().validate( command );    

			// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.assignTrainingRun(command.getModelVersionId(), command.getAssignment());
		    
		}
        catch( Throwable exc ) {
			final String msg = "Failed to get TrainingRun using id " + command.getModelVersionId();
			LOGGER.log( Level.WARNING,  msg );
			throw new ProcessingException( msg, exc );
        }
	}

    /**
     * unAssign TrainingRun on ModelVersion
     * @param		command UnAssignTrainingRunFromModelVersionCommand
     * @exception	ProcessingException
     */     
	public void unAssignTrainingRun( UnAssignTrainingRunFromModelVersionCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	ModelVersionValidator.getInstance().validate( command );    
	
	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.unAssignTrainingRun(command.getModelVersionId());
		}
		catch( Exception exc ) {
			final String msg = "Failed to unassign TrainingRun on ModelVersion";
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}
	

    /**
     * add EvaluationMetric to EvaluationMetrics 
     * @param		command AssignEvaluationMetricsToModelVersionCommand
     * @exception	ProcessingException
     */     
	public void addToEvaluationMetrics( AssignEvaluationMetricsToModelVersionCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	ModelVersionValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToEvaluationMetrics(command.getModelVersionId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a EvaluationMetric as EvaluationMetrics to ModelVersion" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove EvaluationMetric from EvaluationMetrics
     * @param		command RemoveEvaluationMetricsFromModelVersionCommand
     * @exception	ProcessingException
     */     	
	public void removeFromEvaluationMetrics( RemoveEvaluationMetricsFromModelVersionCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	ModelVersionValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromEvaluationMetrics(command.getModelVersionId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getModelVersionId(); 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add InferenceEndpoint to Deployments 
     * @param		command AssignDeploymentsToModelVersionCommand
     * @exception	ProcessingException
     */     
	public void addToDeployments( AssignDeploymentsToModelVersionCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	ModelVersionValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToDeployments(command.getModelVersionId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a InferenceEndpoint as Deployments to ModelVersion" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove InferenceEndpoint from Deployments
     * @param		command RemoveDeploymentsFromModelVersionCommand
     * @exception	ProcessingException
     */     	
	public void removeFromDeployments( RemoveDeploymentsFromModelVersionCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	ModelVersionValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromDeployments(command.getModelVersionId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getModelVersionId(); 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add FeatureSet to FeatureSets 
     * @param		command AssignFeatureSetsToModelVersionCommand
     * @exception	ProcessingException
     */     
	public void addToFeatureSets( AssignFeatureSetsToModelVersionCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	ModelVersionValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToFeatureSets(command.getModelVersionId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a FeatureSet as FeatureSets to ModelVersion" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove FeatureSet from FeatureSets
     * @param		command RemoveFeatureSetsFromModelVersionCommand
     * @exception	ProcessingException
     */     	
	public void removeFromFeatureSets( RemoveFeatureSetsFromModelVersionCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	ModelVersionValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromFeatureSets(command.getModelVersionId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getModelVersionId(); 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add DataSet to Datasets 
     * @param		command AssignDatasetsToModelVersionCommand
     * @exception	ProcessingException
     */     
	public void addToDatasets( AssignDatasetsToModelVersionCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	ModelVersionValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToDatasets(command.getModelVersionId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a DataSet as Datasets to ModelVersion" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove DataSet from Datasets
     * @param		command RemoveDatasetsFromModelVersionCommand
     * @exception	ProcessingException
     */     	
	public void removeFromDatasets( RemoveDatasetsFromModelVersionCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	ModelVersionValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromDatasets(command.getModelVersionId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getModelVersionId(); 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}





//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final ModelVersionEntityProjector projector;
	private ModelVersion modelVersion 	= null;
    private static final Logger LOGGER 			= Logger.getLogger(ModelVersionBusinessDelegate.class.getName());
    
}
