/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.delegate;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.*;
import java.util.concurrent.*;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;

/**
 *
 * <h2>Notebook business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of Notebook related services in the case of a Notebook business related service failing.</li>
 * <li>Exposes a simpler, uniform Notebook interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill Notebook business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
public class NotebookBusinessDelegate 
extends BaseBusinessDelegate {
//************************************************************************
// Public Methods
//************************************************************************
    /** 
     * Default Constructor 
     */
    public NotebookBusinessDelegate()  {
    	projector = new NotebookEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
				applicationContext.getBean(NotebookRepository.class) );
	}


   /**
	* Notebook Business Delegate Factory Method
	*
	* All methods are expected to be self-sufficient.
	*
	* @return 	NotebookBusinessDelegate
	*/
	public static NotebookBusinessDelegate getNotebookInstance() {
		return( new NotebookBusinessDelegate() );
	}
 
   /**
    * Creates the provided command.
    * 
    * @param		command ${class.getCreateCommandAlias()}
    * @exception    ProcessingException
    * @exception	IllegalArgumentException
    * @return		Notebook
    */
	public Notebook createNotebook( CreateNotebookCommand command )
    throws ProcessingException, IllegalArgumentException {

		Notebook entity = new Notebook();

		try {
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	NotebookValidator.getInstance().validate( command );    

            entity.setNotebookId( command.getNotebookId() );
            entity.setTitle( command.getTitle() );
            entity.setRepository( command.getRepository() );
            entity.setLanguage( command.getLanguage() );
    	    
        	// ------------------------------------------
        	// persist a new one
        	// ------------------------------------------ 
    	    entity = projector.create(entity);
    	    
			LOGGER.log( Level.INFO, "done creating of Notebook {0} ", entity.toString() );
			
        }
        catch (Exception exc) {
            final String errMsg = "Unable to create Notebook - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }

   /**
    * Update the provided command.
    * @param		command UpdateNotebookCommand
    * @exception    ProcessingException
    * @exception  	IllegalArgumentException
    * @return		Notebook
    */
    public Notebook updateNotebook( UpdateNotebookCommand command ) 
    throws ProcessingException, IllegalArgumentException {

	    Notebook entity = new Notebook();

    	try {       

			// --------------------------------------
        	// validate 
        	// --------------------------------------    	
        	NotebookValidator.getInstance().validate( command );    

            entity.setNotebookId( command.getNotebookId() );
            entity.setTitle( command.getTitle() );
            entity.setRepository( command.getRepository() );
            entity.setWorkspace( command.getWorkspace() );
            entity.setDatasets( command.getDatasets() );
            entity.setExperiments( command.getExperiments() );
            entity.setQueries( command.getQueries() );
            entity.setLanguage( command.getLanguage() );
        	
        	// ------------------------------------------
        	// persist an existing one
        	// ------------------------------------------ 
        	entity = projector.update(entity);
    	    
			LOGGER.log( Level.INFO, "done saving of Notebook {0} ", entity.toString() );
    	}
        catch (Exception exc) {
            final String errMsg = "Unable to save Notebook - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
    	
    	return entity;
    }
   
   /**
    * Deletes the associatied value object
    * @param		command DeleteNotebookCommand
    * @exception 	ProcessingException
    */
    public void delete( DeleteNotebookCommand command ) 
    throws ProcessingException, IllegalArgumentException {	
        UUID id = null;
        
    	try {  
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	NotebookValidator.getInstance().validate( command );    
        
        	id = command.getNotebookId();
        	
        	// ------------------------------------------
        	// delete the entity
        	// ------------------------------------------
        	projector.delete(id);

        	LOGGER.log( Level.INFO, "done deleting of Notebook {0} ", id );

        }
        catch (Exception exc) {
            final String errMsg = "Unable to delete Notebook using Id = "  + id;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }
    }

    /**
     * Method to retrieve the Notebook via NotebookFetchOneSummary
     * @param 	summary NotebookFetchOneSummary 
     * @return 	NotebookFetchOneResponse
     * @exception ProcessingException - Thrown if processing any related problems
     * @exception IllegalArgumentException 
     */
    public Notebook getNotebook( NotebookFetchOneSummary summary ) 
    throws ProcessingException, IllegalArgumentException {
    	
    	if( summary == null )
    		throw new IllegalArgumentException( "NotebookFetchOneSummary arg cannot be null" );
    	
    	Notebook entity = null;
    	UUID id = summary.getNotebookId();
    	
        try {
        	// --------------------------------------
        	// validate the fetch one summary
        	// --------------------------------------    	
        	NotebookValidator.getInstance().validate( summary );    
        	
        	// --------------------------------------
        	// find a Notebook using the provided id
        	// --------------------------------------
        	entity = projector.find( id );
        }
        catch( Exception exc ) {
            final String errMsg = "Unable to locate Notebook with id " + id;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }


    /**
     * Method to retrieve a collection of all Notebooks
     *
     * @return 	List<Notebook> 
     * @exception ProcessingException Thrown if any problems
     */
    public List<Notebook> getAllNotebook() 
    throws ProcessingException {
        List<Notebook> list = null;

        try {        	
        	list = projector.findAll( new FindAllNotebookQuery() );
        }
        catch( Exception exc ) {
            String errMsg = "Failed to get all Notebook";
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return list;
    }

    /**
     * assign Workspace on Notebook
     * @param		command AssignWorkspaceToNotebookCommand	
     * @exception	ProcessingException
     */     
	public void assignWorkspace( AssignWorkspaceToNotebookCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// best to validate the command now
	    	// --------------------------------------    
	    	NotebookValidator.getInstance().validate( command );    

			// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.assignWorkspace(command.getNotebookId(), command.getAssignment());
		    
		}
        catch( Throwable exc ) {
			final String msg = "Failed to get AnalyticsWorkspace using id " + command.getNotebookId();
			LOGGER.log( Level.WARNING,  msg );
			throw new ProcessingException( msg, exc );
        }
	}

    /**
     * unAssign Workspace on Notebook
     * @param		command UnAssignWorkspaceFromNotebookCommand
     * @exception	ProcessingException
     */     
	public void unAssignWorkspace( UnAssignWorkspaceFromNotebookCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	NotebookValidator.getInstance().validate( command );    
	
	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.unAssignWorkspace(command.getNotebookId());
		}
		catch( Exception exc ) {
			final String msg = "Failed to unassign Workspace on Notebook";
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}
	

    /**
     * add DataSet to Datasets 
     * @param		command AssignDatasetsToNotebookCommand
     * @exception	ProcessingException
     */     
	public void addToDatasets( AssignDatasetsToNotebookCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	NotebookValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToDatasets(command.getNotebookId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a DataSet as Datasets to Notebook" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove DataSet from Datasets
     * @param		command RemoveDatasetsFromNotebookCommand
     * @exception	ProcessingException
     */     	
	public void removeFromDatasets( RemoveDatasetsFromNotebookCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	NotebookValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromDatasets(command.getNotebookId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getNotebookId(); 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Experiment to Experiments 
     * @param		command AssignExperimentsToNotebookCommand
     * @exception	ProcessingException
     */     
	public void addToExperiments( AssignExperimentsToNotebookCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	NotebookValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToExperiments(command.getNotebookId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Experiment as Experiments to Notebook" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Experiment from Experiments
     * @param		command RemoveExperimentsFromNotebookCommand
     * @exception	ProcessingException
     */     	
	public void removeFromExperiments( RemoveExperimentsFromNotebookCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	NotebookValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromExperiments(command.getNotebookId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getNotebookId(); 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add BIQuery to Queries 
     * @param		command AssignQueriesToNotebookCommand
     * @exception	ProcessingException
     */     
	public void addToQueries( AssignQueriesToNotebookCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	NotebookValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToQueries(command.getNotebookId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a BIQuery as Queries to Notebook" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove BIQuery from Queries
     * @param		command RemoveQueriesFromNotebookCommand
     * @exception	ProcessingException
     */     	
	public void removeFromQueries( RemoveQueriesFromNotebookCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	NotebookValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromQueries(command.getNotebookId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getNotebookId(); 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}





//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final NotebookEntityProjector projector;
	private Notebook notebook 	= null;
    private static final Logger LOGGER 			= Logger.getLogger(NotebookBusinessDelegate.class.getName());
    
}
