/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.delegate;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.*;
import java.util.concurrent.*;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;

/**
 *
 * <h2>RecommendationScenario business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of RecommendationScenario related services in the case of a RecommendationScenario business related service failing.</li>
 * <li>Exposes a simpler, uniform RecommendationScenario interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill RecommendationScenario business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
public class RecommendationScenarioBusinessDelegate 
extends BaseBusinessDelegate {
//************************************************************************
// Public Methods
//************************************************************************
    /** 
     * Default Constructor 
     */
    public RecommendationScenarioBusinessDelegate()  {
    	projector = new RecommendationScenarioEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
				applicationContext.getBean(RecommendationScenarioRepository.class) );
	}


   /**
	* RecommendationScenario Business Delegate Factory Method
	*
	* All methods are expected to be self-sufficient.
	*
	* @return 	RecommendationScenarioBusinessDelegate
	*/
	public static RecommendationScenarioBusinessDelegate getRecommendationScenarioInstance() {
		return( new RecommendationScenarioBusinessDelegate() );
	}
 
   /**
    * Creates the provided command.
    * 
    * @param		command ${class.getCreateCommandAlias()}
    * @exception    ProcessingException
    * @exception	IllegalArgumentException
    * @return		RecommendationScenario
    */
	public RecommendationScenario createRecommendationScenario( CreateRecommendationScenarioCommand command )
    throws ProcessingException, IllegalArgumentException {

		RecommendationScenario entity = new RecommendationScenario();

		try {
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	RecommendationScenarioValidator.getInstance().validate( command );    

            entity.setRecommendationScenarioId( command.getRecommendationScenarioId() );
            entity.setName( command.getName() );
            entity.setObjective( command.getObjective() );
            entity.setRecommendationType( command.getRecommendationType() );
    	    
        	// ------------------------------------------
        	// persist a new one
        	// ------------------------------------------ 
    	    entity = projector.create(entity);
    	    
			LOGGER.log( Level.INFO, "done creating of RecommendationScenario {0} ", entity.toString() );
			
        }
        catch (Exception exc) {
            final String errMsg = "Unable to create RecommendationScenario - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }

   /**
    * Update the provided command.
    * @param		command UpdateRecommendationScenarioCommand
    * @exception    ProcessingException
    * @exception  	IllegalArgumentException
    * @return		RecommendationScenario
    */
    public RecommendationScenario updateRecommendationScenario( UpdateRecommendationScenarioCommand command ) 
    throws ProcessingException, IllegalArgumentException {

	    RecommendationScenario entity = new RecommendationScenario();

    	try {       

			// --------------------------------------
        	// validate 
        	// --------------------------------------    	
        	RecommendationScenarioValidator.getInstance().validate( command );    

            entity.setRecommendationScenarioId( command.getRecommendationScenarioId() );
            entity.setName( command.getName() );
            entity.setObjective( command.getObjective() );
            entity.setModels( command.getModels() );
            entity.setDatasets( command.getDatasets() );
            entity.setExperiments( command.getExperiments() );
            entity.setAlerts( command.getAlerts() );
            entity.setRecommendationType( command.getRecommendationType() );
        	
        	// ------------------------------------------
        	// persist an existing one
        	// ------------------------------------------ 
        	entity = projector.update(entity);
    	    
			LOGGER.log( Level.INFO, "done saving of RecommendationScenario {0} ", entity.toString() );
    	}
        catch (Exception exc) {
            final String errMsg = "Unable to save RecommendationScenario - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
    	
    	return entity;
    }
   
   /**
    * Deletes the associatied value object
    * @param		command DeleteRecommendationScenarioCommand
    * @exception 	ProcessingException
    */
    public void delete( DeleteRecommendationScenarioCommand command ) 
    throws ProcessingException, IllegalArgumentException {	
        UUID id = null;
        
    	try {  
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	RecommendationScenarioValidator.getInstance().validate( command );    
        
        	id = command.getRecommendationScenarioId();
        	
        	// ------------------------------------------
        	// delete the entity
        	// ------------------------------------------
        	projector.delete(id);

        	LOGGER.log( Level.INFO, "done deleting of RecommendationScenario {0} ", id );

        }
        catch (Exception exc) {
            final String errMsg = "Unable to delete RecommendationScenario using Id = "  + id;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }
    }

    /**
     * Method to retrieve the RecommendationScenario via RecommendationScenarioFetchOneSummary
     * @param 	summary RecommendationScenarioFetchOneSummary 
     * @return 	RecommendationScenarioFetchOneResponse
     * @exception ProcessingException - Thrown if processing any related problems
     * @exception IllegalArgumentException 
     */
    public RecommendationScenario getRecommendationScenario( RecommendationScenarioFetchOneSummary summary ) 
    throws ProcessingException, IllegalArgumentException {
    	
    	if( summary == null )
    		throw new IllegalArgumentException( "RecommendationScenarioFetchOneSummary arg cannot be null" );
    	
    	RecommendationScenario entity = null;
    	UUID id = summary.getRecommendationScenarioId();
    	
        try {
        	// --------------------------------------
        	// validate the fetch one summary
        	// --------------------------------------    	
        	RecommendationScenarioValidator.getInstance().validate( summary );    
        	
        	// --------------------------------------
        	// find a RecommendationScenario using the provided id
        	// --------------------------------------
        	entity = projector.find( id );
        }
        catch( Exception exc ) {
            final String errMsg = "Unable to locate RecommendationScenario with id " + id;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }


    /**
     * Method to retrieve a collection of all RecommendationScenarios
     *
     * @return 	List<RecommendationScenario> 
     * @exception ProcessingException Thrown if any problems
     */
    public List<RecommendationScenario> getAllRecommendationScenario() 
    throws ProcessingException {
        List<RecommendationScenario> list = null;

        try {        	
        	list = projector.findAll( new FindAllRecommendationScenarioQuery() );
        }
        catch( Exception exc ) {
            String errMsg = "Failed to get all RecommendationScenario";
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return list;
    }


    /**
     * add Model to Models 
     * @param		command AssignModelsToRecommendationScenarioCommand
     * @exception	ProcessingException
     */     
	public void addToModels( AssignModelsToRecommendationScenarioCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	RecommendationScenarioValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToModels(command.getRecommendationScenarioId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Model as Models to RecommendationScenario" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Model from Models
     * @param		command RemoveModelsFromRecommendationScenarioCommand
     * @exception	ProcessingException
     */     	
	public void removeFromModels( RemoveModelsFromRecommendationScenarioCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	RecommendationScenarioValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromModels(command.getRecommendationScenarioId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getRecommendationScenarioId(); 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add DataSet to Datasets 
     * @param		command AssignDatasetsToRecommendationScenarioCommand
     * @exception	ProcessingException
     */     
	public void addToDatasets( AssignDatasetsToRecommendationScenarioCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	RecommendationScenarioValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToDatasets(command.getRecommendationScenarioId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a DataSet as Datasets to RecommendationScenario" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove DataSet from Datasets
     * @param		command RemoveDatasetsFromRecommendationScenarioCommand
     * @exception	ProcessingException
     */     	
	public void removeFromDatasets( RemoveDatasetsFromRecommendationScenarioCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	RecommendationScenarioValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromDatasets(command.getRecommendationScenarioId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getRecommendationScenarioId(); 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Experiment to Experiments 
     * @param		command AssignExperimentsToRecommendationScenarioCommand
     * @exception	ProcessingException
     */     
	public void addToExperiments( AssignExperimentsToRecommendationScenarioCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	RecommendationScenarioValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToExperiments(command.getRecommendationScenarioId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Experiment as Experiments to RecommendationScenario" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Experiment from Experiments
     * @param		command RemoveExperimentsFromRecommendationScenarioCommand
     * @exception	ProcessingException
     */     	
	public void removeFromExperiments( RemoveExperimentsFromRecommendationScenarioCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	RecommendationScenarioValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromExperiments(command.getRecommendationScenarioId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getRecommendationScenarioId(); 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Alert to Alerts 
     * @param		command AssignAlertsToRecommendationScenarioCommand
     * @exception	ProcessingException
     */     
	public void addToAlerts( AssignAlertsToRecommendationScenarioCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	RecommendationScenarioValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToAlerts(command.getRecommendationScenarioId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Alert as Alerts to RecommendationScenario" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Alert from Alerts
     * @param		command RemoveAlertsFromRecommendationScenarioCommand
     * @exception	ProcessingException
     */     	
	public void removeFromAlerts( RemoveAlertsFromRecommendationScenarioCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	RecommendationScenarioValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromAlerts(command.getRecommendationScenarioId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getRecommendationScenarioId(); 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}





//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final RecommendationScenarioEntityProjector projector;
	private RecommendationScenario recommendationScenario 	= null;
    private static final Logger LOGGER 			= Logger.getLogger(RecommendationScenarioBusinessDelegate.class.getName());
    
}
