/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.validator;

import org.springframework.util.Assert;

import com.harbormaster.api.*;

/**
 * <h2>AlertValidation</h2>
 * <p>
 * The Alert Validation  handles state validation of a Alert include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateAlertCommand</li>
 *      <li>UpdateAlertCommand</li>
 *      <li>DeleteAlertCommand</li>
 *set( false = false )
  *       <li>AssignMetricToAlertCommand</li>
 *       <li>UnAssignMetricFromAlertCommand</li>
  *       <li>AssignDashboardToAlertCommand</li>
 *       <li>UnAssignDashboardFromAlertCommand</li>
  *       <li>AssignDatasetToAlertCommand</li>
 *       <li>UnAssignDatasetFromAlertCommand</li>
  *       <li>AssignRuleToAlertCommand</li>
 *       <li>UnAssignRuleFromAlertCommand</li>
   *       <li>AssignAnomaliesToAlertCommand</li>
 *       <li>RemoveAnomaliesFromAlertCommand</li>
 *   </ul>
 *
  *       <li>AssignSubscribersToAlertCommand</li>
 *       <li>RemoveSubscribersFromAlertCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class AlertValidator {
		
	/**
	 * default constructor
	 */
	protected AlertValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public AlertValidator getInstance() {
		return new AlertValidator();
	}
		
	/**
	 * handles creation validation for a Alert
	 */
	public void validate( CreateAlertCommand alert )throws Exception {
		Assert.notNull( alert, "CreateAlertCommand should not be null" );
//		Assert.isNull( alert.getAlertId(), "CreateAlertCommand identifier should be null" );
		Assert.notNull( alert.getTitle(), "Field CreateAlertCommand.title should not be null" );
		Assert.notNull( alert.getCreatedAt(), "Field CreateAlertCommand.createdAt should not be null" );
	}

	/**
	 * handles update validation for a Alert
	 */
	public void validate( UpdateAlertCommand alert ) throws Exception {
		Assert.notNull( alert, "UpdateAlertCommand should not be null" );
		Assert.notNull( alert.getAlertId(), "UpdateAlertCommand identifier should not be null" );
		Assert.notNull( alert.getTitle(), "Field UpdateAlertCommand.title should not be null" );
		Assert.notNull( alert.getCreatedAt(), "Field UpdateAlertCommand.createdAt should not be null" );
    }

	/**
	 * handles delete validation for a Alert
	 */
    public void validate( DeleteAlertCommand alert ) throws Exception {
		Assert.notNull( alert, "{commandAlias} should not be null" );
		Assert.notNull( alert.getAlertId(), "DeleteAlertCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a Alert
	 */
	public void validate( AlertFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "AlertFetchOneSummary should not be null" );
		Assert.notNull( summary.getAlertId(), "AlertFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Metric validation for a Alert
	 * 
	 * @param	command AssignMetricToAlertCommand
	 */	
	public void validate( AssignMetricToAlertCommand command ) throws Exception {
		Assert.notNull( command, "AssignMetricToAlertCommand should not be null" );
		Assert.notNull( command.getAlertId(), "AssignMetricToAlertCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignMetricToAlertCommand assignment should not be null" );
	}

	/**
	 * handles unassign Metric validation for a Alert
	 * 
	 * @param	command UnAssignMetricFromAlertCommand
	 */	
	public void validate( UnAssignMetricFromAlertCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignMetricFromAlertCommand should not be null" );
		Assert.notNull( command.getAlertId(), "UnAssignMetricFromAlertCommand identifier should not be null" );
	}
	/**
	 * handles assign Dashboard validation for a Alert
	 * 
	 * @param	command AssignDashboardToAlertCommand
	 */	
	public void validate( AssignDashboardToAlertCommand command ) throws Exception {
		Assert.notNull( command, "AssignDashboardToAlertCommand should not be null" );
		Assert.notNull( command.getAlertId(), "AssignDashboardToAlertCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignDashboardToAlertCommand assignment should not be null" );
	}

	/**
	 * handles unassign Dashboard validation for a Alert
	 * 
	 * @param	command UnAssignDashboardFromAlertCommand
	 */	
	public void validate( UnAssignDashboardFromAlertCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignDashboardFromAlertCommand should not be null" );
		Assert.notNull( command.getAlertId(), "UnAssignDashboardFromAlertCommand identifier should not be null" );
	}
	/**
	 * handles assign Dataset validation for a Alert
	 * 
	 * @param	command AssignDatasetToAlertCommand
	 */	
	public void validate( AssignDatasetToAlertCommand command ) throws Exception {
		Assert.notNull( command, "AssignDatasetToAlertCommand should not be null" );
		Assert.notNull( command.getAlertId(), "AssignDatasetToAlertCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignDatasetToAlertCommand assignment should not be null" );
	}

	/**
	 * handles unassign Dataset validation for a Alert
	 * 
	 * @param	command UnAssignDatasetFromAlertCommand
	 */	
	public void validate( UnAssignDatasetFromAlertCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignDatasetFromAlertCommand should not be null" );
		Assert.notNull( command.getAlertId(), "UnAssignDatasetFromAlertCommand identifier should not be null" );
	}
	/**
	 * handles assign Rule validation for a Alert
	 * 
	 * @param	command AssignRuleToAlertCommand
	 */	
	public void validate( AssignRuleToAlertCommand command ) throws Exception {
		Assert.notNull( command, "AssignRuleToAlertCommand should not be null" );
		Assert.notNull( command.getAlertId(), "AssignRuleToAlertCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignRuleToAlertCommand assignment should not be null" );
	}

	/**
	 * handles unassign Rule validation for a Alert
	 * 
	 * @param	command UnAssignRuleFromAlertCommand
	 */	
	public void validate( UnAssignRuleFromAlertCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignRuleFromAlertCommand should not be null" );
		Assert.notNull( command.getAlertId(), "UnAssignRuleFromAlertCommand identifier should not be null" );
	}

	/**
	 * handles add to Anomalies validation for a Alert
	 * 
	 * @param	command AssignAnomaliesToAlertCommand
	 */	
	public void validate( AssignAnomaliesToAlertCommand command ) throws Exception {
		Assert.notNull( command, "AssignAnomaliesToAlertCommand should not be null" );
		Assert.notNull( command.getAlertId(), "AssignAnomaliesToAlertCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignAnomaliesToAlertCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Anomalies validation for a Alert
	 * 
	 * @param	command RemoveAnomaliesFromAlertCommand
	 */	
	public void validate( RemoveAnomaliesFromAlertCommand command ) throws Exception {
		Assert.notNull( command, "RemoveAnomaliesFromAlertCommand should not be null" );
		Assert.notNull( command.getAlertId(), "RemoveAnomaliesFromAlertCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveAnomaliesFromAlertCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getAnomalyId(), "RemoveAnomaliesFromAlertCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to Subscribers validation for a Alert
	 * 
	 * @param	command AssignSubscribersToAlertCommand
	 */	
	public void validate( AssignSubscribersToAlertCommand command ) throws Exception {
		Assert.notNull( command, "AssignSubscribersToAlertCommand should not be null" );
		Assert.notNull( command.getAlertId(), "AssignSubscribersToAlertCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignSubscribersToAlertCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Subscribers validation for a Alert
	 * 
	 * @param	command RemoveSubscribersFromAlertCommand
	 */	
	public void validate( RemoveSubscribersFromAlertCommand command ) throws Exception {
		Assert.notNull( command, "RemoveSubscribersFromAlertCommand should not be null" );
		Assert.notNull( command.getAlertId(), "RemoveSubscribersFromAlertCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveSubscribersFromAlertCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getSubscriberId(), "RemoveSubscribersFromAlertCommand removeFrom attribubte identifier should not be null" );
	}
	

}
