/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.validator;

import org.springframework.util.Assert;

import com.harbormaster.api.*;

/**
 * <h2>FraudSignalValidation</h2>
 * <p>
 * The FraudSignal Validation  handles state validation of a FraudSignal include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateFraudSignalCommand</li>
 *      <li>UpdateFraudSignalCommand</li>
 *      <li>DeleteFraudSignalCommand</li>
 *set( false = false )
  *       <li>AssignScenarioToFraudSignalCommand</li>
 *       <li>UnAssignScenarioFromFraudSignalCommand</li>
  *       <li>AssignDatasetToFraudSignalCommand</li>
 *       <li>UnAssignDatasetFromFraudSignalCommand</li>
  *       <li>AssignModelVersionToFraudSignalCommand</li>
 *       <li>UnAssignModelVersionFromFraudSignalCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class FraudSignalValidator {
		
	/**
	 * default constructor
	 */
	protected FraudSignalValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public FraudSignalValidator getInstance() {
		return new FraudSignalValidator();
	}
		
	/**
	 * handles creation validation for a FraudSignal
	 */
	public void validate( CreateFraudSignalCommand fraudSignal )throws Exception {
		Assert.notNull( fraudSignal, "CreateFraudSignalCommand should not be null" );
//		Assert.isNull( fraudSignal.getFraudSignalId(), "CreateFraudSignalCommand identifier should be null" );
		Assert.notNull( fraudSignal.getName(), "Field CreateFraudSignalCommand.name should not be null" );
		Assert.notNull( fraudSignal.getRuleLogic(), "Field CreateFraudSignalCommand.ruleLogic should not be null" );
	}

	/**
	 * handles update validation for a FraudSignal
	 */
	public void validate( UpdateFraudSignalCommand fraudSignal ) throws Exception {
		Assert.notNull( fraudSignal, "UpdateFraudSignalCommand should not be null" );
		Assert.notNull( fraudSignal.getFraudSignalId(), "UpdateFraudSignalCommand identifier should not be null" );
		Assert.notNull( fraudSignal.getName(), "Field UpdateFraudSignalCommand.name should not be null" );
		Assert.notNull( fraudSignal.getRuleLogic(), "Field UpdateFraudSignalCommand.ruleLogic should not be null" );
    }

	/**
	 * handles delete validation for a FraudSignal
	 */
    public void validate( DeleteFraudSignalCommand fraudSignal ) throws Exception {
		Assert.notNull( fraudSignal, "{commandAlias} should not be null" );
		Assert.notNull( fraudSignal.getFraudSignalId(), "DeleteFraudSignalCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a FraudSignal
	 */
	public void validate( FraudSignalFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "FraudSignalFetchOneSummary should not be null" );
		Assert.notNull( summary.getFraudSignalId(), "FraudSignalFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Scenario validation for a FraudSignal
	 * 
	 * @param	command AssignScenarioToFraudSignalCommand
	 */	
	public void validate( AssignScenarioToFraudSignalCommand command ) throws Exception {
		Assert.notNull( command, "AssignScenarioToFraudSignalCommand should not be null" );
		Assert.notNull( command.getFraudSignalId(), "AssignScenarioToFraudSignalCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignScenarioToFraudSignalCommand assignment should not be null" );
	}

	/**
	 * handles unassign Scenario validation for a FraudSignal
	 * 
	 * @param	command UnAssignScenarioFromFraudSignalCommand
	 */	
	public void validate( UnAssignScenarioFromFraudSignalCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignScenarioFromFraudSignalCommand should not be null" );
		Assert.notNull( command.getFraudSignalId(), "UnAssignScenarioFromFraudSignalCommand identifier should not be null" );
	}
	/**
	 * handles assign Dataset validation for a FraudSignal
	 * 
	 * @param	command AssignDatasetToFraudSignalCommand
	 */	
	public void validate( AssignDatasetToFraudSignalCommand command ) throws Exception {
		Assert.notNull( command, "AssignDatasetToFraudSignalCommand should not be null" );
		Assert.notNull( command.getFraudSignalId(), "AssignDatasetToFraudSignalCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignDatasetToFraudSignalCommand assignment should not be null" );
	}

	/**
	 * handles unassign Dataset validation for a FraudSignal
	 * 
	 * @param	command UnAssignDatasetFromFraudSignalCommand
	 */	
	public void validate( UnAssignDatasetFromFraudSignalCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignDatasetFromFraudSignalCommand should not be null" );
		Assert.notNull( command.getFraudSignalId(), "UnAssignDatasetFromFraudSignalCommand identifier should not be null" );
	}
	/**
	 * handles assign ModelVersion validation for a FraudSignal
	 * 
	 * @param	command AssignModelVersionToFraudSignalCommand
	 */	
	public void validate( AssignModelVersionToFraudSignalCommand command ) throws Exception {
		Assert.notNull( command, "AssignModelVersionToFraudSignalCommand should not be null" );
		Assert.notNull( command.getFraudSignalId(), "AssignModelVersionToFraudSignalCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignModelVersionToFraudSignalCommand assignment should not be null" );
	}

	/**
	 * handles unassign ModelVersion validation for a FraudSignal
	 * 
	 * @param	command UnAssignModelVersionFromFraudSignalCommand
	 */	
	public void validate( UnAssignModelVersionFromFraudSignalCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignModelVersionFromFraudSignalCommand should not be null" );
		Assert.notNull( command.getFraudSignalId(), "UnAssignModelVersionFromFraudSignalCommand identifier should not be null" );
	}


}
