/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.validator;

import org.springframework.util.Assert;

import com.harbormaster.api.*;

/**
 * <h2>FraudScenarioValidation</h2>
 * <p>
 * The FraudScenario Validation  handles state validation of a FraudScenario include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateFraudScenarioCommand</li>
 *      <li>UpdateFraudScenarioCommand</li>
 *      <li>DeleteFraudScenarioCommand</li>
 *set( false = false )
   *       <li>AssignModelsToFraudScenarioCommand</li>
 *       <li>RemoveModelsFromFraudScenarioCommand</li>
 *   </ul>
 *
  *       <li>AssignDatasetsToFraudScenarioCommand</li>
 *       <li>RemoveDatasetsFromFraudScenarioCommand</li>
 *   </ul>
 *
  *       <li>AssignAlertsToFraudScenarioCommand</li>
 *       <li>RemoveAlertsFromFraudScenarioCommand</li>
 *   </ul>
 *
  *       <li>AssignSignalsToFraudScenarioCommand</li>
 *       <li>RemoveSignalsFromFraudScenarioCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class FraudScenarioValidator {
		
	/**
	 * default constructor
	 */
	protected FraudScenarioValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public FraudScenarioValidator getInstance() {
		return new FraudScenarioValidator();
	}
		
	/**
	 * handles creation validation for a FraudScenario
	 */
	public void validate( CreateFraudScenarioCommand fraudScenario )throws Exception {
		Assert.notNull( fraudScenario, "CreateFraudScenarioCommand should not be null" );
//		Assert.isNull( fraudScenario.getFraudScenarioId(), "CreateFraudScenarioCommand identifier should be null" );
		Assert.notNull( fraudScenario.getName(), "Field CreateFraudScenarioCommand.name should not be null" );
		Assert.notNull( fraudScenario.getRiskAppetite(), "Field CreateFraudScenarioCommand.riskAppetite should not be null" );
	}

	/**
	 * handles update validation for a FraudScenario
	 */
	public void validate( UpdateFraudScenarioCommand fraudScenario ) throws Exception {
		Assert.notNull( fraudScenario, "UpdateFraudScenarioCommand should not be null" );
		Assert.notNull( fraudScenario.getFraudScenarioId(), "UpdateFraudScenarioCommand identifier should not be null" );
		Assert.notNull( fraudScenario.getName(), "Field UpdateFraudScenarioCommand.name should not be null" );
		Assert.notNull( fraudScenario.getRiskAppetite(), "Field UpdateFraudScenarioCommand.riskAppetite should not be null" );
    }

	/**
	 * handles delete validation for a FraudScenario
	 */
    public void validate( DeleteFraudScenarioCommand fraudScenario ) throws Exception {
		Assert.notNull( fraudScenario, "{commandAlias} should not be null" );
		Assert.notNull( fraudScenario.getFraudScenarioId(), "DeleteFraudScenarioCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a FraudScenario
	 */
	public void validate( FraudScenarioFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "FraudScenarioFetchOneSummary should not be null" );
		Assert.notNull( summary.getFraudScenarioId(), "FraudScenarioFetchOneSummary identifier should not be null" );
	}


	/**
	 * handles add to Models validation for a FraudScenario
	 * 
	 * @param	command AssignModelsToFraudScenarioCommand
	 */	
	public void validate( AssignModelsToFraudScenarioCommand command ) throws Exception {
		Assert.notNull( command, "AssignModelsToFraudScenarioCommand should not be null" );
		Assert.notNull( command.getFraudScenarioId(), "AssignModelsToFraudScenarioCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignModelsToFraudScenarioCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Models validation for a FraudScenario
	 * 
	 * @param	command RemoveModelsFromFraudScenarioCommand
	 */	
	public void validate( RemoveModelsFromFraudScenarioCommand command ) throws Exception {
		Assert.notNull( command, "RemoveModelsFromFraudScenarioCommand should not be null" );
		Assert.notNull( command.getFraudScenarioId(), "RemoveModelsFromFraudScenarioCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveModelsFromFraudScenarioCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getModelId(), "RemoveModelsFromFraudScenarioCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to Datasets validation for a FraudScenario
	 * 
	 * @param	command AssignDatasetsToFraudScenarioCommand
	 */	
	public void validate( AssignDatasetsToFraudScenarioCommand command ) throws Exception {
		Assert.notNull( command, "AssignDatasetsToFraudScenarioCommand should not be null" );
		Assert.notNull( command.getFraudScenarioId(), "AssignDatasetsToFraudScenarioCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignDatasetsToFraudScenarioCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Datasets validation for a FraudScenario
	 * 
	 * @param	command RemoveDatasetsFromFraudScenarioCommand
	 */	
	public void validate( RemoveDatasetsFromFraudScenarioCommand command ) throws Exception {
		Assert.notNull( command, "RemoveDatasetsFromFraudScenarioCommand should not be null" );
		Assert.notNull( command.getFraudScenarioId(), "RemoveDatasetsFromFraudScenarioCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveDatasetsFromFraudScenarioCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getDataSetId(), "RemoveDatasetsFromFraudScenarioCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to Alerts validation for a FraudScenario
	 * 
	 * @param	command AssignAlertsToFraudScenarioCommand
	 */	
	public void validate( AssignAlertsToFraudScenarioCommand command ) throws Exception {
		Assert.notNull( command, "AssignAlertsToFraudScenarioCommand should not be null" );
		Assert.notNull( command.getFraudScenarioId(), "AssignAlertsToFraudScenarioCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignAlertsToFraudScenarioCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Alerts validation for a FraudScenario
	 * 
	 * @param	command RemoveAlertsFromFraudScenarioCommand
	 */	
	public void validate( RemoveAlertsFromFraudScenarioCommand command ) throws Exception {
		Assert.notNull( command, "RemoveAlertsFromFraudScenarioCommand should not be null" );
		Assert.notNull( command.getFraudScenarioId(), "RemoveAlertsFromFraudScenarioCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveAlertsFromFraudScenarioCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getAlertId(), "RemoveAlertsFromFraudScenarioCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to Signals validation for a FraudScenario
	 * 
	 * @param	command AssignSignalsToFraudScenarioCommand
	 */	
	public void validate( AssignSignalsToFraudScenarioCommand command ) throws Exception {
		Assert.notNull( command, "AssignSignalsToFraudScenarioCommand should not be null" );
		Assert.notNull( command.getFraudScenarioId(), "AssignSignalsToFraudScenarioCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignSignalsToFraudScenarioCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Signals validation for a FraudScenario
	 * 
	 * @param	command RemoveSignalsFromFraudScenarioCommand
	 */	
	public void validate( RemoveSignalsFromFraudScenarioCommand command ) throws Exception {
		Assert.notNull( command, "RemoveSignalsFromFraudScenarioCommand should not be null" );
		Assert.notNull( command.getFraudScenarioId(), "RemoveSignalsFromFraudScenarioCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveSignalsFromFraudScenarioCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getFraudSignalId(), "RemoveSignalsFromFraudScenarioCommand removeFrom attribubte identifier should not be null" );
	}
	

}
