/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.validator;

import org.springframework.util.Assert;

import com.harbormaster.api.*;

/**
 * <h2>MeasureValidation</h2>
 * <p>
 * The Measure Validation  handles state validation of a Measure include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateMeasureCommand</li>
 *      <li>UpdateMeasureCommand</li>
 *      <li>DeleteMeasureCommand</li>
 *set( false = false )
  *       <li>AssignSemanticModelToMeasureCommand</li>
 *       <li>UnAssignSemanticModelFromMeasureCommand</li>
   *       <li>AssignDatasetsToMeasureCommand</li>
 *       <li>RemoveDatasetsFromMeasureCommand</li>
 *   </ul>
 *
  *       <li>AssignGlossaryTermsToMeasureCommand</li>
 *       <li>RemoveGlossaryTermsFromMeasureCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class MeasureValidator {
		
	/**
	 * default constructor
	 */
	protected MeasureValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public MeasureValidator getInstance() {
		return new MeasureValidator();
	}
		
	/**
	 * handles creation validation for a Measure
	 */
	public void validate( CreateMeasureCommand measure )throws Exception {
		Assert.notNull( measure, "CreateMeasureCommand should not be null" );
//		Assert.isNull( measure.getMeasureId(), "CreateMeasureCommand identifier should be null" );
		Assert.notNull( measure.getName(), "Field CreateMeasureCommand.name should not be null" );
		Assert.notNull( measure.getFormat(), "Field CreateMeasureCommand.format should not be null" );
	}

	/**
	 * handles update validation for a Measure
	 */
	public void validate( UpdateMeasureCommand measure ) throws Exception {
		Assert.notNull( measure, "UpdateMeasureCommand should not be null" );
		Assert.notNull( measure.getMeasureId(), "UpdateMeasureCommand identifier should not be null" );
		Assert.notNull( measure.getName(), "Field UpdateMeasureCommand.name should not be null" );
		Assert.notNull( measure.getFormat(), "Field UpdateMeasureCommand.format should not be null" );
    }

	/**
	 * handles delete validation for a Measure
	 */
    public void validate( DeleteMeasureCommand measure ) throws Exception {
		Assert.notNull( measure, "{commandAlias} should not be null" );
		Assert.notNull( measure.getMeasureId(), "DeleteMeasureCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a Measure
	 */
	public void validate( MeasureFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "MeasureFetchOneSummary should not be null" );
		Assert.notNull( summary.getMeasureId(), "MeasureFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign SemanticModel validation for a Measure
	 * 
	 * @param	command AssignSemanticModelToMeasureCommand
	 */	
	public void validate( AssignSemanticModelToMeasureCommand command ) throws Exception {
		Assert.notNull( command, "AssignSemanticModelToMeasureCommand should not be null" );
		Assert.notNull( command.getMeasureId(), "AssignSemanticModelToMeasureCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignSemanticModelToMeasureCommand assignment should not be null" );
	}

	/**
	 * handles unassign SemanticModel validation for a Measure
	 * 
	 * @param	command UnAssignSemanticModelFromMeasureCommand
	 */	
	public void validate( UnAssignSemanticModelFromMeasureCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignSemanticModelFromMeasureCommand should not be null" );
		Assert.notNull( command.getMeasureId(), "UnAssignSemanticModelFromMeasureCommand identifier should not be null" );
	}

	/**
	 * handles add to Datasets validation for a Measure
	 * 
	 * @param	command AssignDatasetsToMeasureCommand
	 */	
	public void validate( AssignDatasetsToMeasureCommand command ) throws Exception {
		Assert.notNull( command, "AssignDatasetsToMeasureCommand should not be null" );
		Assert.notNull( command.getMeasureId(), "AssignDatasetsToMeasureCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignDatasetsToMeasureCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Datasets validation for a Measure
	 * 
	 * @param	command RemoveDatasetsFromMeasureCommand
	 */	
	public void validate( RemoveDatasetsFromMeasureCommand command ) throws Exception {
		Assert.notNull( command, "RemoveDatasetsFromMeasureCommand should not be null" );
		Assert.notNull( command.getMeasureId(), "RemoveDatasetsFromMeasureCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveDatasetsFromMeasureCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getDataSetId(), "RemoveDatasetsFromMeasureCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to GlossaryTerms validation for a Measure
	 * 
	 * @param	command AssignGlossaryTermsToMeasureCommand
	 */	
	public void validate( AssignGlossaryTermsToMeasureCommand command ) throws Exception {
		Assert.notNull( command, "AssignGlossaryTermsToMeasureCommand should not be null" );
		Assert.notNull( command.getMeasureId(), "AssignGlossaryTermsToMeasureCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignGlossaryTermsToMeasureCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from GlossaryTerms validation for a Measure
	 * 
	 * @param	command RemoveGlossaryTermsFromMeasureCommand
	 */	
	public void validate( RemoveGlossaryTermsFromMeasureCommand command ) throws Exception {
		Assert.notNull( command, "RemoveGlossaryTermsFromMeasureCommand should not be null" );
		Assert.notNull( command.getMeasureId(), "RemoveGlossaryTermsFromMeasureCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveGlossaryTermsFromMeasureCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getBusinessGlossaryTermId(), "RemoveGlossaryTermsFromMeasureCommand removeFrom attribubte identifier should not be null" );
	}
	

}
