/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.validator;

import org.springframework.util.Assert;

import com.harbormaster.api.*;

/**
 * <h2>NotebookValidation</h2>
 * <p>
 * The Notebook Validation  handles state validation of a Notebook include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateNotebookCommand</li>
 *      <li>UpdateNotebookCommand</li>
 *      <li>DeleteNotebookCommand</li>
 *set( false = false )
  *       <li>AssignWorkspaceToNotebookCommand</li>
 *       <li>UnAssignWorkspaceFromNotebookCommand</li>
   *       <li>AssignDatasetsToNotebookCommand</li>
 *       <li>RemoveDatasetsFromNotebookCommand</li>
 *   </ul>
 *
  *       <li>AssignExperimentsToNotebookCommand</li>
 *       <li>RemoveExperimentsFromNotebookCommand</li>
 *   </ul>
 *
  *       <li>AssignQueriesToNotebookCommand</li>
 *       <li>RemoveQueriesFromNotebookCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class NotebookValidator {
		
	/**
	 * default constructor
	 */
	protected NotebookValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public NotebookValidator getInstance() {
		return new NotebookValidator();
	}
		
	/**
	 * handles creation validation for a Notebook
	 */
	public void validate( CreateNotebookCommand notebook )throws Exception {
		Assert.notNull( notebook, "CreateNotebookCommand should not be null" );
//		Assert.isNull( notebook.getNotebookId(), "CreateNotebookCommand identifier should be null" );
		Assert.notNull( notebook.getTitle(), "Field CreateNotebookCommand.title should not be null" );
		Assert.notNull( notebook.getRepository(), "Field CreateNotebookCommand.repository should not be null" );
	}

	/**
	 * handles update validation for a Notebook
	 */
	public void validate( UpdateNotebookCommand notebook ) throws Exception {
		Assert.notNull( notebook, "UpdateNotebookCommand should not be null" );
		Assert.notNull( notebook.getNotebookId(), "UpdateNotebookCommand identifier should not be null" );
		Assert.notNull( notebook.getTitle(), "Field UpdateNotebookCommand.title should not be null" );
		Assert.notNull( notebook.getRepository(), "Field UpdateNotebookCommand.repository should not be null" );
    }

	/**
	 * handles delete validation for a Notebook
	 */
    public void validate( DeleteNotebookCommand notebook ) throws Exception {
		Assert.notNull( notebook, "{commandAlias} should not be null" );
		Assert.notNull( notebook.getNotebookId(), "DeleteNotebookCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a Notebook
	 */
	public void validate( NotebookFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "NotebookFetchOneSummary should not be null" );
		Assert.notNull( summary.getNotebookId(), "NotebookFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Workspace validation for a Notebook
	 * 
	 * @param	command AssignWorkspaceToNotebookCommand
	 */	
	public void validate( AssignWorkspaceToNotebookCommand command ) throws Exception {
		Assert.notNull( command, "AssignWorkspaceToNotebookCommand should not be null" );
		Assert.notNull( command.getNotebookId(), "AssignWorkspaceToNotebookCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignWorkspaceToNotebookCommand assignment should not be null" );
	}

	/**
	 * handles unassign Workspace validation for a Notebook
	 * 
	 * @param	command UnAssignWorkspaceFromNotebookCommand
	 */	
	public void validate( UnAssignWorkspaceFromNotebookCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignWorkspaceFromNotebookCommand should not be null" );
		Assert.notNull( command.getNotebookId(), "UnAssignWorkspaceFromNotebookCommand identifier should not be null" );
	}

	/**
	 * handles add to Datasets validation for a Notebook
	 * 
	 * @param	command AssignDatasetsToNotebookCommand
	 */	
	public void validate( AssignDatasetsToNotebookCommand command ) throws Exception {
		Assert.notNull( command, "AssignDatasetsToNotebookCommand should not be null" );
		Assert.notNull( command.getNotebookId(), "AssignDatasetsToNotebookCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignDatasetsToNotebookCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Datasets validation for a Notebook
	 * 
	 * @param	command RemoveDatasetsFromNotebookCommand
	 */	
	public void validate( RemoveDatasetsFromNotebookCommand command ) throws Exception {
		Assert.notNull( command, "RemoveDatasetsFromNotebookCommand should not be null" );
		Assert.notNull( command.getNotebookId(), "RemoveDatasetsFromNotebookCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveDatasetsFromNotebookCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getDataSetId(), "RemoveDatasetsFromNotebookCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to Experiments validation for a Notebook
	 * 
	 * @param	command AssignExperimentsToNotebookCommand
	 */	
	public void validate( AssignExperimentsToNotebookCommand command ) throws Exception {
		Assert.notNull( command, "AssignExperimentsToNotebookCommand should not be null" );
		Assert.notNull( command.getNotebookId(), "AssignExperimentsToNotebookCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignExperimentsToNotebookCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Experiments validation for a Notebook
	 * 
	 * @param	command RemoveExperimentsFromNotebookCommand
	 */	
	public void validate( RemoveExperimentsFromNotebookCommand command ) throws Exception {
		Assert.notNull( command, "RemoveExperimentsFromNotebookCommand should not be null" );
		Assert.notNull( command.getNotebookId(), "RemoveExperimentsFromNotebookCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveExperimentsFromNotebookCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getExperimentId(), "RemoveExperimentsFromNotebookCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to Queries validation for a Notebook
	 * 
	 * @param	command AssignQueriesToNotebookCommand
	 */	
	public void validate( AssignQueriesToNotebookCommand command ) throws Exception {
		Assert.notNull( command, "AssignQueriesToNotebookCommand should not be null" );
		Assert.notNull( command.getNotebookId(), "AssignQueriesToNotebookCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignQueriesToNotebookCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Queries validation for a Notebook
	 * 
	 * @param	command RemoveQueriesFromNotebookCommand
	 */	
	public void validate( RemoveQueriesFromNotebookCommand command ) throws Exception {
		Assert.notNull( command, "RemoveQueriesFromNotebookCommand should not be null" );
		Assert.notNull( command.getNotebookId(), "RemoveQueriesFromNotebookCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveQueriesFromNotebookCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getBIQueryId(), "RemoveQueriesFromNotebookCommand removeFrom attribubte identifier should not be null" );
	}
	

}
