/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.validator;

import org.springframework.util.Assert;

import com.harbormaster.api.*;

/**
 * <h2>QualityCheckValidation</h2>
 * <p>
 * The QualityCheck Validation  handles state validation of a QualityCheck include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateQualityCheckCommand</li>
 *      <li>UpdateQualityCheckCommand</li>
 *      <li>DeleteQualityCheckCommand</li>
 *set( false = false )
  *       <li>AssignRuleToQualityCheckCommand</li>
 *       <li>UnAssignRuleFromQualityCheckCommand</li>
  *       <li>AssignDatasetToQualityCheckCommand</li>
 *       <li>UnAssignDatasetFromQualityCheckCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class QualityCheckValidator {
		
	/**
	 * default constructor
	 */
	protected QualityCheckValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public QualityCheckValidator getInstance() {
		return new QualityCheckValidator();
	}
		
	/**
	 * handles creation validation for a QualityCheck
	 */
	public void validate( CreateQualityCheckCommand qualityCheck )throws Exception {
		Assert.notNull( qualityCheck, "CreateQualityCheckCommand should not be null" );
//		Assert.isNull( qualityCheck.getQualityCheckId(), "CreateQualityCheckCommand identifier should be null" );
		Assert.notNull( qualityCheck.getCheckedAt(), "Field CreateQualityCheckCommand.checkedAt should not be null" );
		Assert.notNull( qualityCheck.getObservedValue(), "Field CreateQualityCheckCommand.observedValue should not be null" );
		Assert.notNull( qualityCheck.getSampleSize(), "Field CreateQualityCheckCommand.sampleSize should not be null" );
	}

	/**
	 * handles update validation for a QualityCheck
	 */
	public void validate( UpdateQualityCheckCommand qualityCheck ) throws Exception {
		Assert.notNull( qualityCheck, "UpdateQualityCheckCommand should not be null" );
		Assert.notNull( qualityCheck.getQualityCheckId(), "UpdateQualityCheckCommand identifier should not be null" );
		Assert.notNull( qualityCheck.getCheckedAt(), "Field UpdateQualityCheckCommand.checkedAt should not be null" );
		Assert.notNull( qualityCheck.getObservedValue(), "Field UpdateQualityCheckCommand.observedValue should not be null" );
		Assert.notNull( qualityCheck.getSampleSize(), "Field UpdateQualityCheckCommand.sampleSize should not be null" );
    }

	/**
	 * handles delete validation for a QualityCheck
	 */
    public void validate( DeleteQualityCheckCommand qualityCheck ) throws Exception {
		Assert.notNull( qualityCheck, "{commandAlias} should not be null" );
		Assert.notNull( qualityCheck.getQualityCheckId(), "DeleteQualityCheckCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a QualityCheck
	 */
	public void validate( QualityCheckFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "QualityCheckFetchOneSummary should not be null" );
		Assert.notNull( summary.getQualityCheckId(), "QualityCheckFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Rule validation for a QualityCheck
	 * 
	 * @param	command AssignRuleToQualityCheckCommand
	 */	
	public void validate( AssignRuleToQualityCheckCommand command ) throws Exception {
		Assert.notNull( command, "AssignRuleToQualityCheckCommand should not be null" );
		Assert.notNull( command.getQualityCheckId(), "AssignRuleToQualityCheckCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignRuleToQualityCheckCommand assignment should not be null" );
	}

	/**
	 * handles unassign Rule validation for a QualityCheck
	 * 
	 * @param	command UnAssignRuleFromQualityCheckCommand
	 */	
	public void validate( UnAssignRuleFromQualityCheckCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignRuleFromQualityCheckCommand should not be null" );
		Assert.notNull( command.getQualityCheckId(), "UnAssignRuleFromQualityCheckCommand identifier should not be null" );
	}
	/**
	 * handles assign Dataset validation for a QualityCheck
	 * 
	 * @param	command AssignDatasetToQualityCheckCommand
	 */	
	public void validate( AssignDatasetToQualityCheckCommand command ) throws Exception {
		Assert.notNull( command, "AssignDatasetToQualityCheckCommand should not be null" );
		Assert.notNull( command.getQualityCheckId(), "AssignDatasetToQualityCheckCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignDatasetToQualityCheckCommand assignment should not be null" );
	}

	/**
	 * handles unassign Dataset validation for a QualityCheck
	 * 
	 * @param	command UnAssignDatasetFromQualityCheckCommand
	 */	
	public void validate( UnAssignDatasetFromQualityCheckCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignDatasetFromQualityCheckCommand should not be null" );
		Assert.notNull( command.getQualityCheckId(), "UnAssignDatasetFromQualityCheckCommand identifier should not be null" );
	}


}
