/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.validator;

import org.springframework.util.Assert;

import com.harbormaster.api.*;

/**
 * <h2>RunParameterValidation</h2>
 * <p>
 * The RunParameter Validation  handles state validation of a RunParameter include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateRunParameterCommand</li>
 *      <li>UpdateRunParameterCommand</li>
 *      <li>DeleteRunParameterCommand</li>
 *set( false = false )
  *       <li>AssignTrainingRunToRunParameterCommand</li>
 *       <li>UnAssignTrainingRunFromRunParameterCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class RunParameterValidator {
		
	/**
	 * default constructor
	 */
	protected RunParameterValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public RunParameterValidator getInstance() {
		return new RunParameterValidator();
	}
		
	/**
	 * handles creation validation for a RunParameter
	 */
	public void validate( CreateRunParameterCommand runParameter )throws Exception {
		Assert.notNull( runParameter, "CreateRunParameterCommand should not be null" );
//		Assert.isNull( runParameter.getRunParameterId(), "CreateRunParameterCommand identifier should be null" );
		Assert.notNull( runParameter.getName(), "Field CreateRunParameterCommand.name should not be null" );
		Assert.notNull( runParameter.getValue(), "Field CreateRunParameterCommand.value should not be null" );
	}

	/**
	 * handles update validation for a RunParameter
	 */
	public void validate( UpdateRunParameterCommand runParameter ) throws Exception {
		Assert.notNull( runParameter, "UpdateRunParameterCommand should not be null" );
		Assert.notNull( runParameter.getRunParameterId(), "UpdateRunParameterCommand identifier should not be null" );
		Assert.notNull( runParameter.getName(), "Field UpdateRunParameterCommand.name should not be null" );
		Assert.notNull( runParameter.getValue(), "Field UpdateRunParameterCommand.value should not be null" );
    }

	/**
	 * handles delete validation for a RunParameter
	 */
    public void validate( DeleteRunParameterCommand runParameter ) throws Exception {
		Assert.notNull( runParameter, "{commandAlias} should not be null" );
		Assert.notNull( runParameter.getRunParameterId(), "DeleteRunParameterCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a RunParameter
	 */
	public void validate( RunParameterFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "RunParameterFetchOneSummary should not be null" );
		Assert.notNull( summary.getRunParameterId(), "RunParameterFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign TrainingRun validation for a RunParameter
	 * 
	 * @param	command AssignTrainingRunToRunParameterCommand
	 */	
	public void validate( AssignTrainingRunToRunParameterCommand command ) throws Exception {
		Assert.notNull( command, "AssignTrainingRunToRunParameterCommand should not be null" );
		Assert.notNull( command.getRunParameterId(), "AssignTrainingRunToRunParameterCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignTrainingRunToRunParameterCommand assignment should not be null" );
	}

	/**
	 * handles unassign TrainingRun validation for a RunParameter
	 * 
	 * @param	command UnAssignTrainingRunFromRunParameterCommand
	 */	
	public void validate( UnAssignTrainingRunFromRunParameterCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignTrainingRunFromRunParameterCommand should not be null" );
		Assert.notNull( command.getRunParameterId(), "UnAssignTrainingRunFromRunParameterCommand identifier should not be null" );
	}


}
