/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.validator;

import org.springframework.util.Assert;

import com.harbormaster.api.*;

/**
 * <h2>SubscriberValidation</h2>
 * <p>
 * The Subscriber Validation  handles state validation of a Subscriber include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateSubscriberCommand</li>
 *      <li>UpdateSubscriberCommand</li>
 *      <li>DeleteSubscriberCommand</li>
 *set( false = false )
   *       <li>AssignAlertsToSubscriberCommand</li>
 *       <li>RemoveAlertsFromSubscriberCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class SubscriberValidator {
		
	/**
	 * default constructor
	 */
	protected SubscriberValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public SubscriberValidator getInstance() {
		return new SubscriberValidator();
	}
		
	/**
	 * handles creation validation for a Subscriber
	 */
	public void validate( CreateSubscriberCommand subscriber )throws Exception {
		Assert.notNull( subscriber, "CreateSubscriberCommand should not be null" );
//		Assert.isNull( subscriber.getSubscriberId(), "CreateSubscriberCommand identifier should be null" );
		Assert.notNull( subscriber.getName(), "Field CreateSubscriberCommand.name should not be null" );
		Assert.notNull( subscriber.getAddress(), "Field CreateSubscriberCommand.address should not be null" );
	}

	/**
	 * handles update validation for a Subscriber
	 */
	public void validate( UpdateSubscriberCommand subscriber ) throws Exception {
		Assert.notNull( subscriber, "UpdateSubscriberCommand should not be null" );
		Assert.notNull( subscriber.getSubscriberId(), "UpdateSubscriberCommand identifier should not be null" );
		Assert.notNull( subscriber.getName(), "Field UpdateSubscriberCommand.name should not be null" );
		Assert.notNull( subscriber.getAddress(), "Field UpdateSubscriberCommand.address should not be null" );
    }

	/**
	 * handles delete validation for a Subscriber
	 */
    public void validate( DeleteSubscriberCommand subscriber ) throws Exception {
		Assert.notNull( subscriber, "{commandAlias} should not be null" );
		Assert.notNull( subscriber.getSubscriberId(), "DeleteSubscriberCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a Subscriber
	 */
	public void validate( SubscriberFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "SubscriberFetchOneSummary should not be null" );
		Assert.notNull( summary.getSubscriberId(), "SubscriberFetchOneSummary identifier should not be null" );
	}


	/**
	 * handles add to Alerts validation for a Subscriber
	 * 
	 * @param	command AssignAlertsToSubscriberCommand
	 */	
	public void validate( AssignAlertsToSubscriberCommand command ) throws Exception {
		Assert.notNull( command, "AssignAlertsToSubscriberCommand should not be null" );
		Assert.notNull( command.getSubscriberId(), "AssignAlertsToSubscriberCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignAlertsToSubscriberCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Alerts validation for a Subscriber
	 * 
	 * @param	command RemoveAlertsFromSubscriberCommand
	 */	
	public void validate( RemoveAlertsFromSubscriberCommand command ) throws Exception {
		Assert.notNull( command, "RemoveAlertsFromSubscriberCommand should not be null" );
		Assert.notNull( command.getSubscriberId(), "RemoveAlertsFromSubscriberCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveAlertsFromSubscriberCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getAlertId(), "RemoveAlertsFromSubscriberCommand removeFrom attribubte identifier should not be null" );
	}
	

}
