/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.validator;

import org.springframework.util.Assert;

import com.harbormaster.api.*;

/**
 * <h2>TimeSeriesValidation</h2>
 * <p>
 * The TimeSeries Validation  handles state validation of a TimeSeries include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateTimeSeriesCommand</li>
 *      <li>UpdateTimeSeriesCommand</li>
 *      <li>DeleteTimeSeriesCommand</li>
 *set( false = false )
   *       <li>AssignDatasetsToTimeSeriesCommand</li>
 *       <li>RemoveDatasetsFromTimeSeriesCommand</li>
 *   </ul>
 *
  *       <li>AssignForecastsToTimeSeriesCommand</li>
 *       <li>RemoveForecastsFromTimeSeriesCommand</li>
 *   </ul>
 *
  *       <li>AssignAnomaliesToTimeSeriesCommand</li>
 *       <li>RemoveAnomaliesFromTimeSeriesCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class TimeSeriesValidator {
		
	/**
	 * default constructor
	 */
	protected TimeSeriesValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public TimeSeriesValidator getInstance() {
		return new TimeSeriesValidator();
	}
		
	/**
	 * handles creation validation for a TimeSeries
	 */
	public void validate( CreateTimeSeriesCommand timeSeries )throws Exception {
		Assert.notNull( timeSeries, "CreateTimeSeriesCommand should not be null" );
//		Assert.isNull( timeSeries.getTimeSeriesId(), "CreateTimeSeriesCommand identifier should be null" );
		Assert.notNull( timeSeries.getName(), "Field CreateTimeSeriesCommand.name should not be null" );
		Assert.notNull( timeSeries.getTimezone(), "Field CreateTimeSeriesCommand.timezone should not be null" );
	}

	/**
	 * handles update validation for a TimeSeries
	 */
	public void validate( UpdateTimeSeriesCommand timeSeries ) throws Exception {
		Assert.notNull( timeSeries, "UpdateTimeSeriesCommand should not be null" );
		Assert.notNull( timeSeries.getTimeSeriesId(), "UpdateTimeSeriesCommand identifier should not be null" );
		Assert.notNull( timeSeries.getName(), "Field UpdateTimeSeriesCommand.name should not be null" );
		Assert.notNull( timeSeries.getTimezone(), "Field UpdateTimeSeriesCommand.timezone should not be null" );
    }

	/**
	 * handles delete validation for a TimeSeries
	 */
    public void validate( DeleteTimeSeriesCommand timeSeries ) throws Exception {
		Assert.notNull( timeSeries, "{commandAlias} should not be null" );
		Assert.notNull( timeSeries.getTimeSeriesId(), "DeleteTimeSeriesCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a TimeSeries
	 */
	public void validate( TimeSeriesFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "TimeSeriesFetchOneSummary should not be null" );
		Assert.notNull( summary.getTimeSeriesId(), "TimeSeriesFetchOneSummary identifier should not be null" );
	}


	/**
	 * handles add to Datasets validation for a TimeSeries
	 * 
	 * @param	command AssignDatasetsToTimeSeriesCommand
	 */	
	public void validate( AssignDatasetsToTimeSeriesCommand command ) throws Exception {
		Assert.notNull( command, "AssignDatasetsToTimeSeriesCommand should not be null" );
		Assert.notNull( command.getTimeSeriesId(), "AssignDatasetsToTimeSeriesCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignDatasetsToTimeSeriesCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Datasets validation for a TimeSeries
	 * 
	 * @param	command RemoveDatasetsFromTimeSeriesCommand
	 */	
	public void validate( RemoveDatasetsFromTimeSeriesCommand command ) throws Exception {
		Assert.notNull( command, "RemoveDatasetsFromTimeSeriesCommand should not be null" );
		Assert.notNull( command.getTimeSeriesId(), "RemoveDatasetsFromTimeSeriesCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveDatasetsFromTimeSeriesCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getDataSetId(), "RemoveDatasetsFromTimeSeriesCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to Forecasts validation for a TimeSeries
	 * 
	 * @param	command AssignForecastsToTimeSeriesCommand
	 */	
	public void validate( AssignForecastsToTimeSeriesCommand command ) throws Exception {
		Assert.notNull( command, "AssignForecastsToTimeSeriesCommand should not be null" );
		Assert.notNull( command.getTimeSeriesId(), "AssignForecastsToTimeSeriesCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignForecastsToTimeSeriesCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Forecasts validation for a TimeSeries
	 * 
	 * @param	command RemoveForecastsFromTimeSeriesCommand
	 */	
	public void validate( RemoveForecastsFromTimeSeriesCommand command ) throws Exception {
		Assert.notNull( command, "RemoveForecastsFromTimeSeriesCommand should not be null" );
		Assert.notNull( command.getTimeSeriesId(), "RemoveForecastsFromTimeSeriesCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveForecastsFromTimeSeriesCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getForecastId(), "RemoveForecastsFromTimeSeriesCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to Anomalies validation for a TimeSeries
	 * 
	 * @param	command AssignAnomaliesToTimeSeriesCommand
	 */	
	public void validate( AssignAnomaliesToTimeSeriesCommand command ) throws Exception {
		Assert.notNull( command, "AssignAnomaliesToTimeSeriesCommand should not be null" );
		Assert.notNull( command.getTimeSeriesId(), "AssignAnomaliesToTimeSeriesCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignAnomaliesToTimeSeriesCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Anomalies validation for a TimeSeries
	 * 
	 * @param	command RemoveAnomaliesFromTimeSeriesCommand
	 */	
	public void validate( RemoveAnomaliesFromTimeSeriesCommand command ) throws Exception {
		Assert.notNull( command, "RemoveAnomaliesFromTimeSeriesCommand should not be null" );
		Assert.notNull( command.getTimeSeriesId(), "RemoveAnomaliesFromTimeSeriesCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveAnomaliesFromTimeSeriesCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getAnomalyId(), "RemoveAnomaliesFromTimeSeriesCommand removeFrom attribubte identifier should not be null" );
	}
	

}
