/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.delegate.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * AccessPolicyRestController as REST API
 *
 * <p>Exposes REST endpoints for the AccessPolicy entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	AccessPolicyBusinessDelegate
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateAccessPolicyCommand</li>
 *      <li></li>UpdateAccessPolicyCommand</li>
 *      <liDeleteAccessPolicyCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/AccessPolicy")
public class AccessPolicyRestController extends BaseSpringRestController {

    /**
     * Handles create a AccessPolicy.  if not key provided, calls create, otherwise calls save
     * @param		AccessPolicy	accessPolicy
     * @return		AccessPolicy 
     */
	@PostMapping("/create")
    public AccessPolicy create( @RequestBody(required=true) CreateAccessPolicyCommand command ) {
    	AccessPolicy entity = null;
		try {       
        	
			entity = AccessPolicyBusinessDelegate.getAccessPolicyInstance().createAccessPolicy( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return entity;
    }

    /**
     * Handles updating a AccessPolicy.  if no key provided, calls create, otherwise calls save
     * @param		AccessPolicy accessPolicy
     * @return		AccessPolicy
     */
	@PutMapping("/update")
    public AccessPolicy update( @RequestBody(required=true) UpdateAccessPolicyCommand command ) {
		AccessPolicy entity = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateAccessPolicyCommand
			// -----------------------------------------------
			entity = AccessPolicyBusinessDelegate.getAccessPolicyInstance().updateAccessPolicy(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "AccessPolicyController:update() - successfully update AccessPolicy - " + exc.getMessage());        	
	    }		
		
		return entity;
	}
 
    /**
     * Handles deleting a AccessPolicy entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteAccessPolicyCommand command ) {                
    	try {
        	AccessPolicyBusinessDelegate delegate = AccessPolicyBusinessDelegate.getAccessPolicyInstance();

        	delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted AccessPolicy with key " + command.getAccessPolicyId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }

	}        
	
    /**
     * Handles loading a AccessPolicy using a UUID
     * @param		UUID uuid 
     * @return		AccessPolicy
     */    
    @GetMapping("/load")
    public AccessPolicy load( @RequestParam(required=true) UUID uuid ) {    	
    	AccessPolicy entity = null;

    	try {  
    		entity = AccessPolicyBusinessDelegate.getAccessPolicyInstance().getAccessPolicy( new AccessPolicyFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load AccessPolicy using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all AccessPolicy business objects
     * @return		Set<AccessPolicy>
     */
    @GetMapping("/")
    public List<AccessPolicy> loadAll() {                
    	List<AccessPolicy> accessPolicyList = null;
        
    	try {
            // load the AccessPolicy
            accessPolicyList = AccessPolicyBusinessDelegate.getAccessPolicyInstance().getAllAccessPolicy();
            
            if ( accessPolicyList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all AccessPolicys" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all AccessPolicys ", exc );
        	return null;
        }

        return accessPolicyList;
                            
    }

    /**
     * save Workspace on AccessPolicy
     * @param		command AssignWorkspaceToAccessPolicyCommand
     */     
	@PutMapping("/assignWorkspace")
	public void assignWorkspace( @RequestBody AssignWorkspaceToAccessPolicyCommand command ) {
		try {
			AccessPolicyBusinessDelegate.getAccessPolicyInstance().assignWorkspace( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Workspace", exc );
        }
	}

    /**
     * unassign Workspace on AccessPolicy
     * @param		 command UnAssignWorkspaceFromAccessPolicyCommand
     */     
	@PutMapping("/unAssignWorkspace")
	public void unAssignWorkspace( @RequestBody(required=true)  UnAssignWorkspaceFromAccessPolicyCommand command ) {
		try {
			AccessPolicyBusinessDelegate.getAccessPolicyInstance().unAssignWorkspace( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Workspace", exc );
		}
	}
	

    /**
     * save Datasets on AccessPolicy
     * @param		command AssignDatasetsToAccessPolicyCommand
     */     
	@PutMapping("/addToDatasets")
	public void addToDatasets( @RequestBody(required=true) AssignDatasetsToAccessPolicyCommand command ) {
		try {
			AccessPolicyBusinessDelegate.getAccessPolicyInstance().addToDatasets( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Datasets", exc );
		}
	}

    /**
     * remove Datasets on AccessPolicy
     * @param		command RemoveDatasetsFromAccessPolicyCommand
     */     	
	@PutMapping("/removeFromDatasets")
	public void removeFromDatasets( 	@RequestBody(required=true) RemoveDatasetsFromAccessPolicyCommand command )
	{		
		try {
			AccessPolicyBusinessDelegate.getAccessPolicyInstance().removeFromDatasets( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Datasets", exc );
		}
	}

    /**
     * save Dashboards on AccessPolicy
     * @param		command AssignDashboardsToAccessPolicyCommand
     */     
	@PutMapping("/addToDashboards")
	public void addToDashboards( @RequestBody(required=true) AssignDashboardsToAccessPolicyCommand command ) {
		try {
			AccessPolicyBusinessDelegate.getAccessPolicyInstance().addToDashboards( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Dashboards", exc );
		}
	}

    /**
     * remove Dashboards on AccessPolicy
     * @param		command RemoveDashboardsFromAccessPolicyCommand
     */     	
	@PutMapping("/removeFromDashboards")
	public void removeFromDashboards( 	@RequestBody(required=true) RemoveDashboardsFromAccessPolicyCommand command )
	{		
		try {
			AccessPolicyBusinessDelegate.getAccessPolicyInstance().removeFromDashboards( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Dashboards", exc );
		}
	}

    /**
     * save Reports on AccessPolicy
     * @param		command AssignReportsToAccessPolicyCommand
     */     
	@PutMapping("/addToReports")
	public void addToReports( @RequestBody(required=true) AssignReportsToAccessPolicyCommand command ) {
		try {
			AccessPolicyBusinessDelegate.getAccessPolicyInstance().addToReports( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Reports", exc );
		}
	}

    /**
     * remove Reports on AccessPolicy
     * @param		command RemoveReportsFromAccessPolicyCommand
     */     	
	@PutMapping("/removeFromReports")
	public void removeFromReports( 	@RequestBody(required=true) RemoveReportsFromAccessPolicyCommand command )
	{		
		try {
			AccessPolicyBusinessDelegate.getAccessPolicyInstance().removeFromReports( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Reports", exc );
		}
	}

    /**
     * save Models on AccessPolicy
     * @param		command AssignModelsToAccessPolicyCommand
     */     
	@PutMapping("/addToModels")
	public void addToModels( @RequestBody(required=true) AssignModelsToAccessPolicyCommand command ) {
		try {
			AccessPolicyBusinessDelegate.getAccessPolicyInstance().addToModels( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Models", exc );
		}
	}

    /**
     * remove Models on AccessPolicy
     * @param		command RemoveModelsFromAccessPolicyCommand
     */     	
	@PutMapping("/removeFromModels")
	public void removeFromModels( 	@RequestBody(required=true) RemoveModelsFromAccessPolicyCommand command )
	{		
		try {
			AccessPolicyBusinessDelegate.getAccessPolicyInstance().removeFromModels( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Models", exc );
		}
	}

    /**
     * save FeatureSets on AccessPolicy
     * @param		command AssignFeatureSetsToAccessPolicyCommand
     */     
	@PutMapping("/addToFeatureSets")
	public void addToFeatureSets( @RequestBody(required=true) AssignFeatureSetsToAccessPolicyCommand command ) {
		try {
			AccessPolicyBusinessDelegate.getAccessPolicyInstance().addToFeatureSets( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set FeatureSets", exc );
		}
	}

    /**
     * remove FeatureSets on AccessPolicy
     * @param		command RemoveFeatureSetsFromAccessPolicyCommand
     */     	
	@PutMapping("/removeFromFeatureSets")
	public void removeFromFeatureSets( 	@RequestBody(required=true) RemoveFeatureSetsFromAccessPolicyCommand command )
	{		
		try {
			AccessPolicyBusinessDelegate.getAccessPolicyInstance().removeFromFeatureSets( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set FeatureSets", exc );
		}
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected AccessPolicy accessPolicy = null;
    private static final Logger LOGGER = Logger.getLogger(AccessPolicyRestController.class.getName());
    
}
