/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * DataSetRestController as REST API
 *
 * <p>Exposes REST endpoints for the DataSet entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	DataSetService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateDataSetCommand</li>
 *      <li></li>UpdateDataSetCommand</li>
 *      <liDeleteDataSetCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/DataSet")
public class DataSetRestController extends BaseSpringRestController {

	public DataSetRestController( DataSetService service ) {
		this.service = service;
	}
    /**
     * Handles create a DataSet.  if not key provided, calls create, otherwise calls save
     * @param		DataSet	dataSet
     * @return		DataSet 
     */
	@PostMapping("/create")
    public DataSet create( @RequestBody(required=true) CreateDataSetCommand command ) {
    	DataSet entity = null;
		try {       
        	
			entity = service.createDataSet( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return entity;
    }

    /**
     * Handles updating a DataSet.  if no key provided, calls create, otherwise calls save
     * @param		DataSet dataSet
     * @return		DataSet
     */
	@PutMapping("/update")
    public DataSet update( @RequestBody(required=true) UpdateDataSetCommand command ) {
		DataSet entity = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateDataSetCommand
			// -----------------------------------------------
			entity = service.updateDataSet(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "DataSetController:update() - successfully update DataSet - " + exc.getMessage());        	
	    }		
		
		return entity;
	}
 
    /**
     * Handles deleting a DataSet entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteDataSetCommand command ) {                
    	try {
        	DataSetService delegate = service;

        	delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted DataSet with key " + command.getDataSetId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }

	}        
	
    /**
     * Handles loading a DataSet using a UUID
     * @param		UUID uuid 
     * @return		DataSet
     */    
    @GetMapping("/load")
    public DataSet load( @RequestParam(required=true) UUID uuid ) {    	
    	DataSet entity = null;

    	try {  
    		entity = service.getDataSet( new DataSetFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load DataSet using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all DataSet business objects
     * @return		Set<DataSet>
     */
    @GetMapping("/")
    public List<DataSet> loadAll() {                
    	List<DataSet> dataSetList = null;
        
    	try {
            // load the DataSet
            dataSetList = service.getAllDataSet();
            
            if ( dataSetList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all DataSets" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all DataSets ", exc );
        	return null;
        }

        return dataSetList;
                            
    }

    /**
     * save Workspace on DataSet
     * @param		command AssignWorkspaceToDataSetCommand
     */     
	@PutMapping("/assignWorkspace")
	public void assignWorkspace( @RequestBody AssignWorkspaceToDataSetCommand command ) {
		try {
			service.assignWorkspace( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Workspace", exc );
        }
	}

    /**
     * unassign Workspace on DataSet
     * @param		 command UnAssignWorkspaceFromDataSetCommand
     */     
	@PutMapping("/unAssignWorkspace")
	public void unAssignWorkspace( @RequestBody(required=true)  UnAssignWorkspaceFromDataSetCommand command ) {
		try {
			service.unAssignWorkspace( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Workspace", exc );
		}
	}
	
    /**
     * save LineageNode on DataSet
     * @param		command AssignLineageNodeToDataSetCommand
     */     
	@PutMapping("/assignLineageNode")
	public void assignLineageNode( @RequestBody AssignLineageNodeToDataSetCommand command ) {
		try {
			service.assignLineageNode( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign LineageNode", exc );
        }
	}

    /**
     * unassign LineageNode on DataSet
     * @param		 command UnAssignLineageNodeFromDataSetCommand
     */     
	@PutMapping("/unAssignLineageNode")
	public void unAssignLineageNode( @RequestBody(required=true)  UnAssignLineageNodeFromDataSetCommand command ) {
		try {
			service.unAssignLineageNode( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign LineageNode", exc );
		}
	}
	

    /**
     * save Sources on DataSet
     * @param		command AssignSourcesToDataSetCommand
     */     
	@PutMapping("/addToSources")
	public void addToSources( @RequestBody(required=true) AssignSourcesToDataSetCommand command ) {
		try {
			service.addToSources( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Sources", exc );
		}
	}

    /**
     * remove Sources on DataSet
     * @param		command RemoveSourcesFromDataSetCommand
     */     	
	@PutMapping("/removeFromSources")
	public void removeFromSources( 	@RequestBody(required=true) RemoveSourcesFromDataSetCommand command )
	{		
		try {
			service.removeFromSources( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Sources", exc );
		}
	}

    /**
     * save Pipelines on DataSet
     * @param		command AssignPipelinesToDataSetCommand
     */     
	@PutMapping("/addToPipelines")
	public void addToPipelines( @RequestBody(required=true) AssignPipelinesToDataSetCommand command ) {
		try {
			service.addToPipelines( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Pipelines", exc );
		}
	}

    /**
     * remove Pipelines on DataSet
     * @param		command RemovePipelinesFromDataSetCommand
     */     	
	@PutMapping("/removeFromPipelines")
	public void removeFromPipelines( 	@RequestBody(required=true) RemovePipelinesFromDataSetCommand command )
	{		
		try {
			service.removeFromPipelines( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Pipelines", exc );
		}
	}

    /**
     * save SemanticModels on DataSet
     * @param		command AssignSemanticModelsToDataSetCommand
     */     
	@PutMapping("/addToSemanticModels")
	public void addToSemanticModels( @RequestBody(required=true) AssignSemanticModelsToDataSetCommand command ) {
		try {
			service.addToSemanticModels( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set SemanticModels", exc );
		}
	}

    /**
     * remove SemanticModels on DataSet
     * @param		command RemoveSemanticModelsFromDataSetCommand
     */     	
	@PutMapping("/removeFromSemanticModels")
	public void removeFromSemanticModels( 	@RequestBody(required=true) RemoveSemanticModelsFromDataSetCommand command )
	{		
		try {
			service.removeFromSemanticModels( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set SemanticModels", exc );
		}
	}

    /**
     * save Dimensions on DataSet
     * @param		command AssignDimensionsToDataSetCommand
     */     
	@PutMapping("/addToDimensions")
	public void addToDimensions( @RequestBody(required=true) AssignDimensionsToDataSetCommand command ) {
		try {
			service.addToDimensions( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Dimensions", exc );
		}
	}

    /**
     * remove Dimensions on DataSet
     * @param		command RemoveDimensionsFromDataSetCommand
     */     	
	@PutMapping("/removeFromDimensions")
	public void removeFromDimensions( 	@RequestBody(required=true) RemoveDimensionsFromDataSetCommand command )
	{		
		try {
			service.removeFromDimensions( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Dimensions", exc );
		}
	}

    /**
     * save Measures on DataSet
     * @param		command AssignMeasuresToDataSetCommand
     */     
	@PutMapping("/addToMeasures")
	public void addToMeasures( @RequestBody(required=true) AssignMeasuresToDataSetCommand command ) {
		try {
			service.addToMeasures( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Measures", exc );
		}
	}

    /**
     * remove Measures on DataSet
     * @param		command RemoveMeasuresFromDataSetCommand
     */     	
	@PutMapping("/removeFromMeasures")
	public void removeFromMeasures( 	@RequestBody(required=true) RemoveMeasuresFromDataSetCommand command )
	{		
		try {
			service.removeFromMeasures( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Measures", exc );
		}
	}

    /**
     * save Metrics on DataSet
     * @param		command AssignMetricsToDataSetCommand
     */     
	@PutMapping("/addToMetrics")
	public void addToMetrics( @RequestBody(required=true) AssignMetricsToDataSetCommand command ) {
		try {
			service.addToMetrics( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Metrics", exc );
		}
	}

    /**
     * remove Metrics on DataSet
     * @param		command RemoveMetricsFromDataSetCommand
     */     	
	@PutMapping("/removeFromMetrics")
	public void removeFromMetrics( 	@RequestBody(required=true) RemoveMetricsFromDataSetCommand command )
	{		
		try {
			service.removeFromMetrics( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Metrics", exc );
		}
	}

    /**
     * save QualityRules on DataSet
     * @param		command AssignQualityRulesToDataSetCommand
     */     
	@PutMapping("/addToQualityRules")
	public void addToQualityRules( @RequestBody(required=true) AssignQualityRulesToDataSetCommand command ) {
		try {
			service.addToQualityRules( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set QualityRules", exc );
		}
	}

    /**
     * remove QualityRules on DataSet
     * @param		command RemoveQualityRulesFromDataSetCommand
     */     	
	@PutMapping("/removeFromQualityRules")
	public void removeFromQualityRules( 	@RequestBody(required=true) RemoveQualityRulesFromDataSetCommand command )
	{		
		try {
			service.removeFromQualityRules( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set QualityRules", exc );
		}
	}

    /**
     * save Tags on DataSet
     * @param		command AssignTagsToDataSetCommand
     */     
	@PutMapping("/addToTags")
	public void addToTags( @RequestBody(required=true) AssignTagsToDataSetCommand command ) {
		try {
			service.addToTags( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Tags", exc );
		}
	}

    /**
     * remove Tags on DataSet
     * @param		command RemoveTagsFromDataSetCommand
     */     	
	@PutMapping("/removeFromTags")
	public void removeFromTags( 	@RequestBody(required=true) RemoveTagsFromDataSetCommand command )
	{		
		try {
			service.removeFromTags( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Tags", exc );
		}
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected DataSet dataSet = null;
	protected DataSetService service = null;
    private static final Logger LOGGER = Logger.getLogger(DataSetRestController.class.getName());
    
}
