/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.delegate.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * FeatureSetRestController as REST API
 *
 * <p>Exposes REST endpoints for the FeatureSet entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	FeatureSetBusinessDelegate
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateFeatureSetCommand</li>
 *      <li></li>UpdateFeatureSetCommand</li>
 *      <liDeleteFeatureSetCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/FeatureSet")
public class FeatureSetRestController extends BaseSpringRestController {

    /**
     * Handles create a FeatureSet.  if not key provided, calls create, otherwise calls save
     * @param		FeatureSet	featureSet
     * @return		FeatureSet 
     */
	@PostMapping("/create")
    public FeatureSet create( @RequestBody(required=true) CreateFeatureSetCommand command ) {
    	FeatureSet entity = null;
		try {       
        	
			entity = FeatureSetBusinessDelegate.getFeatureSetInstance().createFeatureSet( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return entity;
    }

    /**
     * Handles updating a FeatureSet.  if no key provided, calls create, otherwise calls save
     * @param		FeatureSet featureSet
     * @return		FeatureSet
     */
	@PutMapping("/update")
    public FeatureSet update( @RequestBody(required=true) UpdateFeatureSetCommand command ) {
		FeatureSet entity = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateFeatureSetCommand
			// -----------------------------------------------
			entity = FeatureSetBusinessDelegate.getFeatureSetInstance().updateFeatureSet(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "FeatureSetController:update() - successfully update FeatureSet - " + exc.getMessage());        	
	    }		
		
		return entity;
	}
 
    /**
     * Handles deleting a FeatureSet entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteFeatureSetCommand command ) {                
    	try {
        	FeatureSetBusinessDelegate delegate = FeatureSetBusinessDelegate.getFeatureSetInstance();

        	delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted FeatureSet with key " + command.getFeatureSetId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }

	}        
	
    /**
     * Handles loading a FeatureSet using a UUID
     * @param		UUID uuid 
     * @return		FeatureSet
     */    
    @GetMapping("/load")
    public FeatureSet load( @RequestParam(required=true) UUID uuid ) {    	
    	FeatureSet entity = null;

    	try {  
    		entity = FeatureSetBusinessDelegate.getFeatureSetInstance().getFeatureSet( new FeatureSetFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load FeatureSet using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all FeatureSet business objects
     * @return		Set<FeatureSet>
     */
    @GetMapping("/")
    public List<FeatureSet> loadAll() {                
    	List<FeatureSet> featureSetList = null;
        
    	try {
            // load the FeatureSet
            featureSetList = FeatureSetBusinessDelegate.getFeatureSetInstance().getAllFeatureSet();
            
            if ( featureSetList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all FeatureSets" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all FeatureSets ", exc );
        	return null;
        }

        return featureSetList;
                            
    }

    /**
     * save Workspace on FeatureSet
     * @param		command AssignWorkspaceToFeatureSetCommand
     */     
	@PutMapping("/assignWorkspace")
	public void assignWorkspace( @RequestBody AssignWorkspaceToFeatureSetCommand command ) {
		try {
			FeatureSetBusinessDelegate.getFeatureSetInstance().assignWorkspace( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Workspace", exc );
        }
	}

    /**
     * unassign Workspace on FeatureSet
     * @param		 command UnAssignWorkspaceFromFeatureSetCommand
     */     
	@PutMapping("/unAssignWorkspace")
	public void unAssignWorkspace( @RequestBody(required=true)  UnAssignWorkspaceFromFeatureSetCommand command ) {
		try {
			FeatureSetBusinessDelegate.getFeatureSetInstance().unAssignWorkspace( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Workspace", exc );
		}
	}
	

    /**
     * save Features on FeatureSet
     * @param		command AssignFeaturesToFeatureSetCommand
     */     
	@PutMapping("/addToFeatures")
	public void addToFeatures( @RequestBody(required=true) AssignFeaturesToFeatureSetCommand command ) {
		try {
			FeatureSetBusinessDelegate.getFeatureSetInstance().addToFeatures( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Features", exc );
		}
	}

    /**
     * remove Features on FeatureSet
     * @param		command RemoveFeaturesFromFeatureSetCommand
     */     	
	@PutMapping("/removeFromFeatures")
	public void removeFromFeatures( 	@RequestBody(required=true) RemoveFeaturesFromFeatureSetCommand command )
	{		
		try {
			FeatureSetBusinessDelegate.getFeatureSetInstance().removeFromFeatures( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Features", exc );
		}
	}

    /**
     * save Datasets on FeatureSet
     * @param		command AssignDatasetsToFeatureSetCommand
     */     
	@PutMapping("/addToDatasets")
	public void addToDatasets( @RequestBody(required=true) AssignDatasetsToFeatureSetCommand command ) {
		try {
			FeatureSetBusinessDelegate.getFeatureSetInstance().addToDatasets( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Datasets", exc );
		}
	}

    /**
     * remove Datasets on FeatureSet
     * @param		command RemoveDatasetsFromFeatureSetCommand
     */     	
	@PutMapping("/removeFromDatasets")
	public void removeFromDatasets( 	@RequestBody(required=true) RemoveDatasetsFromFeatureSetCommand command )
	{		
		try {
			FeatureSetBusinessDelegate.getFeatureSetInstance().removeFromDatasets( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Datasets", exc );
		}
	}

    /**
     * save Models on FeatureSet
     * @param		command AssignModelsToFeatureSetCommand
     */     
	@PutMapping("/addToModels")
	public void addToModels( @RequestBody(required=true) AssignModelsToFeatureSetCommand command ) {
		try {
			FeatureSetBusinessDelegate.getFeatureSetInstance().addToModels( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Models", exc );
		}
	}

    /**
     * remove Models on FeatureSet
     * @param		command RemoveModelsFromFeatureSetCommand
     */     	
	@PutMapping("/removeFromModels")
	public void removeFromModels( 	@RequestBody(required=true) RemoveModelsFromFeatureSetCommand command )
	{		
		try {
			FeatureSetBusinessDelegate.getFeatureSetInstance().removeFromModels( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Models", exc );
		}
	}

    /**
     * save ModelVersions on FeatureSet
     * @param		command AssignModelVersionsToFeatureSetCommand
     */     
	@PutMapping("/addToModelVersions")
	public void addToModelVersions( @RequestBody(required=true) AssignModelVersionsToFeatureSetCommand command ) {
		try {
			FeatureSetBusinessDelegate.getFeatureSetInstance().addToModelVersions( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set ModelVersions", exc );
		}
	}

    /**
     * remove ModelVersions on FeatureSet
     * @param		command RemoveModelVersionsFromFeatureSetCommand
     */     	
	@PutMapping("/removeFromModelVersions")
	public void removeFromModelVersions( 	@RequestBody(required=true) RemoveModelVersionsFromFeatureSetCommand command )
	{		
		try {
			FeatureSetBusinessDelegate.getFeatureSetInstance().removeFromModelVersions( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set ModelVersions", exc );
		}
	}

    /**
     * save Tags on FeatureSet
     * @param		command AssignTagsToFeatureSetCommand
     */     
	@PutMapping("/addToTags")
	public void addToTags( @RequestBody(required=true) AssignTagsToFeatureSetCommand command ) {
		try {
			FeatureSetBusinessDelegate.getFeatureSetInstance().addToTags( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Tags", exc );
		}
	}

    /**
     * remove Tags on FeatureSet
     * @param		command RemoveTagsFromFeatureSetCommand
     */     	
	@PutMapping("/removeFromTags")
	public void removeFromTags( 	@RequestBody(required=true) RemoveTagsFromFeatureSetCommand command )
	{		
		try {
			FeatureSetBusinessDelegate.getFeatureSetInstance().removeFromTags( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Tags", exc );
		}
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected FeatureSet featureSet = null;
    private static final Logger LOGGER = Logger.getLogger(FeatureSetRestController.class.getName());
    
}
