/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * FraudSignalRestController as REST API
 *
 * <p>Exposes REST endpoints for the FraudSignal entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	FraudSignalService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateFraudSignalCommand</li>
 *      <li></li>UpdateFraudSignalCommand</li>
 *      <liDeleteFraudSignalCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/FraudSignal")
public class FraudSignalRestController extends BaseSpringRestController {

	public FraudSignalRestController( FraudSignalService service ) {
		this.service = service;
	}
    /**
     * Handles create a FraudSignal.  if not key provided, calls create, otherwise calls save
     * @param		FraudSignal	fraudSignal
     * @return		FraudSignal 
     */
	@PostMapping("/create")
    public FraudSignal create( @RequestBody(required=true) CreateFraudSignalCommand command ) {
    	FraudSignal entity = null;
		try {       
        	
			entity = service.createFraudSignal( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return entity;
    }

    /**
     * Handles updating a FraudSignal.  if no key provided, calls create, otherwise calls save
     * @param		FraudSignal fraudSignal
     * @return		FraudSignal
     */
	@PutMapping("/update")
    public FraudSignal update( @RequestBody(required=true) UpdateFraudSignalCommand command ) {
		FraudSignal entity = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateFraudSignalCommand
			// -----------------------------------------------
			entity = service.updateFraudSignal(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "FraudSignalController:update() - successfully update FraudSignal - " + exc.getMessage());        	
	    }		
		
		return entity;
	}
 
    /**
     * Handles deleting a FraudSignal entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteFraudSignalCommand command ) {                
    	try {
        	FraudSignalService delegate = service;

        	delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted FraudSignal with key " + command.getFraudSignalId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }

	}        
	
    /**
     * Handles loading a FraudSignal using a UUID
     * @param		UUID uuid 
     * @return		FraudSignal
     */    
    @GetMapping("/load")
    public FraudSignal load( @RequestParam(required=true) UUID uuid ) {    	
    	FraudSignal entity = null;

    	try {  
    		entity = service.getFraudSignal( new FraudSignalFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load FraudSignal using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all FraudSignal business objects
     * @return		Set<FraudSignal>
     */
    @GetMapping("/")
    public List<FraudSignal> loadAll() {                
    	List<FraudSignal> fraudSignalList = null;
        
    	try {
            // load the FraudSignal
            fraudSignalList = service.getAllFraudSignal();
            
            if ( fraudSignalList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all FraudSignals" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all FraudSignals ", exc );
        	return null;
        }

        return fraudSignalList;
                            
    }

    /**
     * save Scenario on FraudSignal
     * @param		command AssignScenarioToFraudSignalCommand
     */     
	@PutMapping("/assignScenario")
	public void assignScenario( @RequestBody AssignScenarioToFraudSignalCommand command ) {
		try {
			service.assignScenario( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Scenario", exc );
        }
	}

    /**
     * unassign Scenario on FraudSignal
     * @param		 command UnAssignScenarioFromFraudSignalCommand
     */     
	@PutMapping("/unAssignScenario")
	public void unAssignScenario( @RequestBody(required=true)  UnAssignScenarioFromFraudSignalCommand command ) {
		try {
			service.unAssignScenario( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Scenario", exc );
		}
	}
	
    /**
     * save Dataset on FraudSignal
     * @param		command AssignDatasetToFraudSignalCommand
     */     
	@PutMapping("/assignDataset")
	public void assignDataset( @RequestBody AssignDatasetToFraudSignalCommand command ) {
		try {
			service.assignDataset( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Dataset", exc );
        }
	}

    /**
     * unassign Dataset on FraudSignal
     * @param		 command UnAssignDatasetFromFraudSignalCommand
     */     
	@PutMapping("/unAssignDataset")
	public void unAssignDataset( @RequestBody(required=true)  UnAssignDatasetFromFraudSignalCommand command ) {
		try {
			service.unAssignDataset( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Dataset", exc );
		}
	}
	
    /**
     * save ModelVersion on FraudSignal
     * @param		command AssignModelVersionToFraudSignalCommand
     */     
	@PutMapping("/assignModelVersion")
	public void assignModelVersion( @RequestBody AssignModelVersionToFraudSignalCommand command ) {
		try {
			service.assignModelVersion( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign ModelVersion", exc );
        }
	}

    /**
     * unassign ModelVersion on FraudSignal
     * @param		 command UnAssignModelVersionFromFraudSignalCommand
     */     
	@PutMapping("/unAssignModelVersion")
	public void unAssignModelVersion( @RequestBody(required=true)  UnAssignModelVersionFromFraudSignalCommand command ) {
		try {
			service.unAssignModelVersion( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign ModelVersion", exc );
		}
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected FraudSignal fraudSignal = null;
	protected FraudSignalService service = null;
    private static final Logger LOGGER = Logger.getLogger(FraudSignalRestController.class.getName());
    
}
