/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.delegate.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * MetricRestController as REST API
 *
 * <p>Exposes REST endpoints for the Metric entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	MetricBusinessDelegate
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateMetricCommand</li>
 *      <li></li>UpdateMetricCommand</li>
 *      <liDeleteMetricCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Metric")
public class MetricRestController extends BaseSpringRestController {

    /**
     * Handles create a Metric.  if not key provided, calls create, otherwise calls save
     * @param		Metric	metric
     * @return		Metric 
     */
	@PostMapping("/create")
    public Metric create( @RequestBody(required=true) CreateMetricCommand command ) {
    	Metric entity = null;
		try {       
        	
			entity = MetricBusinessDelegate.getMetricInstance().createMetric( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return entity;
    }

    /**
     * Handles updating a Metric.  if no key provided, calls create, otherwise calls save
     * @param		Metric metric
     * @return		Metric
     */
	@PutMapping("/update")
    public Metric update( @RequestBody(required=true) UpdateMetricCommand command ) {
		Metric entity = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateMetricCommand
			// -----------------------------------------------
			entity = MetricBusinessDelegate.getMetricInstance().updateMetric(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "MetricController:update() - successfully update Metric - " + exc.getMessage());        	
	    }		
		
		return entity;
	}
 
    /**
     * Handles deleting a Metric entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteMetricCommand command ) {                
    	try {
        	MetricBusinessDelegate delegate = MetricBusinessDelegate.getMetricInstance();

        	delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted Metric with key " + command.getMetricId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }

	}        
	
    /**
     * Handles loading a Metric using a UUID
     * @param		UUID uuid 
     * @return		Metric
     */    
    @GetMapping("/load")
    public Metric load( @RequestParam(required=true) UUID uuid ) {    	
    	Metric entity = null;

    	try {  
    		entity = MetricBusinessDelegate.getMetricInstance().getMetric( new MetricFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load Metric using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all Metric business objects
     * @return		Set<Metric>
     */
    @GetMapping("/")
    public List<Metric> loadAll() {                
    	List<Metric> metricList = null;
        
    	try {
            // load the Metric
            metricList = MetricBusinessDelegate.getMetricInstance().getAllMetric();
            
            if ( metricList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all Metrics" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all Metrics ", exc );
        	return null;
        }

        return metricList;
                            
    }

    /**
     * save SemanticModel on Metric
     * @param		command AssignSemanticModelToMetricCommand
     */     
	@PutMapping("/assignSemanticModel")
	public void assignSemanticModel( @RequestBody AssignSemanticModelToMetricCommand command ) {
		try {
			MetricBusinessDelegate.getMetricInstance().assignSemanticModel( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign SemanticModel", exc );
        }
	}

    /**
     * unassign SemanticModel on Metric
     * @param		 command UnAssignSemanticModelFromMetricCommand
     */     
	@PutMapping("/unAssignSemanticModel")
	public void unAssignSemanticModel( @RequestBody(required=true)  UnAssignSemanticModelFromMetricCommand command ) {
		try {
			MetricBusinessDelegate.getMetricInstance().unAssignSemanticModel( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign SemanticModel", exc );
		}
	}
	

    /**
     * save Datasets on Metric
     * @param		command AssignDatasetsToMetricCommand
     */     
	@PutMapping("/addToDatasets")
	public void addToDatasets( @RequestBody(required=true) AssignDatasetsToMetricCommand command ) {
		try {
			MetricBusinessDelegate.getMetricInstance().addToDatasets( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Datasets", exc );
		}
	}

    /**
     * remove Datasets on Metric
     * @param		command RemoveDatasetsFromMetricCommand
     */     	
	@PutMapping("/removeFromDatasets")
	public void removeFromDatasets( 	@RequestBody(required=true) RemoveDatasetsFromMetricCommand command )
	{		
		try {
			MetricBusinessDelegate.getMetricInstance().removeFromDatasets( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Datasets", exc );
		}
	}

    /**
     * save GlossaryTerms on Metric
     * @param		command AssignGlossaryTermsToMetricCommand
     */     
	@PutMapping("/addToGlossaryTerms")
	public void addToGlossaryTerms( @RequestBody(required=true) AssignGlossaryTermsToMetricCommand command ) {
		try {
			MetricBusinessDelegate.getMetricInstance().addToGlossaryTerms( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set GlossaryTerms", exc );
		}
	}

    /**
     * remove GlossaryTerms on Metric
     * @param		command RemoveGlossaryTermsFromMetricCommand
     */     	
	@PutMapping("/removeFromGlossaryTerms")
	public void removeFromGlossaryTerms( 	@RequestBody(required=true) RemoveGlossaryTermsFromMetricCommand command )
	{		
		try {
			MetricBusinessDelegate.getMetricInstance().removeFromGlossaryTerms( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set GlossaryTerms", exc );
		}
	}

    /**
     * save Alerts on Metric
     * @param		command AssignAlertsToMetricCommand
     */     
	@PutMapping("/addToAlerts")
	public void addToAlerts( @RequestBody(required=true) AssignAlertsToMetricCommand command ) {
		try {
			MetricBusinessDelegate.getMetricInstance().addToAlerts( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Alerts", exc );
		}
	}

    /**
     * remove Alerts on Metric
     * @param		command RemoveAlertsFromMetricCommand
     */     	
	@PutMapping("/removeFromAlerts")
	public void removeFromAlerts( 	@RequestBody(required=true) RemoveAlertsFromMetricCommand command )
	{		
		try {
			MetricBusinessDelegate.getMetricInstance().removeFromAlerts( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Alerts", exc );
		}
	}

    /**
     * save Visualizations on Metric
     * @param		command AssignVisualizationsToMetricCommand
     */     
	@PutMapping("/addToVisualizations")
	public void addToVisualizations( @RequestBody(required=true) AssignVisualizationsToMetricCommand command ) {
		try {
			MetricBusinessDelegate.getMetricInstance().addToVisualizations( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Visualizations", exc );
		}
	}

    /**
     * remove Visualizations on Metric
     * @param		command RemoveVisualizationsFromMetricCommand
     */     	
	@PutMapping("/removeFromVisualizations")
	public void removeFromVisualizations( 	@RequestBody(required=true) RemoveVisualizationsFromMetricCommand command )
	{		
		try {
			MetricBusinessDelegate.getMetricInstance().removeFromVisualizations( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Visualizations", exc );
		}
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected Metric metric = null;
    private static final Logger LOGGER = Logger.getLogger(MetricRestController.class.getName());
    
}
