/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.delegate.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * QualityCheckRestController as REST API
 *
 * <p>Exposes REST endpoints for the QualityCheck entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	QualityCheckBusinessDelegate
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateQualityCheckCommand</li>
 *      <li></li>UpdateQualityCheckCommand</li>
 *      <liDeleteQualityCheckCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/QualityCheck")
public class QualityCheckRestController extends BaseSpringRestController {

    /**
     * Handles create a QualityCheck.  if not key provided, calls create, otherwise calls save
     * @param		QualityCheck	qualityCheck
     * @return		QualityCheck 
     */
	@PostMapping("/create")
    public QualityCheck create( @RequestBody(required=true) CreateQualityCheckCommand command ) {
    	QualityCheck entity = null;
		try {       
        	
			entity = QualityCheckBusinessDelegate.getQualityCheckInstance().createQualityCheck( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return entity;
    }

    /**
     * Handles updating a QualityCheck.  if no key provided, calls create, otherwise calls save
     * @param		QualityCheck qualityCheck
     * @return		QualityCheck
     */
	@PutMapping("/update")
    public QualityCheck update( @RequestBody(required=true) UpdateQualityCheckCommand command ) {
		QualityCheck entity = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateQualityCheckCommand
			// -----------------------------------------------
			entity = QualityCheckBusinessDelegate.getQualityCheckInstance().updateQualityCheck(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "QualityCheckController:update() - successfully update QualityCheck - " + exc.getMessage());        	
	    }		
		
		return entity;
	}
 
    /**
     * Handles deleting a QualityCheck entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteQualityCheckCommand command ) {                
    	try {
        	QualityCheckBusinessDelegate delegate = QualityCheckBusinessDelegate.getQualityCheckInstance();

        	delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted QualityCheck with key " + command.getQualityCheckId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }

	}        
	
    /**
     * Handles loading a QualityCheck using a UUID
     * @param		UUID uuid 
     * @return		QualityCheck
     */    
    @GetMapping("/load")
    public QualityCheck load( @RequestParam(required=true) UUID uuid ) {    	
    	QualityCheck entity = null;

    	try {  
    		entity = QualityCheckBusinessDelegate.getQualityCheckInstance().getQualityCheck( new QualityCheckFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load QualityCheck using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all QualityCheck business objects
     * @return		Set<QualityCheck>
     */
    @GetMapping("/")
    public List<QualityCheck> loadAll() {                
    	List<QualityCheck> qualityCheckList = null;
        
    	try {
            // load the QualityCheck
            qualityCheckList = QualityCheckBusinessDelegate.getQualityCheckInstance().getAllQualityCheck();
            
            if ( qualityCheckList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all QualityChecks" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all QualityChecks ", exc );
        	return null;
        }

        return qualityCheckList;
                            
    }

    /**
     * save Rule on QualityCheck
     * @param		command AssignRuleToQualityCheckCommand
     */     
	@PutMapping("/assignRule")
	public void assignRule( @RequestBody AssignRuleToQualityCheckCommand command ) {
		try {
			QualityCheckBusinessDelegate.getQualityCheckInstance().assignRule( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Rule", exc );
        }
	}

    /**
     * unassign Rule on QualityCheck
     * @param		 command UnAssignRuleFromQualityCheckCommand
     */     
	@PutMapping("/unAssignRule")
	public void unAssignRule( @RequestBody(required=true)  UnAssignRuleFromQualityCheckCommand command ) {
		try {
			QualityCheckBusinessDelegate.getQualityCheckInstance().unAssignRule( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Rule", exc );
		}
	}
	
    /**
     * save Dataset on QualityCheck
     * @param		command AssignDatasetToQualityCheckCommand
     */     
	@PutMapping("/assignDataset")
	public void assignDataset( @RequestBody AssignDatasetToQualityCheckCommand command ) {
		try {
			QualityCheckBusinessDelegate.getQualityCheckInstance().assignDataset( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Dataset", exc );
        }
	}

    /**
     * unassign Dataset on QualityCheck
     * @param		 command UnAssignDatasetFromQualityCheckCommand
     */     
	@PutMapping("/unAssignDataset")
	public void unAssignDataset( @RequestBody(required=true)  UnAssignDatasetFromQualityCheckCommand command ) {
		try {
			QualityCheckBusinessDelegate.getQualityCheckInstance().unAssignDataset( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Dataset", exc );
		}
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected QualityCheck qualityCheck = null;
    private static final Logger LOGGER = Logger.getLogger(QualityCheckRestController.class.getName());
    
}
