/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * SubscriberRestController as REST API
 *
 * <p>Exposes REST endpoints for the Subscriber entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	SubscriberService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateSubscriberCommand</li>
 *      <li></li>UpdateSubscriberCommand</li>
 *      <liDeleteSubscriberCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Subscriber")
public class SubscriberRestController extends BaseSpringRestController {

	public SubscriberRestController( SubscriberService service ) {
		this.service = service;
	}
    /**
     * Handles create a Subscriber.  if not key provided, calls create, otherwise calls save
     * @param		Subscriber	subscriber
     * @return		Subscriber 
     */
	@PostMapping("/create")
    public Subscriber create( @RequestBody(required=true) CreateSubscriberCommand command ) {
    	Subscriber entity = null;
		try {       
        	
			entity = service.createSubscriber( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return entity;
    }

    /**
     * Handles updating a Subscriber.  if no key provided, calls create, otherwise calls save
     * @param		Subscriber subscriber
     * @return		Subscriber
     */
	@PutMapping("/update")
    public Subscriber update( @RequestBody(required=true) UpdateSubscriberCommand command ) {
		Subscriber entity = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateSubscriberCommand
			// -----------------------------------------------
			entity = service.updateSubscriber(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "SubscriberController:update() - successfully update Subscriber - " + exc.getMessage());        	
	    }		
		
		return entity;
	}
 
    /**
     * Handles deleting a Subscriber entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteSubscriberCommand command ) {                
    	try {
        	SubscriberService delegate = service;

        	delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted Subscriber with key " + command.getSubscriberId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }

	}        
	
    /**
     * Handles loading a Subscriber using a UUID
     * @param		UUID uuid 
     * @return		Subscriber
     */    
    @GetMapping("/load")
    public Subscriber load( @RequestParam(required=true) UUID uuid ) {    	
    	Subscriber entity = null;

    	try {  
    		entity = service.getSubscriber( new SubscriberFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load Subscriber using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all Subscriber business objects
     * @return		Set<Subscriber>
     */
    @GetMapping("/")
    public List<Subscriber> loadAll() {                
    	List<Subscriber> subscriberList = null;
        
    	try {
            // load the Subscriber
            subscriberList = service.getAllSubscriber();
            
            if ( subscriberList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all Subscribers" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all Subscribers ", exc );
        	return null;
        }

        return subscriberList;
                            
    }


    /**
     * save Alerts on Subscriber
     * @param		command AssignAlertsToSubscriberCommand
     */     
	@PutMapping("/addToAlerts")
	public void addToAlerts( @RequestBody(required=true) AssignAlertsToSubscriberCommand command ) {
		try {
			service.addToAlerts( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Alerts", exc );
		}
	}

    /**
     * remove Alerts on Subscriber
     * @param		command RemoveAlertsFromSubscriberCommand
     */     	
	@PutMapping("/removeFromAlerts")
	public void removeFromAlerts( 	@RequestBody(required=true) RemoveAlertsFromSubscriberCommand command )
	{		
		try {
			service.removeFromAlerts( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Alerts", exc );
		}
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected Subscriber subscriber = null;
	protected SubscriberService service = null;
    private static final Logger LOGGER = Logger.getLogger(SubscriberRestController.class.getName());
    
}
