/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.delegate.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * TrainingRunRestController as REST API
 *
 * <p>Exposes REST endpoints for the TrainingRun entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	TrainingRunBusinessDelegate
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateTrainingRunCommand</li>
 *      <li></li>UpdateTrainingRunCommand</li>
 *      <liDeleteTrainingRunCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/TrainingRun")
public class TrainingRunRestController extends BaseSpringRestController {

    /**
     * Handles create a TrainingRun.  if not key provided, calls create, otherwise calls save
     * @param		TrainingRun	trainingRun
     * @return		TrainingRun 
     */
	@PostMapping("/create")
    public TrainingRun create( @RequestBody(required=true) CreateTrainingRunCommand command ) {
    	TrainingRun entity = null;
		try {       
        	
			entity = TrainingRunBusinessDelegate.getTrainingRunInstance().createTrainingRun( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return entity;
    }

    /**
     * Handles updating a TrainingRun.  if no key provided, calls create, otherwise calls save
     * @param		TrainingRun trainingRun
     * @return		TrainingRun
     */
	@PutMapping("/update")
    public TrainingRun update( @RequestBody(required=true) UpdateTrainingRunCommand command ) {
		TrainingRun entity = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateTrainingRunCommand
			// -----------------------------------------------
			entity = TrainingRunBusinessDelegate.getTrainingRunInstance().updateTrainingRun(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "TrainingRunController:update() - successfully update TrainingRun - " + exc.getMessage());        	
	    }		
		
		return entity;
	}
 
    /**
     * Handles deleting a TrainingRun entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteTrainingRunCommand command ) {                
    	try {
        	TrainingRunBusinessDelegate delegate = TrainingRunBusinessDelegate.getTrainingRunInstance();

        	delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted TrainingRun with key " + command.getTrainingRunId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }

	}        
	
    /**
     * Handles loading a TrainingRun using a UUID
     * @param		UUID uuid 
     * @return		TrainingRun
     */    
    @GetMapping("/load")
    public TrainingRun load( @RequestParam(required=true) UUID uuid ) {    	
    	TrainingRun entity = null;

    	try {  
    		entity = TrainingRunBusinessDelegate.getTrainingRunInstance().getTrainingRun( new TrainingRunFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load TrainingRun using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all TrainingRun business objects
     * @return		Set<TrainingRun>
     */
    @GetMapping("/")
    public List<TrainingRun> loadAll() {                
    	List<TrainingRun> trainingRunList = null;
        
    	try {
            // load the TrainingRun
            trainingRunList = TrainingRunBusinessDelegate.getTrainingRunInstance().getAllTrainingRun();
            
            if ( trainingRunList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all TrainingRuns" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all TrainingRuns ", exc );
        	return null;
        }

        return trainingRunList;
                            
    }

    /**
     * save Experiment on TrainingRun
     * @param		command AssignExperimentToTrainingRunCommand
     */     
	@PutMapping("/assignExperiment")
	public void assignExperiment( @RequestBody AssignExperimentToTrainingRunCommand command ) {
		try {
			TrainingRunBusinessDelegate.getTrainingRunInstance().assignExperiment( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Experiment", exc );
        }
	}

    /**
     * unassign Experiment on TrainingRun
     * @param		 command UnAssignExperimentFromTrainingRunCommand
     */     
	@PutMapping("/unAssignExperiment")
	public void unAssignExperiment( @RequestBody(required=true)  UnAssignExperimentFromTrainingRunCommand command ) {
		try {
			TrainingRunBusinessDelegate.getTrainingRunInstance().unAssignExperiment( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Experiment", exc );
		}
	}
	
    /**
     * save ModelVersion on TrainingRun
     * @param		command AssignModelVersionToTrainingRunCommand
     */     
	@PutMapping("/assignModelVersion")
	public void assignModelVersion( @RequestBody AssignModelVersionToTrainingRunCommand command ) {
		try {
			TrainingRunBusinessDelegate.getTrainingRunInstance().assignModelVersion( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign ModelVersion", exc );
        }
	}

    /**
     * unassign ModelVersion on TrainingRun
     * @param		 command UnAssignModelVersionFromTrainingRunCommand
     */     
	@PutMapping("/unAssignModelVersion")
	public void unAssignModelVersion( @RequestBody(required=true)  UnAssignModelVersionFromTrainingRunCommand command ) {
		try {
			TrainingRunBusinessDelegate.getTrainingRunInstance().unAssignModelVersion( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign ModelVersion", exc );
		}
	}
	

    /**
     * save InputDatasets on TrainingRun
     * @param		command AssignInputDatasetsToTrainingRunCommand
     */     
	@PutMapping("/addToInputDatasets")
	public void addToInputDatasets( @RequestBody(required=true) AssignInputDatasetsToTrainingRunCommand command ) {
		try {
			TrainingRunBusinessDelegate.getTrainingRunInstance().addToInputDatasets( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set InputDatasets", exc );
		}
	}

    /**
     * remove InputDatasets on TrainingRun
     * @param		command RemoveInputDatasetsFromTrainingRunCommand
     */     	
	@PutMapping("/removeFromInputDatasets")
	public void removeFromInputDatasets( 	@RequestBody(required=true) RemoveInputDatasetsFromTrainingRunCommand command )
	{		
		try {
			TrainingRunBusinessDelegate.getTrainingRunInstance().removeFromInputDatasets( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set InputDatasets", exc );
		}
	}

    /**
     * save Features on TrainingRun
     * @param		command AssignFeaturesToTrainingRunCommand
     */     
	@PutMapping("/addToFeatures")
	public void addToFeatures( @RequestBody(required=true) AssignFeaturesToTrainingRunCommand command ) {
		try {
			TrainingRunBusinessDelegate.getTrainingRunInstance().addToFeatures( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Features", exc );
		}
	}

    /**
     * remove Features on TrainingRun
     * @param		command RemoveFeaturesFromTrainingRunCommand
     */     	
	@PutMapping("/removeFromFeatures")
	public void removeFromFeatures( 	@RequestBody(required=true) RemoveFeaturesFromTrainingRunCommand command )
	{		
		try {
			TrainingRunBusinessDelegate.getTrainingRunInstance().removeFromFeatures( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Features", exc );
		}
	}

    /**
     * save RunMetrics on TrainingRun
     * @param		command AssignRunMetricsToTrainingRunCommand
     */     
	@PutMapping("/addToRunMetrics")
	public void addToRunMetrics( @RequestBody(required=true) AssignRunMetricsToTrainingRunCommand command ) {
		try {
			TrainingRunBusinessDelegate.getTrainingRunInstance().addToRunMetrics( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set RunMetrics", exc );
		}
	}

    /**
     * remove RunMetrics on TrainingRun
     * @param		command RemoveRunMetricsFromTrainingRunCommand
     */     	
	@PutMapping("/removeFromRunMetrics")
	public void removeFromRunMetrics( 	@RequestBody(required=true) RemoveRunMetricsFromTrainingRunCommand command )
	{		
		try {
			TrainingRunBusinessDelegate.getTrainingRunInstance().removeFromRunMetrics( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set RunMetrics", exc );
		}
	}

    /**
     * save RunParameters on TrainingRun
     * @param		command AssignRunParametersToTrainingRunCommand
     */     
	@PutMapping("/addToRunParameters")
	public void addToRunParameters( @RequestBody(required=true) AssignRunParametersToTrainingRunCommand command ) {
		try {
			TrainingRunBusinessDelegate.getTrainingRunInstance().addToRunParameters( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set RunParameters", exc );
		}
	}

    /**
     * remove RunParameters on TrainingRun
     * @param		command RemoveRunParametersFromTrainingRunCommand
     */     	
	@PutMapping("/removeFromRunParameters")
	public void removeFromRunParameters( 	@RequestBody(required=true) RemoveRunParametersFromTrainingRunCommand command )
	{		
		try {
			TrainingRunBusinessDelegate.getTrainingRunInstance().removeFromRunParameters( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set RunParameters", exc );
		}
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected TrainingRun trainingRun = null;
    private static final Logger LOGGER = Logger.getLogger(TrainingRunRestController.class.getName());
    
}
