/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.delegate.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * VisualizationRestController as REST API
 *
 * <p>Exposes REST endpoints for the Visualization entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	VisualizationBusinessDelegate
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateVisualizationCommand</li>
 *      <li></li>UpdateVisualizationCommand</li>
 *      <liDeleteVisualizationCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Visualization")
public class VisualizationRestController extends BaseSpringRestController {

    /**
     * Handles create a Visualization.  if not key provided, calls create, otherwise calls save
     * @param		Visualization	visualization
     * @return		Visualization 
     */
	@PostMapping("/create")
    public Visualization create( @RequestBody(required=true) CreateVisualizationCommand command ) {
    	Visualization entity = null;
		try {       
        	
			entity = VisualizationBusinessDelegate.getVisualizationInstance().createVisualization( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return entity;
    }

    /**
     * Handles updating a Visualization.  if no key provided, calls create, otherwise calls save
     * @param		Visualization visualization
     * @return		Visualization
     */
	@PutMapping("/update")
    public Visualization update( @RequestBody(required=true) UpdateVisualizationCommand command ) {
		Visualization entity = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateVisualizationCommand
			// -----------------------------------------------
			entity = VisualizationBusinessDelegate.getVisualizationInstance().updateVisualization(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "VisualizationController:update() - successfully update Visualization - " + exc.getMessage());        	
	    }		
		
		return entity;
	}
 
    /**
     * Handles deleting a Visualization entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteVisualizationCommand command ) {                
    	try {
        	VisualizationBusinessDelegate delegate = VisualizationBusinessDelegate.getVisualizationInstance();

        	delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted Visualization with key " + command.getVisualizationId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }

	}        
	
    /**
     * Handles loading a Visualization using a UUID
     * @param		UUID uuid 
     * @return		Visualization
     */    
    @GetMapping("/load")
    public Visualization load( @RequestParam(required=true) UUID uuid ) {    	
    	Visualization entity = null;

    	try {  
    		entity = VisualizationBusinessDelegate.getVisualizationInstance().getVisualization( new VisualizationFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load Visualization using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all Visualization business objects
     * @return		Set<Visualization>
     */
    @GetMapping("/")
    public List<Visualization> loadAll() {                
    	List<Visualization> visualizationList = null;
        
    	try {
            // load the Visualization
            visualizationList = VisualizationBusinessDelegate.getVisualizationInstance().getAllVisualization();
            
            if ( visualizationList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all Visualizations" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all Visualizations ", exc );
        	return null;
        }

        return visualizationList;
                            
    }

    /**
     * save Dashboard on Visualization
     * @param		command AssignDashboardToVisualizationCommand
     */     
	@PutMapping("/assignDashboard")
	public void assignDashboard( @RequestBody AssignDashboardToVisualizationCommand command ) {
		try {
			VisualizationBusinessDelegate.getVisualizationInstance().assignDashboard( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Dashboard", exc );
        }
	}

    /**
     * unassign Dashboard on Visualization
     * @param		 command UnAssignDashboardFromVisualizationCommand
     */     
	@PutMapping("/unAssignDashboard")
	public void unAssignDashboard( @RequestBody(required=true)  UnAssignDashboardFromVisualizationCommand command ) {
		try {
			VisualizationBusinessDelegate.getVisualizationInstance().unAssignDashboard( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Dashboard", exc );
		}
	}
	
    /**
     * save Report on Visualization
     * @param		command AssignReportToVisualizationCommand
     */     
	@PutMapping("/assignReport")
	public void assignReport( @RequestBody AssignReportToVisualizationCommand command ) {
		try {
			VisualizationBusinessDelegate.getVisualizationInstance().assignReport( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Report", exc );
        }
	}

    /**
     * unassign Report on Visualization
     * @param		 command UnAssignReportFromVisualizationCommand
     */     
	@PutMapping("/unAssignReport")
	public void unAssignReport( @RequestBody(required=true)  UnAssignReportFromVisualizationCommand command ) {
		try {
			VisualizationBusinessDelegate.getVisualizationInstance().unAssignReport( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Report", exc );
		}
	}
	

    /**
     * save Metrics on Visualization
     * @param		command AssignMetricsToVisualizationCommand
     */     
	@PutMapping("/addToMetrics")
	public void addToMetrics( @RequestBody(required=true) AssignMetricsToVisualizationCommand command ) {
		try {
			VisualizationBusinessDelegate.getVisualizationInstance().addToMetrics( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Metrics", exc );
		}
	}

    /**
     * remove Metrics on Visualization
     * @param		command RemoveMetricsFromVisualizationCommand
     */     	
	@PutMapping("/removeFromMetrics")
	public void removeFromMetrics( 	@RequestBody(required=true) RemoveMetricsFromVisualizationCommand command )
	{		
		try {
			VisualizationBusinessDelegate.getVisualizationInstance().removeFromMetrics( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Metrics", exc );
		}
	}

    /**
     * save Dimensions on Visualization
     * @param		command AssignDimensionsToVisualizationCommand
     */     
	@PutMapping("/addToDimensions")
	public void addToDimensions( @RequestBody(required=true) AssignDimensionsToVisualizationCommand command ) {
		try {
			VisualizationBusinessDelegate.getVisualizationInstance().addToDimensions( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Dimensions", exc );
		}
	}

    /**
     * remove Dimensions on Visualization
     * @param		command RemoveDimensionsFromVisualizationCommand
     */     	
	@PutMapping("/removeFromDimensions")
	public void removeFromDimensions( 	@RequestBody(required=true) RemoveDimensionsFromVisualizationCommand command )
	{		
		try {
			VisualizationBusinessDelegate.getVisualizationInstance().removeFromDimensions( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Dimensions", exc );
		}
	}

    /**
     * save Datasets on Visualization
     * @param		command AssignDatasetsToVisualizationCommand
     */     
	@PutMapping("/addToDatasets")
	public void addToDatasets( @RequestBody(required=true) AssignDatasetsToVisualizationCommand command ) {
		try {
			VisualizationBusinessDelegate.getVisualizationInstance().addToDatasets( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Datasets", exc );
		}
	}

    /**
     * remove Datasets on Visualization
     * @param		command RemoveDatasetsFromVisualizationCommand
     */     	
	@PutMapping("/removeFromDatasets")
	public void removeFromDatasets( 	@RequestBody(required=true) RemoveDatasetsFromVisualizationCommand command )
	{		
		try {
			VisualizationBusinessDelegate.getVisualizationInstance().removeFromDatasets( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Datasets", exc );
		}
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected Visualization visualization = null;
    private static final Logger LOGGER = Logger.getLogger(VisualizationRestController.class.getName());
    
}
