/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>AnalyticsWorkspace business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of AnalyticsWorkspace related services in the case of a AnalyticsWorkspace business related service failing.</li>
 * <li>Exposes a simpler, uniform AnalyticsWorkspace interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill AnalyticsWorkspace business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class AnalyticsWorkspaceService 
extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
    /** 
     * Default Constructor 
     */
    public AnalyticsWorkspaceService(CurrentIdentity identity)  {

		this.identity	= identity;
    	projector 		= new AnalyticsWorkspaceEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
							applicationContext.getBean(AnalyticsWorkspaceRepository.class) );
	}


   /**
	* AnalyticsWorkspace Business Delegate Factory Method
	*
	* All methods are expected to be self-sufficient.
	*
	* @return 	AnalyticsWorkspaceService
	*/
	public static AnalyticsWorkspaceService getAnalyticsWorkspaceInstance() {
		return( new AnalyticsWorkspaceService() );
	}
 
   /**
    * Creates the provided command.
    * 
    * @param		command ${class.getCreateCommandAlias()}
    * @exception    ProcessingException
    * @exception	IllegalArgumentException
    * @return		AnalyticsWorkspace
    */
	public AnalyticsWorkspace createAnalyticsWorkspace( CreateAnalyticsWorkspaceCommand command )
    throws ProcessingException, IllegalArgumentException {

		AnalyticsWorkspace entity = new AnalyticsWorkspace();

		try {
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	AnalyticsWorkspaceValidator.getInstance().validate( command );    

            entity.setAnalyticsWorkspaceId( command.getAnalyticsWorkspaceId() );
            entity.setName( command.getName() );
            entity.setBusinessDomain( command.getBusinessDomain() );
            entity.setOwnerTeam( command.getOwnerTeam() );
            entity.setGovernanceTier( command.getGovernanceTier() );
    	    
        	// ------------------------------------------
        	// persist a new one
        	// ------------------------------------------ 
    	    entity = projector.create(entity);
    	    
			LOGGER.info( "done creating of AnalyticsWorkspace {0} ", entity.toString() );

        }
        catch (Exception exc) {
            final String errMsg = "Unable to create AnalyticsWorkspace - " + exc;
            LOGGER.warn(  errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }

   /**
    * Update the provided command.
    * @param		command UpdateAnalyticsWorkspaceCommand
    * @exception    ProcessingException
    * @exception  	IllegalArgumentException
    * @return		AnalyticsWorkspace
    */
    public AnalyticsWorkspace updateAnalyticsWorkspace( UpdateAnalyticsWorkspaceCommand command ) 
    throws ProcessingException, IllegalArgumentException {

	    AnalyticsWorkspace entity = new AnalyticsWorkspace();

    	try {       

			// --------------------------------------
        	// validate 
        	// --------------------------------------    	
        	AnalyticsWorkspaceValidator.getInstance().validate( command );    

            entity.setAnalyticsWorkspaceId( command.getAnalyticsWorkspaceId() );
            entity.setName( command.getName() );
            entity.setBusinessDomain( command.getBusinessDomain() );
            entity.setOwnerTeam( command.getOwnerTeam() );
            entity.setDatasets( command.getDatasets() );
            entity.setDataSources( command.getDataSources() );
            entity.setPipelines( command.getPipelines() );
            entity.setDashboards( command.getDashboards() );
            entity.setReports( command.getReports() );
            entity.setNotebooks( command.getNotebooks() );
            entity.setModels( command.getModels() );
            entity.setFeatureSets( command.getFeatureSets() );
            entity.setPolicies( command.getPolicies() );
            entity.setLineageNodes( command.getLineageNodes() );
            entity.setGovernanceTier( command.getGovernanceTier() );
        	
        	// ------------------------------------------
        	// persist an existing one
        	// ------------------------------------------ 
        	entity = projector.update(entity);
    	    
			LOGGER.info( "done saving of AnalyticsWorkspace {0} ", entity.toString() );
    	}
        catch (Exception exc) {
            final String errMsg = "Unable to save AnalyticsWorkspace - " + exc;
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
    	
    	return entity;
    }
   
   /**
    * Deletes the associatied value object
    * @param		command DeleteAnalyticsWorkspaceCommand
    * @exception 	ProcessingException
    */
    public void delete( DeleteAnalyticsWorkspaceCommand command ) 
    throws ProcessingException, IllegalArgumentException {	
        UUID id = null;
        
    	try {  
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	AnalyticsWorkspaceValidator.getInstance().validate( command );    
        
        	id = command.getAnalyticsWorkspaceId();
        	
        	// ------------------------------------------
        	// delete the entity
        	// ------------------------------------------
        	projector.delete(id);

        	LOGGER.info( "done deleting of AnalyticsWorkspace {0} ", id );

        }
        catch (Exception exc) {
            final String errMsg = "Unable to delete AnalyticsWorkspace using Id = "  + id;
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }
    }

    /**
     * Method to retrieve the AnalyticsWorkspace via AnalyticsWorkspaceFetchOneSummary
     * @param 	summary AnalyticsWorkspaceFetchOneSummary 
     * @return 	AnalyticsWorkspaceFetchOneResponse
     * @exception ProcessingException - Thrown if processing any related problems
     * @exception IllegalArgumentException 
     */
    public AnalyticsWorkspace getAnalyticsWorkspace( AnalyticsWorkspaceFetchOneSummary summary ) 
    throws ProcessingException, IllegalArgumentException {
    	
    	if( summary == null )
    		throw new IllegalArgumentException( "AnalyticsWorkspaceFetchOneSummary arg cannot be null" );
    	
    	AnalyticsWorkspace entity = null;
    	UUID id = summary.getAnalyticsWorkspaceId();
    	
        try {
        	// --------------------------------------
        	// validate the fetch one summary
        	// --------------------------------------    	
        	AnalyticsWorkspaceValidator.getInstance().validate( summary );    
        	
        	// --------------------------------------
        	// find a AnalyticsWorkspace using the provided id
        	// --------------------------------------
        	entity = projector.find( id );
        }
        catch( Exception exc ) {
            final String errMsg = "Unable to locate AnalyticsWorkspace with id " + id;
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }


    /**
     * Method to retrieve a collection of all AnalyticsWorkspaces
     *
     * @return 	List<AnalyticsWorkspace> 
     * @exception ProcessingException Thrown if any problems
     */
    public List<AnalyticsWorkspace> getAllAnalyticsWorkspace() 
    throws ProcessingException {
        List<AnalyticsWorkspace> list = null;

        try {        	
        	list = projector.findAll( new FindAllAnalyticsWorkspaceQuery() );
        }
        catch( Exception exc ) {
            String errMsg = "Failed to get all AnalyticsWorkspace";
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return list;
    }


    /**
     * add DataSet to Datasets 
     * @param		command AssignDatasetsToAnalyticsWorkspaceCommand
     * @exception	ProcessingException
     */     
	public void addToDatasets( AssignDatasetsToAnalyticsWorkspaceCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AnalyticsWorkspaceValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToDatasets(command.getAnalyticsWorkspaceId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a DataSet as Datasets to AnalyticsWorkspace" ; 
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove DataSet from Datasets
     * @param		command RemoveDatasetsFromAnalyticsWorkspaceCommand
     * @exception	ProcessingException
     */     	
	public void removeFromDatasets( RemoveDatasetsFromAnalyticsWorkspaceCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AnalyticsWorkspaceValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromDatasets(command.getAnalyticsWorkspaceId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getAnalyticsWorkspaceId(); 
			LOGGER.warn(  msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add DataSource to DataSources 
     * @param		command AssignDataSourcesToAnalyticsWorkspaceCommand
     * @exception	ProcessingException
     */     
	public void addToDataSources( AssignDataSourcesToAnalyticsWorkspaceCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AnalyticsWorkspaceValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToDataSources(command.getAnalyticsWorkspaceId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a DataSource as DataSources to AnalyticsWorkspace" ; 
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove DataSource from DataSources
     * @param		command RemoveDataSourcesFromAnalyticsWorkspaceCommand
     * @exception	ProcessingException
     */     	
	public void removeFromDataSources( RemoveDataSourcesFromAnalyticsWorkspaceCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AnalyticsWorkspaceValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromDataSources(command.getAnalyticsWorkspaceId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getAnalyticsWorkspaceId(); 
			LOGGER.warn(  msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add DataPipeline to Pipelines 
     * @param		command AssignPipelinesToAnalyticsWorkspaceCommand
     * @exception	ProcessingException
     */     
	public void addToPipelines( AssignPipelinesToAnalyticsWorkspaceCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AnalyticsWorkspaceValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToPipelines(command.getAnalyticsWorkspaceId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a DataPipeline as Pipelines to AnalyticsWorkspace" ; 
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove DataPipeline from Pipelines
     * @param		command RemovePipelinesFromAnalyticsWorkspaceCommand
     * @exception	ProcessingException
     */     	
	public void removeFromPipelines( RemovePipelinesFromAnalyticsWorkspaceCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AnalyticsWorkspaceValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromPipelines(command.getAnalyticsWorkspaceId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getAnalyticsWorkspaceId(); 
			LOGGER.warn(  msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Dashboard to Dashboards 
     * @param		command AssignDashboardsToAnalyticsWorkspaceCommand
     * @exception	ProcessingException
     */     
	public void addToDashboards( AssignDashboardsToAnalyticsWorkspaceCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AnalyticsWorkspaceValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToDashboards(command.getAnalyticsWorkspaceId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Dashboard as Dashboards to AnalyticsWorkspace" ; 
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Dashboard from Dashboards
     * @param		command RemoveDashboardsFromAnalyticsWorkspaceCommand
     * @exception	ProcessingException
     */     	
	public void removeFromDashboards( RemoveDashboardsFromAnalyticsWorkspaceCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AnalyticsWorkspaceValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromDashboards(command.getAnalyticsWorkspaceId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getAnalyticsWorkspaceId(); 
			LOGGER.warn(  msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Report to Reports 
     * @param		command AssignReportsToAnalyticsWorkspaceCommand
     * @exception	ProcessingException
     */     
	public void addToReports( AssignReportsToAnalyticsWorkspaceCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AnalyticsWorkspaceValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToReports(command.getAnalyticsWorkspaceId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Report as Reports to AnalyticsWorkspace" ; 
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Report from Reports
     * @param		command RemoveReportsFromAnalyticsWorkspaceCommand
     * @exception	ProcessingException
     */     	
	public void removeFromReports( RemoveReportsFromAnalyticsWorkspaceCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AnalyticsWorkspaceValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromReports(command.getAnalyticsWorkspaceId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getAnalyticsWorkspaceId(); 
			LOGGER.warn(  msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Notebook to Notebooks 
     * @param		command AssignNotebooksToAnalyticsWorkspaceCommand
     * @exception	ProcessingException
     */     
	public void addToNotebooks( AssignNotebooksToAnalyticsWorkspaceCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AnalyticsWorkspaceValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToNotebooks(command.getAnalyticsWorkspaceId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Notebook as Notebooks to AnalyticsWorkspace" ; 
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Notebook from Notebooks
     * @param		command RemoveNotebooksFromAnalyticsWorkspaceCommand
     * @exception	ProcessingException
     */     	
	public void removeFromNotebooks( RemoveNotebooksFromAnalyticsWorkspaceCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AnalyticsWorkspaceValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromNotebooks(command.getAnalyticsWorkspaceId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getAnalyticsWorkspaceId(); 
			LOGGER.warn(  msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Model to Models 
     * @param		command AssignModelsToAnalyticsWorkspaceCommand
     * @exception	ProcessingException
     */     
	public void addToModels( AssignModelsToAnalyticsWorkspaceCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AnalyticsWorkspaceValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToModels(command.getAnalyticsWorkspaceId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Model as Models to AnalyticsWorkspace" ; 
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Model from Models
     * @param		command RemoveModelsFromAnalyticsWorkspaceCommand
     * @exception	ProcessingException
     */     	
	public void removeFromModels( RemoveModelsFromAnalyticsWorkspaceCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AnalyticsWorkspaceValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromModels(command.getAnalyticsWorkspaceId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getAnalyticsWorkspaceId(); 
			LOGGER.warn(  msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add FeatureSet to FeatureSets 
     * @param		command AssignFeatureSetsToAnalyticsWorkspaceCommand
     * @exception	ProcessingException
     */     
	public void addToFeatureSets( AssignFeatureSetsToAnalyticsWorkspaceCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AnalyticsWorkspaceValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToFeatureSets(command.getAnalyticsWorkspaceId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a FeatureSet as FeatureSets to AnalyticsWorkspace" ; 
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove FeatureSet from FeatureSets
     * @param		command RemoveFeatureSetsFromAnalyticsWorkspaceCommand
     * @exception	ProcessingException
     */     	
	public void removeFromFeatureSets( RemoveFeatureSetsFromAnalyticsWorkspaceCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AnalyticsWorkspaceValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromFeatureSets(command.getAnalyticsWorkspaceId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getAnalyticsWorkspaceId(); 
			LOGGER.warn(  msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add AccessPolicy to Policies 
     * @param		command AssignPoliciesToAnalyticsWorkspaceCommand
     * @exception	ProcessingException
     */     
	public void addToPolicies( AssignPoliciesToAnalyticsWorkspaceCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AnalyticsWorkspaceValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToPolicies(command.getAnalyticsWorkspaceId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a AccessPolicy as Policies to AnalyticsWorkspace" ; 
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove AccessPolicy from Policies
     * @param		command RemovePoliciesFromAnalyticsWorkspaceCommand
     * @exception	ProcessingException
     */     	
	public void removeFromPolicies( RemovePoliciesFromAnalyticsWorkspaceCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AnalyticsWorkspaceValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromPolicies(command.getAnalyticsWorkspaceId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getAnalyticsWorkspaceId(); 
			LOGGER.warn(  msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add LineageNode to LineageNodes 
     * @param		command AssignLineageNodesToAnalyticsWorkspaceCommand
     * @exception	ProcessingException
     */     
	public void addToLineageNodes( AssignLineageNodesToAnalyticsWorkspaceCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AnalyticsWorkspaceValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToLineageNodes(command.getAnalyticsWorkspaceId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a LineageNode as LineageNodes to AnalyticsWorkspace" ; 
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove LineageNode from LineageNodes
     * @param		command RemoveLineageNodesFromAnalyticsWorkspaceCommand
     * @exception	ProcessingException
     */     	
	public void removeFromLineageNodes( RemoveLineageNodesFromAnalyticsWorkspaceCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AnalyticsWorkspaceValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromLineageNodes(command.getAnalyticsWorkspaceId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getAnalyticsWorkspaceId(); 
			LOGGER.warn(  msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}





//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final AnalyticsWorkspaceEntityProjector projector;
	private AnalyticsWorkspace analyticsWorkspace 	= null;
	private CurrentIdentity identity			= null;
    private static final Logger LOGGER 			=  LoggerFactory.getLogger(AnalyticsWorkspaceService.class);
}
