/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>Feature business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of Feature related services in the case of a Feature business related service failing.</li>
 * <li>Exposes a simpler, uniform Feature interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill Feature business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class FeatureService 
extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
    /** 
     * Default Constructor 
     */
    public FeatureService(CurrentIdentity identity)  {

		this.identity	= identity;
    	projector 		= new FeatureEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
							applicationContext.getBean(FeatureRepository.class) );
	}


   /**
	* Feature Business Delegate Factory Method
	*
	* All methods are expected to be self-sufficient.
	*
	* @return 	FeatureService
	*/
	public static FeatureService getFeatureInstance() {
		return( new FeatureService() );
	}
 
   /**
    * Creates the provided command.
    * 
    * @param		command ${class.getCreateCommandAlias()}
    * @exception    ProcessingException
    * @exception	IllegalArgumentException
    * @return		Feature
    */
	public Feature createFeature( CreateFeatureCommand command )
    throws ProcessingException, IllegalArgumentException {

		Feature entity = new Feature();

		try {
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	FeatureValidator.getInstance().validate( command );    

            entity.setFeatureId( command.getFeatureId() );
            entity.setName( command.getName() );
            entity.setDescription( command.getDescription() );
            entity.setDataType( command.getDataType() );
    	    
        	// ------------------------------------------
        	// persist a new one
        	// ------------------------------------------ 
    	    entity = projector.create(entity);
    	    
			LOGGER.info( "done creating of Feature {0} ", entity.toString() );

        }
        catch (Exception exc) {
            final String errMsg = "Unable to create Feature - " + exc;
            LOGGER.warn(  errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }

   /**
    * Update the provided command.
    * @param		command UpdateFeatureCommand
    * @exception    ProcessingException
    * @exception  	IllegalArgumentException
    * @return		Feature
    */
    public Feature updateFeature( UpdateFeatureCommand command ) 
    throws ProcessingException, IllegalArgumentException {

	    Feature entity = new Feature();

    	try {       

			// --------------------------------------
        	// validate 
        	// --------------------------------------    	
        	FeatureValidator.getInstance().validate( command );    

            entity.setFeatureId( command.getFeatureId() );
            entity.setName( command.getName() );
            entity.setDescription( command.getDescription() );
            entity.setFeatureSet( command.getFeatureSet() );
            entity.setSourceDatasets( command.getSourceDatasets() );
            entity.setModels( command.getModels() );
            entity.setTrainingRuns( command.getTrainingRuns() );
            entity.setDataType( command.getDataType() );
        	
        	// ------------------------------------------
        	// persist an existing one
        	// ------------------------------------------ 
        	entity = projector.update(entity);
    	    
			LOGGER.info( "done saving of Feature {0} ", entity.toString() );
    	}
        catch (Exception exc) {
            final String errMsg = "Unable to save Feature - " + exc;
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
    	
    	return entity;
    }
   
   /**
    * Deletes the associatied value object
    * @param		command DeleteFeatureCommand
    * @exception 	ProcessingException
    */
    public void delete( DeleteFeatureCommand command ) 
    throws ProcessingException, IllegalArgumentException {	
        UUID id = null;
        
    	try {  
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	FeatureValidator.getInstance().validate( command );    
        
        	id = command.getFeatureId();
        	
        	// ------------------------------------------
        	// delete the entity
        	// ------------------------------------------
        	projector.delete(id);

        	LOGGER.info( "done deleting of Feature {0} ", id );

        }
        catch (Exception exc) {
            final String errMsg = "Unable to delete Feature using Id = "  + id;
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }
    }

    /**
     * Method to retrieve the Feature via FeatureFetchOneSummary
     * @param 	summary FeatureFetchOneSummary 
     * @return 	FeatureFetchOneResponse
     * @exception ProcessingException - Thrown if processing any related problems
     * @exception IllegalArgumentException 
     */
    public Feature getFeature( FeatureFetchOneSummary summary ) 
    throws ProcessingException, IllegalArgumentException {
    	
    	if( summary == null )
    		throw new IllegalArgumentException( "FeatureFetchOneSummary arg cannot be null" );
    	
    	Feature entity = null;
    	UUID id = summary.getFeatureId();
    	
        try {
        	// --------------------------------------
        	// validate the fetch one summary
        	// --------------------------------------    	
        	FeatureValidator.getInstance().validate( summary );    
        	
        	// --------------------------------------
        	// find a Feature using the provided id
        	// --------------------------------------
        	entity = projector.find( id );
        }
        catch( Exception exc ) {
            final String errMsg = "Unable to locate Feature with id " + id;
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }


    /**
     * Method to retrieve a collection of all Features
     *
     * @return 	List<Feature> 
     * @exception ProcessingException Thrown if any problems
     */
    public List<Feature> getAllFeature() 
    throws ProcessingException {
        List<Feature> list = null;

        try {        	
        	list = projector.findAll( new FindAllFeatureQuery() );
        }
        catch( Exception exc ) {
            String errMsg = "Failed to get all Feature";
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return list;
    }

    /**
     * assign FeatureSet on Feature
     * @param		command AssignFeatureSetToFeatureCommand	
     * @exception	ProcessingException
     */     
	public void assignFeatureSet( AssignFeatureSetToFeatureCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// best to validate the command now
	    	// --------------------------------------    
	    	FeatureValidator.getInstance().validate( command );    

			// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.assignFeatureSet(command.getFeatureId(), command.getAssignment());
		    
		}
        catch( Throwable exc ) {
			final String msg = "Failed to get FeatureSet using id " + command.getFeatureId();
			LOGGER.warn( msg );
			throw new ProcessingException( msg, exc );
        }
	}

    /**
     * unAssign FeatureSet on Feature
     * @param		command UnAssignFeatureSetFromFeatureCommand
     * @exception	ProcessingException
     */     
	public void unAssignFeatureSet( UnAssignFeatureSetFromFeatureCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	FeatureValidator.getInstance().validate( command );    
	
	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.unAssignFeatureSet(command.getFeatureId());
		}
		catch( Exception exc ) {
			final String msg = "Failed to unassign FeatureSet on Feature";
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}
	

    /**
     * add DataSet to SourceDatasets 
     * @param		command AssignSourceDatasetsToFeatureCommand
     * @exception	ProcessingException
     */     
	public void addToSourceDatasets( AssignSourceDatasetsToFeatureCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	FeatureValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToSourceDatasets(command.getFeatureId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a DataSet as SourceDatasets to Feature" ; 
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove DataSet from SourceDatasets
     * @param		command RemoveSourceDatasetsFromFeatureCommand
     * @exception	ProcessingException
     */     	
	public void removeFromSourceDatasets( RemoveSourceDatasetsFromFeatureCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	FeatureValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromSourceDatasets(command.getFeatureId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getFeatureId(); 
			LOGGER.warn(  msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Model to Models 
     * @param		command AssignModelsToFeatureCommand
     * @exception	ProcessingException
     */     
	public void addToModels( AssignModelsToFeatureCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	FeatureValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToModels(command.getFeatureId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Model as Models to Feature" ; 
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Model from Models
     * @param		command RemoveModelsFromFeatureCommand
     * @exception	ProcessingException
     */     	
	public void removeFromModels( RemoveModelsFromFeatureCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	FeatureValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromModels(command.getFeatureId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getFeatureId(); 
			LOGGER.warn(  msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add TrainingRun to TrainingRuns 
     * @param		command AssignTrainingRunsToFeatureCommand
     * @exception	ProcessingException
     */     
	public void addToTrainingRuns( AssignTrainingRunsToFeatureCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	FeatureValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToTrainingRuns(command.getFeatureId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a TrainingRun as TrainingRuns to Feature" ; 
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove TrainingRun from TrainingRuns
     * @param		command RemoveTrainingRunsFromFeatureCommand
     * @exception	ProcessingException
     */     	
	public void removeFromTrainingRuns( RemoveTrainingRunsFromFeatureCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	FeatureValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromTrainingRuns(command.getFeatureId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getFeatureId(); 
			LOGGER.warn(  msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}





//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final FeatureEntityProjector projector;
	private Feature feature 	= null;
	private CurrentIdentity identity			= null;
    private static final Logger LOGGER 			=  LoggerFactory.getLogger(FeatureService.class);
}
