/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>RunMetric business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of RunMetric related services in the case of a RunMetric business related service failing.</li>
 * <li>Exposes a simpler, uniform RunMetric interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill RunMetric business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class RunMetricService 
extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
    /** 
     * Default Constructor 
     */
    public RunMetricService(CurrentIdentity identity)  {

		this.identity	= identity;
    	projector 		= new RunMetricEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
							applicationContext.getBean(RunMetricRepository.class) );
	}


   /**
	* RunMetric Business Delegate Factory Method
	*
	* All methods are expected to be self-sufficient.
	*
	* @return 	RunMetricService
	*/
	public static RunMetricService getRunMetricInstance() {
		return( new RunMetricService() );
	}
 
   /**
    * Creates the provided command.
    * 
    * @param		command ${class.getCreateCommandAlias()}
    * @exception    ProcessingException
    * @exception	IllegalArgumentException
    * @return		RunMetric
    */
	public RunMetric createRunMetric( CreateRunMetricCommand command )
    throws ProcessingException, IllegalArgumentException {

		RunMetric entity = new RunMetric();

		try {
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	RunMetricValidator.getInstance().validate( command );    

            entity.setRunMetricId( command.getRunMetricId() );
            entity.setName( command.getName() );
            entity.setValue( command.getValue() );
    	    
        	// ------------------------------------------
        	// persist a new one
        	// ------------------------------------------ 
    	    entity = projector.create(entity);
    	    
			LOGGER.info( "done creating of RunMetric {0} ", entity.toString() );

        }
        catch (Exception exc) {
            final String errMsg = "Unable to create RunMetric - " + exc;
            LOGGER.warn(  errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }

   /**
    * Update the provided command.
    * @param		command UpdateRunMetricCommand
    * @exception    ProcessingException
    * @exception  	IllegalArgumentException
    * @return		RunMetric
    */
    public RunMetric updateRunMetric( UpdateRunMetricCommand command ) 
    throws ProcessingException, IllegalArgumentException {

	    RunMetric entity = new RunMetric();

    	try {       

			// --------------------------------------
        	// validate 
        	// --------------------------------------    	
        	RunMetricValidator.getInstance().validate( command );    

            entity.setRunMetricId( command.getRunMetricId() );
            entity.setName( command.getName() );
            entity.setValue( command.getValue() );
            entity.setTrainingRun( command.getTrainingRun() );
            entity.setMetric( command.getMetric() );
            entity.setDataset( command.getDataset() );
        	
        	// ------------------------------------------
        	// persist an existing one
        	// ------------------------------------------ 
        	entity = projector.update(entity);
    	    
			LOGGER.info( "done saving of RunMetric {0} ", entity.toString() );
    	}
        catch (Exception exc) {
            final String errMsg = "Unable to save RunMetric - " + exc;
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
    	
    	return entity;
    }
   
   /**
    * Deletes the associatied value object
    * @param		command DeleteRunMetricCommand
    * @exception 	ProcessingException
    */
    public void delete( DeleteRunMetricCommand command ) 
    throws ProcessingException, IllegalArgumentException {	
        UUID id = null;
        
    	try {  
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	RunMetricValidator.getInstance().validate( command );    
        
        	id = command.getRunMetricId();
        	
        	// ------------------------------------------
        	// delete the entity
        	// ------------------------------------------
        	projector.delete(id);

        	LOGGER.info( "done deleting of RunMetric {0} ", id );

        }
        catch (Exception exc) {
            final String errMsg = "Unable to delete RunMetric using Id = "  + id;
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }
    }

    /**
     * Method to retrieve the RunMetric via RunMetricFetchOneSummary
     * @param 	summary RunMetricFetchOneSummary 
     * @return 	RunMetricFetchOneResponse
     * @exception ProcessingException - Thrown if processing any related problems
     * @exception IllegalArgumentException 
     */
    public RunMetric getRunMetric( RunMetricFetchOneSummary summary ) 
    throws ProcessingException, IllegalArgumentException {
    	
    	if( summary == null )
    		throw new IllegalArgumentException( "RunMetricFetchOneSummary arg cannot be null" );
    	
    	RunMetric entity = null;
    	UUID id = summary.getRunMetricId();
    	
        try {
        	// --------------------------------------
        	// validate the fetch one summary
        	// --------------------------------------    	
        	RunMetricValidator.getInstance().validate( summary );    
        	
        	// --------------------------------------
        	// find a RunMetric using the provided id
        	// --------------------------------------
        	entity = projector.find( id );
        }
        catch( Exception exc ) {
            final String errMsg = "Unable to locate RunMetric with id " + id;
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }


    /**
     * Method to retrieve a collection of all RunMetrics
     *
     * @return 	List<RunMetric> 
     * @exception ProcessingException Thrown if any problems
     */
    public List<RunMetric> getAllRunMetric() 
    throws ProcessingException {
        List<RunMetric> list = null;

        try {        	
        	list = projector.findAll( new FindAllRunMetricQuery() );
        }
        catch( Exception exc ) {
            String errMsg = "Failed to get all RunMetric";
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return list;
    }

    /**
     * assign TrainingRun on RunMetric
     * @param		command AssignTrainingRunToRunMetricCommand	
     * @exception	ProcessingException
     */     
	public void assignTrainingRun( AssignTrainingRunToRunMetricCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// best to validate the command now
	    	// --------------------------------------    
	    	RunMetricValidator.getInstance().validate( command );    

			// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.assignTrainingRun(command.getRunMetricId(), command.getAssignment());
		    
		}
        catch( Throwable exc ) {
			final String msg = "Failed to get TrainingRun using id " + command.getRunMetricId();
			LOGGER.warn( msg );
			throw new ProcessingException( msg, exc );
        }
	}

    /**
     * unAssign TrainingRun on RunMetric
     * @param		command UnAssignTrainingRunFromRunMetricCommand
     * @exception	ProcessingException
     */     
	public void unAssignTrainingRun( UnAssignTrainingRunFromRunMetricCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	RunMetricValidator.getInstance().validate( command );    
	
	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.unAssignTrainingRun(command.getRunMetricId());
		}
		catch( Exception exc ) {
			final String msg = "Failed to unassign TrainingRun on RunMetric";
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}
	
    /**
     * assign Metric on RunMetric
     * @param		command AssignMetricToRunMetricCommand	
     * @exception	ProcessingException
     */     
	public void assignMetric( AssignMetricToRunMetricCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// best to validate the command now
	    	// --------------------------------------    
	    	RunMetricValidator.getInstance().validate( command );    

			// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.assignMetric(command.getRunMetricId(), command.getAssignment());
		    
		}
        catch( Throwable exc ) {
			final String msg = "Failed to get Metric using id " + command.getRunMetricId();
			LOGGER.warn( msg );
			throw new ProcessingException( msg, exc );
        }
	}

    /**
     * unAssign Metric on RunMetric
     * @param		command UnAssignMetricFromRunMetricCommand
     * @exception	ProcessingException
     */     
	public void unAssignMetric( UnAssignMetricFromRunMetricCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	RunMetricValidator.getInstance().validate( command );    
	
	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.unAssignMetric(command.getRunMetricId());
		}
		catch( Exception exc ) {
			final String msg = "Failed to unassign Metric on RunMetric";
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}
	
    /**
     * assign Dataset on RunMetric
     * @param		command AssignDatasetToRunMetricCommand	
     * @exception	ProcessingException
     */     
	public void assignDataset( AssignDatasetToRunMetricCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// best to validate the command now
	    	// --------------------------------------    
	    	RunMetricValidator.getInstance().validate( command );    

			// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.assignDataset(command.getRunMetricId(), command.getAssignment());
		    
		}
        catch( Throwable exc ) {
			final String msg = "Failed to get DataSet using id " + command.getRunMetricId();
			LOGGER.warn( msg );
			throw new ProcessingException( msg, exc );
        }
	}

    /**
     * unAssign Dataset on RunMetric
     * @param		command UnAssignDatasetFromRunMetricCommand
     * @exception	ProcessingException
     */     
	public void unAssignDataset( UnAssignDatasetFromRunMetricCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	RunMetricValidator.getInstance().validate( command );    
	
	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.unAssignDataset(command.getRunMetricId());
		}
		catch( Exception exc ) {
			final String msg = "Failed to unassign Dataset on RunMetric";
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}
	





//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final RunMetricEntityProjector projector;
	private RunMetric runMetric 	= null;
	private CurrentIdentity identity			= null;
    private static final Logger LOGGER 			=  LoggerFactory.getLogger(RunMetricService.class);
}
