/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>SemanticModel business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of SemanticModel related services in the case of a SemanticModel business related service failing.</li>
 * <li>Exposes a simpler, uniform SemanticModel interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill SemanticModel business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class SemanticModelService 
extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
    /** 
     * Default Constructor 
     */
    public SemanticModelService(CurrentIdentity identity)  {

		this.identity	= identity;
    	projector 		= new SemanticModelEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
							applicationContext.getBean(SemanticModelRepository.class) );
	}


   /**
	* SemanticModel Business Delegate Factory Method
	*
	* All methods are expected to be self-sufficient.
	*
	* @return 	SemanticModelService
	*/
	public static SemanticModelService getSemanticModelInstance() {
		return( new SemanticModelService() );
	}
 
   /**
    * Creates the provided command.
    * 
    * @param		command ${class.getCreateCommandAlias()}
    * @exception    ProcessingException
    * @exception	IllegalArgumentException
    * @return		SemanticModel
    */
	public SemanticModel createSemanticModel( CreateSemanticModelCommand command )
    throws ProcessingException, IllegalArgumentException {

		SemanticModel entity = new SemanticModel();

		try {
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	SemanticModelValidator.getInstance().validate( command );    

            entity.setSemanticModelId( command.getSemanticModelId() );
            entity.setName( command.getName() );
            entity.setVersion( command.getVersion() );
            entity.setGrain( command.getGrain() );
    	    
        	// ------------------------------------------
        	// persist a new one
        	// ------------------------------------------ 
    	    entity = projector.create(entity);
    	    
			LOGGER.info( "done creating of SemanticModel {0} ", entity.toString() );

        }
        catch (Exception exc) {
            final String errMsg = "Unable to create SemanticModel - " + exc;
            LOGGER.warn(  errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }

   /**
    * Update the provided command.
    * @param		command UpdateSemanticModelCommand
    * @exception    ProcessingException
    * @exception  	IllegalArgumentException
    * @return		SemanticModel
    */
    public SemanticModel updateSemanticModel( UpdateSemanticModelCommand command ) 
    throws ProcessingException, IllegalArgumentException {

	    SemanticModel entity = new SemanticModel();

    	try {       

			// --------------------------------------
        	// validate 
        	// --------------------------------------    	
        	SemanticModelValidator.getInstance().validate( command );    

            entity.setSemanticModelId( command.getSemanticModelId() );
            entity.setName( command.getName() );
            entity.setVersion( command.getVersion() );
            entity.setGrain( command.getGrain() );
            entity.setDatasets( command.getDatasets() );
            entity.setMetrics( command.getMetrics() );
            entity.setDimensions( command.getDimensions() );
            entity.setMeasures( command.getMeasures() );
            entity.setGlossaryTerms( command.getGlossaryTerms() );
        	
        	// ------------------------------------------
        	// persist an existing one
        	// ------------------------------------------ 
        	entity = projector.update(entity);
    	    
			LOGGER.info( "done saving of SemanticModel {0} ", entity.toString() );
    	}
        catch (Exception exc) {
            final String errMsg = "Unable to save SemanticModel - " + exc;
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
    	
    	return entity;
    }
   
   /**
    * Deletes the associatied value object
    * @param		command DeleteSemanticModelCommand
    * @exception 	ProcessingException
    */
    public void delete( DeleteSemanticModelCommand command ) 
    throws ProcessingException, IllegalArgumentException {	
        UUID id = null;
        
    	try {  
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	SemanticModelValidator.getInstance().validate( command );    
        
        	id = command.getSemanticModelId();
        	
        	// ------------------------------------------
        	// delete the entity
        	// ------------------------------------------
        	projector.delete(id);

        	LOGGER.info( "done deleting of SemanticModel {0} ", id );

        }
        catch (Exception exc) {
            final String errMsg = "Unable to delete SemanticModel using Id = "  + id;
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }
    }

    /**
     * Method to retrieve the SemanticModel via SemanticModelFetchOneSummary
     * @param 	summary SemanticModelFetchOneSummary 
     * @return 	SemanticModelFetchOneResponse
     * @exception ProcessingException - Thrown if processing any related problems
     * @exception IllegalArgumentException 
     */
    public SemanticModel getSemanticModel( SemanticModelFetchOneSummary summary ) 
    throws ProcessingException, IllegalArgumentException {
    	
    	if( summary == null )
    		throw new IllegalArgumentException( "SemanticModelFetchOneSummary arg cannot be null" );
    	
    	SemanticModel entity = null;
    	UUID id = summary.getSemanticModelId();
    	
        try {
        	// --------------------------------------
        	// validate the fetch one summary
        	// --------------------------------------    	
        	SemanticModelValidator.getInstance().validate( summary );    
        	
        	// --------------------------------------
        	// find a SemanticModel using the provided id
        	// --------------------------------------
        	entity = projector.find( id );
        }
        catch( Exception exc ) {
            final String errMsg = "Unable to locate SemanticModel with id " + id;
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }


    /**
     * Method to retrieve a collection of all SemanticModels
     *
     * @return 	List<SemanticModel> 
     * @exception ProcessingException Thrown if any problems
     */
    public List<SemanticModel> getAllSemanticModel() 
    throws ProcessingException {
        List<SemanticModel> list = null;

        try {        	
        	list = projector.findAll( new FindAllSemanticModelQuery() );
        }
        catch( Exception exc ) {
            String errMsg = "Failed to get all SemanticModel";
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return list;
    }


    /**
     * add DataSet to Datasets 
     * @param		command AssignDatasetsToSemanticModelCommand
     * @exception	ProcessingException
     */     
	public void addToDatasets( AssignDatasetsToSemanticModelCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	SemanticModelValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToDatasets(command.getSemanticModelId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a DataSet as Datasets to SemanticModel" ; 
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove DataSet from Datasets
     * @param		command RemoveDatasetsFromSemanticModelCommand
     * @exception	ProcessingException
     */     	
	public void removeFromDatasets( RemoveDatasetsFromSemanticModelCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	SemanticModelValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromDatasets(command.getSemanticModelId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getSemanticModelId(); 
			LOGGER.warn(  msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Metric to Metrics 
     * @param		command AssignMetricsToSemanticModelCommand
     * @exception	ProcessingException
     */     
	public void addToMetrics( AssignMetricsToSemanticModelCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	SemanticModelValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToMetrics(command.getSemanticModelId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Metric as Metrics to SemanticModel" ; 
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Metric from Metrics
     * @param		command RemoveMetricsFromSemanticModelCommand
     * @exception	ProcessingException
     */     	
	public void removeFromMetrics( RemoveMetricsFromSemanticModelCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	SemanticModelValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromMetrics(command.getSemanticModelId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getSemanticModelId(); 
			LOGGER.warn(  msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Dimension to Dimensions 
     * @param		command AssignDimensionsToSemanticModelCommand
     * @exception	ProcessingException
     */     
	public void addToDimensions( AssignDimensionsToSemanticModelCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	SemanticModelValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToDimensions(command.getSemanticModelId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Dimension as Dimensions to SemanticModel" ; 
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Dimension from Dimensions
     * @param		command RemoveDimensionsFromSemanticModelCommand
     * @exception	ProcessingException
     */     	
	public void removeFromDimensions( RemoveDimensionsFromSemanticModelCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	SemanticModelValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromDimensions(command.getSemanticModelId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getSemanticModelId(); 
			LOGGER.warn(  msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Measure to Measures 
     * @param		command AssignMeasuresToSemanticModelCommand
     * @exception	ProcessingException
     */     
	public void addToMeasures( AssignMeasuresToSemanticModelCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	SemanticModelValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToMeasures(command.getSemanticModelId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Measure as Measures to SemanticModel" ; 
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Measure from Measures
     * @param		command RemoveMeasuresFromSemanticModelCommand
     * @exception	ProcessingException
     */     	
	public void removeFromMeasures( RemoveMeasuresFromSemanticModelCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	SemanticModelValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromMeasures(command.getSemanticModelId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getSemanticModelId(); 
			LOGGER.warn(  msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add BusinessGlossaryTerm to GlossaryTerms 
     * @param		command AssignGlossaryTermsToSemanticModelCommand
     * @exception	ProcessingException
     */     
	public void addToGlossaryTerms( AssignGlossaryTermsToSemanticModelCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	SemanticModelValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToGlossaryTerms(command.getSemanticModelId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a BusinessGlossaryTerm as GlossaryTerms to SemanticModel" ; 
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove BusinessGlossaryTerm from GlossaryTerms
     * @param		command RemoveGlossaryTermsFromSemanticModelCommand
     * @exception	ProcessingException
     */     	
	public void removeFromGlossaryTerms( RemoveGlossaryTermsFromSemanticModelCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	SemanticModelValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromGlossaryTerms(command.getSemanticModelId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getSemanticModelId(); 
			LOGGER.warn(  msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}





//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final SemanticModelEntityProjector projector;
	private SemanticModel semanticModel 	= null;
	private CurrentIdentity identity			= null;
    private static final Logger LOGGER 			=  LoggerFactory.getLogger(SemanticModelService.class);
}
