/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>Subscriber business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of Subscriber related services in the case of a Subscriber business related service failing.</li>
 * <li>Exposes a simpler, uniform Subscriber interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill Subscriber business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class SubscriberService 
extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
    /** 
     * Default Constructor 
     */
    public SubscriberService(CurrentIdentity identity)  {

		this.identity	= identity;
    	projector 		= new SubscriberEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
							applicationContext.getBean(SubscriberRepository.class) );
	}


   /**
	* Subscriber Business Delegate Factory Method
	*
	* All methods are expected to be self-sufficient.
	*
	* @return 	SubscriberService
	*/
	public static SubscriberService getSubscriberInstance() {
		return( new SubscriberService() );
	}
 
   /**
    * Creates the provided command.
    * 
    * @param		command ${class.getCreateCommandAlias()}
    * @exception    ProcessingException
    * @exception	IllegalArgumentException
    * @return		Subscriber
    */
	public Subscriber createSubscriber( CreateSubscriberCommand command )
    throws ProcessingException, IllegalArgumentException {

		Subscriber entity = new Subscriber();

		try {
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	SubscriberValidator.getInstance().validate( command );    

            entity.setSubscriberId( command.getSubscriberId() );
            entity.setName( command.getName() );
            entity.setAddress( command.getAddress() );
            entity.setChannel( command.getChannel() );
    	    
        	// ------------------------------------------
        	// persist a new one
        	// ------------------------------------------ 
    	    entity = projector.create(entity);
    	    
			LOGGER.info( "done creating of Subscriber {0} ", entity.toString() );

        }
        catch (Exception exc) {
            final String errMsg = "Unable to create Subscriber - " + exc;
            LOGGER.warn(  errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }

   /**
    * Update the provided command.
    * @param		command UpdateSubscriberCommand
    * @exception    ProcessingException
    * @exception  	IllegalArgumentException
    * @return		Subscriber
    */
    public Subscriber updateSubscriber( UpdateSubscriberCommand command ) 
    throws ProcessingException, IllegalArgumentException {

	    Subscriber entity = new Subscriber();

    	try {       

			// --------------------------------------
        	// validate 
        	// --------------------------------------    	
        	SubscriberValidator.getInstance().validate( command );    

            entity.setSubscriberId( command.getSubscriberId() );
            entity.setName( command.getName() );
            entity.setAddress( command.getAddress() );
            entity.setAlerts( command.getAlerts() );
            entity.setChannel( command.getChannel() );
        	
        	// ------------------------------------------
        	// persist an existing one
        	// ------------------------------------------ 
        	entity = projector.update(entity);
    	    
			LOGGER.info( "done saving of Subscriber {0} ", entity.toString() );
    	}
        catch (Exception exc) {
            final String errMsg = "Unable to save Subscriber - " + exc;
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
    	
    	return entity;
    }
   
   /**
    * Deletes the associatied value object
    * @param		command DeleteSubscriberCommand
    * @exception 	ProcessingException
    */
    public void delete( DeleteSubscriberCommand command ) 
    throws ProcessingException, IllegalArgumentException {	
        UUID id = null;
        
    	try {  
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	SubscriberValidator.getInstance().validate( command );    
        
        	id = command.getSubscriberId();
        	
        	// ------------------------------------------
        	// delete the entity
        	// ------------------------------------------
        	projector.delete(id);

        	LOGGER.info( "done deleting of Subscriber {0} ", id );

        }
        catch (Exception exc) {
            final String errMsg = "Unable to delete Subscriber using Id = "  + id;
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }
    }

    /**
     * Method to retrieve the Subscriber via SubscriberFetchOneSummary
     * @param 	summary SubscriberFetchOneSummary 
     * @return 	SubscriberFetchOneResponse
     * @exception ProcessingException - Thrown if processing any related problems
     * @exception IllegalArgumentException 
     */
    public Subscriber getSubscriber( SubscriberFetchOneSummary summary ) 
    throws ProcessingException, IllegalArgumentException {
    	
    	if( summary == null )
    		throw new IllegalArgumentException( "SubscriberFetchOneSummary arg cannot be null" );
    	
    	Subscriber entity = null;
    	UUID id = summary.getSubscriberId();
    	
        try {
        	// --------------------------------------
        	// validate the fetch one summary
        	// --------------------------------------    	
        	SubscriberValidator.getInstance().validate( summary );    
        	
        	// --------------------------------------
        	// find a Subscriber using the provided id
        	// --------------------------------------
        	entity = projector.find( id );
        }
        catch( Exception exc ) {
            final String errMsg = "Unable to locate Subscriber with id " + id;
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }


    /**
     * Method to retrieve a collection of all Subscribers
     *
     * @return 	List<Subscriber> 
     * @exception ProcessingException Thrown if any problems
     */
    public List<Subscriber> getAllSubscriber() 
    throws ProcessingException {
        List<Subscriber> list = null;

        try {        	
        	list = projector.findAll( new FindAllSubscriberQuery() );
        }
        catch( Exception exc ) {
            String errMsg = "Failed to get all Subscriber";
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return list;
    }


    /**
     * add Alert to Alerts 
     * @param		command AssignAlertsToSubscriberCommand
     * @exception	ProcessingException
     */     
	public void addToAlerts( AssignAlertsToSubscriberCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	SubscriberValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToAlerts(command.getSubscriberId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Alert as Alerts to Subscriber" ; 
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Alert from Alerts
     * @param		command RemoveAlertsFromSubscriberCommand
     * @exception	ProcessingException
     */     	
	public void removeFromAlerts( RemoveAlertsFromSubscriberCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	SubscriberValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromAlerts(command.getSubscriberId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getSubscriberId(); 
			LOGGER.warn(  msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}





//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final SubscriberEntityProjector projector;
	private Subscriber subscriber 	= null;
	private CurrentIdentity identity			= null;
    private static final Logger LOGGER 			=  LoggerFactory.getLogger(SubscriberService.class);
}
