/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>Tag business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of Tag related services in the case of a Tag business related service failing.</li>
 * <li>Exposes a simpler, uniform Tag interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill Tag business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class TagService 
extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
    /** 
     * Default Constructor 
     */
    public TagService(CurrentIdentity identity)  {

		this.identity	= identity;
    	projector 		= new TagEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
							applicationContext.getBean(TagRepository.class) );
	}


   /**
	* Tag Business Delegate Factory Method
	*
	* All methods are expected to be self-sufficient.
	*
	* @return 	TagService
	*/
	public static TagService getTagInstance() {
		return( new TagService() );
	}
 
   /**
    * Creates the provided command.
    * 
    * @param		command ${class.getCreateCommandAlias()}
    * @exception    ProcessingException
    * @exception	IllegalArgumentException
    * @return		Tag
    */
	public Tag createTag( CreateTagCommand command )
    throws ProcessingException, IllegalArgumentException {

		Tag entity = new Tag();

		try {
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	TagValidator.getInstance().validate( command );    

            entity.setTagId( command.getTagId() );
            entity.setName( command.getName() );
            entity.setCategory( command.getCategory() );
    	    
        	// ------------------------------------------
        	// persist a new one
        	// ------------------------------------------ 
    	    entity = projector.create(entity);
    	    
			LOGGER.info( "done creating of Tag {0} ", entity.toString() );

        }
        catch (Exception exc) {
            final String errMsg = "Unable to create Tag - " + exc;
            LOGGER.warn(  errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }

   /**
    * Update the provided command.
    * @param		command UpdateTagCommand
    * @exception    ProcessingException
    * @exception  	IllegalArgumentException
    * @return		Tag
    */
    public Tag updateTag( UpdateTagCommand command ) 
    throws ProcessingException, IllegalArgumentException {

	    Tag entity = new Tag();

    	try {       

			// --------------------------------------
        	// validate 
        	// --------------------------------------    	
        	TagValidator.getInstance().validate( command );    

            entity.setTagId( command.getTagId() );
            entity.setName( command.getName() );
            entity.setDatasets( command.getDatasets() );
            entity.setModels( command.getModels() );
            entity.setModelVersions( command.getModelVersions() );
            entity.setDashboards( command.getDashboards() );
            entity.setReports( command.getReports() );
            entity.setFeatureSets( command.getFeatureSets() );
            entity.setMetrics( command.getMetrics() );
            entity.setCategory( command.getCategory() );
        	
        	// ------------------------------------------
        	// persist an existing one
        	// ------------------------------------------ 
        	entity = projector.update(entity);
    	    
			LOGGER.info( "done saving of Tag {0} ", entity.toString() );
    	}
        catch (Exception exc) {
            final String errMsg = "Unable to save Tag - " + exc;
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
    	
    	return entity;
    }
   
   /**
    * Deletes the associatied value object
    * @param		command DeleteTagCommand
    * @exception 	ProcessingException
    */
    public void delete( DeleteTagCommand command ) 
    throws ProcessingException, IllegalArgumentException {	
        UUID id = null;
        
    	try {  
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	TagValidator.getInstance().validate( command );    
        
        	id = command.getTagId();
        	
        	// ------------------------------------------
        	// delete the entity
        	// ------------------------------------------
        	projector.delete(id);

        	LOGGER.info( "done deleting of Tag {0} ", id );

        }
        catch (Exception exc) {
            final String errMsg = "Unable to delete Tag using Id = "  + id;
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }
    }

    /**
     * Method to retrieve the Tag via TagFetchOneSummary
     * @param 	summary TagFetchOneSummary 
     * @return 	TagFetchOneResponse
     * @exception ProcessingException - Thrown if processing any related problems
     * @exception IllegalArgumentException 
     */
    public Tag getTag( TagFetchOneSummary summary ) 
    throws ProcessingException, IllegalArgumentException {
    	
    	if( summary == null )
    		throw new IllegalArgumentException( "TagFetchOneSummary arg cannot be null" );
    	
    	Tag entity = null;
    	UUID id = summary.getTagId();
    	
        try {
        	// --------------------------------------
        	// validate the fetch one summary
        	// --------------------------------------    	
        	TagValidator.getInstance().validate( summary );    
        	
        	// --------------------------------------
        	// find a Tag using the provided id
        	// --------------------------------------
        	entity = projector.find( id );
        }
        catch( Exception exc ) {
            final String errMsg = "Unable to locate Tag with id " + id;
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }


    /**
     * Method to retrieve a collection of all Tags
     *
     * @return 	List<Tag> 
     * @exception ProcessingException Thrown if any problems
     */
    public List<Tag> getAllTag() 
    throws ProcessingException {
        List<Tag> list = null;

        try {        	
        	list = projector.findAll( new FindAllTagQuery() );
        }
        catch( Exception exc ) {
            String errMsg = "Failed to get all Tag";
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return list;
    }


    /**
     * add DataSet to Datasets 
     * @param		command AssignDatasetsToTagCommand
     * @exception	ProcessingException
     */     
	public void addToDatasets( AssignDatasetsToTagCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	TagValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToDatasets(command.getTagId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a DataSet as Datasets to Tag" ; 
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove DataSet from Datasets
     * @param		command RemoveDatasetsFromTagCommand
     * @exception	ProcessingException
     */     	
	public void removeFromDatasets( RemoveDatasetsFromTagCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	TagValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromDatasets(command.getTagId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getTagId(); 
			LOGGER.warn(  msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Model to Models 
     * @param		command AssignModelsToTagCommand
     * @exception	ProcessingException
     */     
	public void addToModels( AssignModelsToTagCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	TagValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToModels(command.getTagId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Model as Models to Tag" ; 
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Model from Models
     * @param		command RemoveModelsFromTagCommand
     * @exception	ProcessingException
     */     	
	public void removeFromModels( RemoveModelsFromTagCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	TagValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromModels(command.getTagId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getTagId(); 
			LOGGER.warn(  msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add ModelVersion to ModelVersions 
     * @param		command AssignModelVersionsToTagCommand
     * @exception	ProcessingException
     */     
	public void addToModelVersions( AssignModelVersionsToTagCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	TagValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToModelVersions(command.getTagId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a ModelVersion as ModelVersions to Tag" ; 
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove ModelVersion from ModelVersions
     * @param		command RemoveModelVersionsFromTagCommand
     * @exception	ProcessingException
     */     	
	public void removeFromModelVersions( RemoveModelVersionsFromTagCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	TagValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromModelVersions(command.getTagId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getTagId(); 
			LOGGER.warn(  msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Dashboard to Dashboards 
     * @param		command AssignDashboardsToTagCommand
     * @exception	ProcessingException
     */     
	public void addToDashboards( AssignDashboardsToTagCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	TagValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToDashboards(command.getTagId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Dashboard as Dashboards to Tag" ; 
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Dashboard from Dashboards
     * @param		command RemoveDashboardsFromTagCommand
     * @exception	ProcessingException
     */     	
	public void removeFromDashboards( RemoveDashboardsFromTagCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	TagValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromDashboards(command.getTagId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getTagId(); 
			LOGGER.warn(  msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Report to Reports 
     * @param		command AssignReportsToTagCommand
     * @exception	ProcessingException
     */     
	public void addToReports( AssignReportsToTagCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	TagValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToReports(command.getTagId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Report as Reports to Tag" ; 
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Report from Reports
     * @param		command RemoveReportsFromTagCommand
     * @exception	ProcessingException
     */     	
	public void removeFromReports( RemoveReportsFromTagCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	TagValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromReports(command.getTagId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getTagId(); 
			LOGGER.warn(  msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add FeatureSet to FeatureSets 
     * @param		command AssignFeatureSetsToTagCommand
     * @exception	ProcessingException
     */     
	public void addToFeatureSets( AssignFeatureSetsToTagCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	TagValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToFeatureSets(command.getTagId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a FeatureSet as FeatureSets to Tag" ; 
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove FeatureSet from FeatureSets
     * @param		command RemoveFeatureSetsFromTagCommand
     * @exception	ProcessingException
     */     	
	public void removeFromFeatureSets( RemoveFeatureSetsFromTagCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	TagValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromFeatureSets(command.getTagId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getTagId(); 
			LOGGER.warn(  msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Metric to Metrics 
     * @param		command AssignMetricsToTagCommand
     * @exception	ProcessingException
     */     
	public void addToMetrics( AssignMetricsToTagCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	TagValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToMetrics(command.getTagId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Metric as Metrics to Tag" ; 
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Metric from Metrics
     * @param		command RemoveMetricsFromTagCommand
     * @exception	ProcessingException
     */     	
	public void removeFromMetrics( RemoveMetricsFromTagCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	TagValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromMetrics(command.getTagId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getTagId(); 
			LOGGER.warn(  msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}





//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final TagEntityProjector projector;
	private Tag tag 	= null;
	private CurrentIdentity identity			= null;
    private static final Logger LOGGER 			=  LoggerFactory.getLogger(TagService.class);
}
